github/github.py

github integration doesn't work with remote urls that to not end on ".git".
users like me who tend to clone repos by just copy and pasting the address line out of the browser into the terminal would be affected by this issue.

Conditional check if remote url ends with .git

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
core/commands/commit.py

Partial fix for #36, this will sign-off commits by hitting <kbd>Super</kbd>+<kbd>s</kbd>.
As with my previous PR, this will need proof-checking, I'm still quite new to Python.

Add a keybinding to the commit view to easily sign off commits

---

core/commands/inline_diff.py

Check out this fix when you have a chance. Not sure what necessitated the region-end as you had it before, but this seems to work for several different types of diffs I tested....

Avoid empty sublime.Region for removed newline. Closes #61.

---

core/commands/push.py

I moved `do_push` outside of the classes (since they all use something like this) and turned all calls of it (and `self.push`) into calling it asynchronously.
I was thinking of moving it even further away (maybe into the mixins) since other files might make use of it as well. And while on that train of thought I was also thinking of maybe moving every occurrence of the following block of code just the same.
```Python
self.remotes = list(self.get_remotes().keys())
if not self.remotes:
self.window.show_quick_panel([NO_REMOTES_MESSAGE], None)
else:
self.window.show_quick_panel(
self.remotes,
self.on_select_remote,
flags=sublime.MONOSPACE_FONT
)
```

Don't lock up the panels/inputs while pushing

---

core/git_mixins/active_branch.py

The idea here is not to validate a branch's name, but to parse it from the
git status output. Git will not allow a branch to be created with an
invalid name. Thus what I've tried to do is to create a simple regex that
will recognize any valid branch, while not worrying about each branch
naming rule at http://git-scm.com/docs/git-check-ref-format#_description.
Closes https://github.com/divmain/GitSavvy/issues/75.

Sacrifice specificity for sensitivity in status view branch pattern

---

core/commands/status.py
core/git_mixins/active_branch.py
syntax/status.YAML-tmLanguage
syntax/status.tmLanguage

Switching to GitSavvy from SublimeGit one small feature I and possibly others might find useful to is having a quick reference to the HEAD current commit SHA1 and commit msg as part of the status view. I find this handy for info about the most recent commit as well as when I am cherry picking the latest commit I can easily grab the SHA1 I'll be cherry picking before switching branches to do so.

Adding head SHA1 and abbreviated commit msg to status view

---

core/commands/log_graph.py

Add `--all` to `graph` log command so that other branches become visible.
This is helpful in branched workflow (e.g. git-flow) where after a pull on master one needs to see how feature branches have diverged.
Screenshot:

Add `--all` to graph command to show other branches (esp. origin)

---

GitSavvy.sublime-settings
core/commands/inline_diff.py
docs/staging.md

Hello again!
This PR makes GitSavvy automatically scroll to the first found diff on the file:
**before**
**after**
I don't know if this is a something you had in mind for the package but I find it very useful.
Let me know if you need me to change anything,
Thanks!

Scroll to first diff (inline)

---

core/commands/blame.py

fix: regex for matching blame dividers is broken

---

GitSavvy.sublime-settings
core/commands/commit.py

So that one can display a commit rule/tip/convention to the team when they commit, something like this:

Add an option to append customized message to the default commit help.

---

core/git_mixins/branches.py

Existing regex didn't match branch names like 'v1.1' or 'release/v1.1'. If you checkout or create a branch with `.` in the name, it will display correctly as the active branch, but won't appear in the list of local or remote branches:

fix: BranchesMixin regex doesn't match branch names with dots

---

core/interfaces/rebase.py
docs/rebase.md

Some branching models (e.g. [gitflow](http://nvie.com/posts/a-successful-git-branching-model/)) use something other than `master` as an integration branch. In my case, I'm integrating against a branch called `dev` and only merging to `master` when I'm doing a stable release. This means that when I open the rebase dashboard I always need to switch base ref.
As the appropriate default base ref varies from repository to repository, I think a per-project setting in a project's `.sublime-project` file is the best place to override the default base ref. In the absence of this setting, or an active `.sublime-project`, I've retained the default behaviour of defaulting to `master`

feature: per-project default rebase base ref

---

core/git_mixins/active_branch.py

In my previous commit 6b5fd98c `_get_branch_status_components` was updated to return a seventh value (boolean indicating if the remote branch was gone), but `get_branch_status_short` wasn't updated to unpack this value.
Sorry, I really should have checked for additional calls to `get_branch_status_short`!

fix: get_branch_status_short should unpack gone value

---

common/util/__init__.py

Since 983cf67 Linux key map has used `CTRL` instead of `SUPER`, but `common.util.super_key` was still set to `SUPER` on Linux as `os.name == 'posix'` is `true` on both Linux and OS X. Condition changed to `sys.platform == 'darwin'` which is only true on OS X.
Closes #190.

Fix: super_key should be set to CTRL on Linux

---

core/commands/diff.py
core/commands/log.py
docs/history.md

When the `show_log_output_options` setting is set to `true`, on selection of a commit from the `git: log` quick panel, a user can choose from the following options:
`Show commit`: Display the commit
`Show diff`: Display the diff between the commit and the working tree
`Show diff (cached)`: Display the diff between the commit and staged changes
Closes #172

Feature: Display diffs against commit history from `git: log`

---

core/git_mixins/remotes.py

The fetch `All remotes.` option currently does not fetch all remotes (watch the upstream remote below):
The GitSavvy `RemotesMixin.fetch` function expects git to fetch all remotes if a remote isn't specified, but according to the git docs it will default to `origin`:
```
When no remote is specified, by default the origin remote will be used,
unless there’s an upstream branch configured for the current branch.
```
http://git-scm.com/docs/git-fetch/2.4.0
To fix I've appended the `--all` option if remote is falsey.

Fix: Git fetch with remotes=None should append --all option

---

Default.sublime-commands
core/commands/__init__.py
core/commands/reset.py
docs/misc.md

I've made a first attempt at a git reset feature (closes #200). Feedback welcomed :smile: 
Adds two git reset commands to the command panel:
- `git: reset`: Displays the commit selector from `git: log`, selecting a commit performs a `git reset --mixed` to that commit.
- `git: reset (reflog)` Displays a reference log selector, selecting a reference performs a `git reset --mixed` to the referenced commit. This allows you to reset an earlier reset or a rebase.
Reflog quick panel:
The reflog option could be confusing to less advanced git users. I personally would find it useful, on occasion I've reset one or two commits too far, and it would be nice if I could quickly undo that without returning to the terminal. If it's more trouble than it's worth though, I'm happy to take it out.
Doc …

Feature: git reset, using log or reflog

---

syntax/status.YAML-tmLanguage
syntax/status.tmLanguage

Matching regex for meta.git-savvy.status.saved_stash did not include end of line.
Closes #196.

Fix: Stash shortcuts do not execute when cursor is at end of line

---

Default.sublime-keymap
syntax/rebase.YAML-tmLanguage
syntax/rebase.tmLanguage

@divmain I've checked the other key binding contexts as we discussed in #202
| Key binding context                                           | Syntax file                | Pattern captures line endings |
|---------------------------------------------------------------|----------------------------|-----------------------------------------|
| meta.git-savvy.status.file                                   | status.tmLanguage  | Yes
| meta.git-savvy.tags.tag                                     | tags.tmLanguage     | Yes
| meta.git-savvy.status.saved_stash                   | status.tmLanguage  | Yes
| meta.git-savvy.rebase-graph.entry                   | rebase.tmLanguage | Yes
| keyword.other.name.git-savvy.rebase-conflict | rebase.tmLanguage | No
| meta.link.inline.markdown …

Fix: rebase dashboard shortcuts

---

CONTRIBUTE.md

Added info to contributer guidelines regarding commit message structure as mentioned in [this comment](https://github.com/divmain/GitSavvy/pull/206#issuecomment-114359322).

Mention preferred commit message structure

---

GitSavvy.sublime-settings
core/commands/commit.py

* display prompt by default
* allow toggling behavior with "prompt_on_abort_commit" setting
* always set to scratch on commit (no need to prompt)
Coming in from writing commit message with command line editors,
quitting the view mid-commit is always considered dirty in my mind.
And so I often found myself closing a commit by habit and losing
changes without recover options. 
I've considered different solutions for this problem but could not
find anything as simple that worked for me until now.
The same behavior is also used in by the popular plugin "sublime git"
which is where some users come from (including myself).
This is a simple change, however if anyone wants to change anything
about this behavior or make it disabled by default, please let me know
and I'll amend the PR.

Prompt before discarding commit message

---

Default.sublime-keymap
core/commands/log_graph.py
core/interfaces/branch.py
docs/branch_mgmt.md

I created `f + m` in branch interface. This displays a graph of commits that on one of the branches but not  on the active. It have all the same functions as graph view have. Not sure if that is good or bad.
it looks like this: 
This is not done completed but I would like to get you feedback.

Diff commit on branch

---

Default.sublime-commands
core/commands/__init__.py
core/commands/flow.py
docs/README.md
docs/flow.md

Add support for the most common commands as simple window commands, as initially requested in #43.
This is still *work in progress*.
What remains to be done:
- ~~Feature commands: `checkout`, `diff` and `rebase`~~ (not really more useful within GitSavvy)
About the dashboard, I feel less of a need for it right now. The `branch` dashboard provides an overview of everything I'm looking for, and when I actually need to interact with the branches, running a git command is simple. Also, I'm not really sure how dashboards even work yet.
Closes #43. _(edit)_

Feature: add `git-flow` commands

---

core/git_mixins/branches.py

Fixed branch matching regex so it matches remote branch names containing dots.
**Before:**
**After:**

Bug: Branch matching regex did not match dots in remote branch name

---

GitSavvy.sublime-settings
core/commands/flow.py
docs/flow.md

Git-flow commands are only functional if the [git-flow Git extenstions](https://github.com/nvie/gitflow) are installed. Added a setting to hide `flow: *` commands for users who don't use git-flow.

Enhancement: Add setting to hide git-flow commands

---

docs/flow.md

Docs updated as `show_git_flow_commands` is now false by default.

Enhancement: Updated git-flow documentation

---

GitSavvy.sublime-settings
core/git_command.py

On Windows, git isn't always in PATH, requiring you to set git_path for GitSavvy to work correctly.  For users that sync settings across platforms, this allows git_path to be (optionally) customized on a per-platform basis.

Allowing git_path to be customized on a per-platform basis.

---

core/commands/blame.py
docs/history.md

This adds additional options to the git blame view. I occasionally "blame" the wrong person for a change, because they fixed indentation, moved a function within a file, or broke a large file up into smaller files. When using git blame from the command line I can use the `-w`, `-M` and `-C` flags to find the last real change to a line. This adds similar functionality to GitSavvy.

Enhancement: Additional git blame display options

---

Default.sublime-commands

Fix: Rename logging commands

---

core/commands/custom.py

Without this fix, running a custom command raises the following exception:
Traceback (most recent call last):
File ".../Sublime Text 3/Packages/GitSavvy/core/commands/custom.py", line 18, in <lambda>
sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
File ".../Sublime Text 3/Packages/GitSavvy/core/commands/custom.py", line 29, in run_async
for idx, arg in args:
ValueError: too many values to unpack (expected 2)

Bug: properly iterate over an enumerated argument list

---

core/commands/custom.py

There's no documentation, I just wanted to pitch the idea first.
The custom commands work well for short duration commands; however, for long running commands the
plugin is blocked in the `subprocess` `communicate()` call (polling for stdout/err).

Feature: simple background thread for custom commands

---

core/git_command.py

When looking up the repo_path in git_command, it was possible to find a non-existing path that would make everything fail. This verified the path it find exists and if not, it will go the long way round to try to find one.

Added an extra check when looking up the gitsavvy repo_path

---

core/interfaces/status.py

As explained in https://github.com/divmain/GitSavvy/issues/240, navigation to stashes with `gs_status_navigate_file` is currently not possible. This can be a problem when all navigation inside git status is bound to that action and not to arrow keys anymore.

Added navigation to stashes to `NavigateFileCommand`

---

core/commands/checkout.py
core/git_mixins/branches.py

closes divmain/GitSavvy#251
simply just remove the \b. (if you don't remember like me) \b mean that is should be end of a string and have a *blank* character after. Therefor it did not match `some-name-`. It exist \B that is  the opposite of \b. So it it matches with a symbol like -+!~@#$% etc..
I did not see why it was needed. I guess there were some reason it got added there, so. Do any of you remember why?

Fix: branch names ending on -

---

Default.sublime-keymap
core/commands/log_graph.py

Did not nuke the position since you are refreshing to see the new commits
and the new commits will be on top of the graph
closes #259

Improve: Git Graph has refresh function

---

syntax/graph.YAML-tmLanguage
syntax/graph.tmLanguage

I change regex from `(.*)` to `([^()]*)` since than it only match what is should match
Now reqex expect '(' than character other than '()' ')'
```
xxxxxx2 (master)(2 hours ago) by `Simon` Type: change(removes type) to => two
new     ^^^^^^^^^^^^^^^^^^^^^
old     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xxxxxx1 (1 hours ago) by `Simon` My  message is awsome :)
new     ^^^^^^^^^^^^^
old     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Fix: Syntax for graph

---

Default.sublime-keymap
core/interfaces/__init__.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
core/interfaces/tags.py
syntax/branch.YAML-tmLanguage
syntax/branch.tmLanguage
syntax/status.YAML-tmLanguage
syntax/status.tmLanguage
syntax/tags.YAML-tmLanguage
syntax/tags.tmLanguage

Tab cycling through dashboards is an awesome thing, but there was no way to go back to the previous one and in the discussion in #261 it was mentioned briefly as an issue but wasn't really resolved as the discussion there went in a different direction.
Why not just remove the unnecessary dashboards through the config? Unless you remove everything but two dashboards, this still is a nice enhancement to have.
This adds the keybinding (as is common, if I cycle one way with tab then shift-tab should cycle it back) and lists it in the various dashboards (with proper syntax coloring).
I've used [SHIFT-tab] in the dashboard keybinding lists, to be in line with [SUPER-Z] keybindings in the rebase dashboard.

Enhancement: shift-tab to cycle dashboards in reverse

---

docs/README.md

Small nitpicky fix, comment in settings JSON example used python comment delimiter `#` instead of JS comment delimiter `//`. Additionally, comments aren't valid syntax in a Github Flavoured Markdown `json` code blocks, so changed the highlighting mode to `javascript`.

Fix: Incorrect syntax highlighting in docs/README.md

---

GitSavvy.sublime-settings
core/commands/reset.py
docs/misc.md

This commit adds an extra step to the `git: reset` and `git: reset (reflog)` commands that prompts for the git reset mode (e.g. --soft, --hard). By default this step is disabled, and can be enabled by setting `prompt_for_reset_mode` to `true` in GitSavvy.sublime-settings.
Closes #304

Enhancement: Prompt for git reset mode

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
core/commands/commit.py

This PR attempts to fix #293 by explicitly passing the message on view close. It is my understanding that when run_async is called, the original view is not guaranteed to exist anymore, hence the exception seen by @laggingreflex.
Additionally, I made sure that `prompt_on_abort_commit` setting does not prevent `commit_on_close` setting, as well as added a condition to Super/Ctrl+Enter keymap to prevent GitSavvy from attempting a double commit.

Better commit on close behavior

---

core/git_command.py

If the repo is symlinked and the file opened from the symlinked directory, `get_rel_path` doesn't work.
`self.repo_path` shows the real directory but `path` is in terms of the symlink directory.

fix get_rel_path

---

Default.sublime-commands
core/interfaces/tags.py

**tl;dr** "quick tag" is not quick enough.
Smart tag by adding one to to the right part of the last tag.
For example, if the last tag is "v0.4.5", "tag patch" yields "v0.4.6", "tag minor" yields "v0.5.0" and "tag major" yeilds "v1.0.0".

Feature: smart tag based on semantic versioning

---

Default.sublime-commands
core/git_mixins/tags.py
core/interfaces/tags.py

Two changes.
1. add per-release support, if the last tag is in form of `2.3.5-alpha.1`, `0.7.2-rc.10`, the last set of number will be increased by one: `1.4.6-alpha` to `1.4.6-alpha.1` and `2.3.5-rc.1` to `2.3.5-rc.2`.
2. the `tagname` passes to `show_input_panel` instead of running `on_entered_name` directly. It gives user a chance to modify the tag 
These things may be worth discussions:
1. How we should allow user to jump from a pre-release to a regular release. For example, if the last tag is 
`0.7.2-rc.10`, should "git: quick tag patch" yields "0.7.2"? how about "tag minor" and "tag major"?
2. on the other hand, if the last tag is a regular release, say `1.4.6`, should "git: quick tag prerelease" yields `1.4.6-alpha`? how about "beta" and "rc"?
3. other forms of prereleases? there is …

prerelease tag name support

---

core/git_mixins/tags.py

Catch error when the git repo doesn't have any tags.

Fix: get_lastest_local_tag

---

core/commands/__init__.py
core/commands/tag.py
core/interfaces/tags.py

`GsTagCreateCommand` and `GsSmartTagCommand` are not interface-related commands, they should be placed under the `core.command` submodule.

move tag commands out of interfaces

---

core/commands/tag.py

`patch` and `prerelease` are more frequently used then other options.

reorder smart tag order list

---

core/git_mixins/tags.py

this allows tagging different smart-tags on stable and dev branches.
For example, the stable is tagging v1.2.3 while the dev branch, the next major version, is tagging v2.0.0-1.
This is essentially the PR #333  without the dead code.

check tags on current branch only

---

syntax/branch.YAML-tmLanguage
syntax/branch.tmLanguage
syntax/rebase.YAML-tmLanguage
syntax/rebase.tmLanguage
syntax/status.YAML-tmLanguage
syntax/status.tmLanguage
syntax/tags.YAML-tmLanguage
syntax/tags.tmLanguage

Git will only generate short SHA1 refs that are 7 characters long if the 7 character ref is unambiguous. For larger repositories Git will begin to generate larger short SHA1 refs to keep refs unambiguous. This fix allows GitSavvy to correctly highlight refs longer than 7 characters.
See http://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1 for more information.
Closes #323.

Fix: Syntax files don't match short SHA1 refs longer than 7

---

core/commands/custom.py
docs/README.md
docs/custom.md

This will allow for more dynamic commands to be created.
I moved custom command documentation to it's own custom.md file since it started to grow too much for README index IMO, and also added some more custom command examples to the doc.

Feature: allow prompt to specify custom command argument

---

core/commands/blame.py
syntax/blame.YAML-tmLanguage
syntax/blame.tmLanguage

This pull request changes the blame command to not output unnecessary trailing spaces, if the [Trailing Spaces](https://github.com/SublimeText/TrailingSpaces) package is installed it is quite noticeable.
Before:
After:
A superfluous assignment of the variable `total_lines` is also removed.

Avoid printing trailing spaces from blame output

---

syntax/blame.YAML-tmLanguage
syntax/blame.tmLanguage

This enables syntax highlighting for line separators of commit messages spanning 40-48 characters to match what `blame.py` outputs.
For example in commit 40cdf58 the maximum commit line length of `core/git_command.py` is 48 characters and for `core/commands/blame.py` is 40 characters. This causes line separators to be either white or grey (which both look okay).

Syntax highlighting for blame output

---

core/commands/status_bar.py

Status bar is erased when there is no view because `self.file_path` is empty. In fact, there is no need to check `self.file_path` because `self._repo_path` already checks that the directory is a git repo.
There is also side effect, not sure if it is a good/bad thing. Status-bar is now shown also in the dashboard pages.
fix #356

show git status in status-bar when there is no view.

---

GitSavvy.tmPreferences
syntax/branch.sublime-syntax
syntax/diff.sublime-syntax
syntax/graph.sublime-syntax
syntax/rebase.sublime-syntax
syntax/show_commit.sublime-syntax
syntax/status.sublime-syntax
syntax/tags.sublime-syntax

Feature: Use `Goto Symbol` to navigate in all views
We use .tmPreferences to define witch scopes that should be added to SymbolList, by using a custom scope like `gitsavvy.totosymbol` it can not match any other scopes unless the is a theme defines this scope. So all view will look the same way that are doing now.

Goto symbol

---

core/commands/checkout.py
core/commands/pull.py
core/commands/push.py
core/git_mixins/remotes.py
core/interfaces/branch.py
github/commands/configure.py
github/commands/pull_request.py

I have renamed `list_remote_branches` to `get_remote_branches` and upgraded the related code 4e3f012.
> `get_branches` and `get_remote_branches` have similar names but have very different outputs.
`get_branches` returns a named tuple `Branch` and `get_remote_branches` returns a list of remote branches names. In order to reduce confusion, `get_remote_branches` is renamed
as `list_remote_branches`. `list_remote_branches` also has a new argument `remote` which
filters the results with a specified remote.
Also, `create pull request` now checks if remote tracking branch has been set.
PS: `on_select_remote` and `on_select_branch` have been used several times, but I couldn't find a easy way to reuse the code.

Improve `create pull request` and rename the function `get_remote_branches`

---

core/git_command.py

`last_remote_used ` would return the active tracking remote if last remote is not set.

use active remote if empty

---

core/git_mixins/ignore.py

Enhancement: Don't add "# added by GitSavvy" to .gitignore files

---

git_savvy.py

Detail: `util.file.determine_syntax_files` has been significantly slowing down the start up time of Sublime Text (at least 6 seconds on my computer).
Solution: use `set_timeout_async` to run it.

Improve: the slow startup time

---

core/commands/blame.py

Git commit names can contain decomposed Unicode, which causes line length calculation to be incorrect for the output of the blame command. In the below example the "ö" in "Schöne decomposed" is `\x6F\xCC\x88` but in "Schöne original" it is `\xC3\xB6`.
The solution is to normalize the Unicode of the output from the git blame command.
Before:
After:

Ensure Unicode is not decomposed

---

Default.sublime-keymap
common/util/view.py
core/commands/__init__.py
core/commands/branch_commit_history.py
core/commands/cherry_pick.py
core/commands/log.py
core/git_command.py
core/interfaces/branch.py
docs/branch_mgmt.md

closes #11
Some of the changes is so Branch Commit Comparison view can be refreshed.
Read my comment on core/commands/cherry_pick.py L28.
Maybe I can rewrite the cherrypick to be defined in BranchesMixin instead, and call that one. This way I we don't need to call the asynk call.

Feature: Cherry-pick from Branch Commit Comparison view

---

common/commands/debug.py
common/util/__init__.py
common/util/reload.py

This PR implements reloading modules in a more robust and reliable way using import hooks. The key feature is that the modules get reloaded in the very same order they would be loaded during fresh startup.
Here's a part of debug output showing the proper reload sequence (I don't include debug trace facilities for now though, that is a subject for a separate PR):
```
GS [reload] begin ══════════════════════════════════════════════════════
reloading plugin GitSavvy.git_savvy
GS [reload]  ┡━─ GitSavvy.git_savvy
GS [reload]  ╿ ┡━─ GitSavvy.common
GS [reload]  ╿ ┡━─ GitSavvy.common.commands
GS [reload]  ╿ ╿ ┡━─ GitSavvy.common.commands.debug
GS [reload]  ╿ ╿ ╿ ┡━─ GitSavvy.common.util
GS [reload]  ╿ ╿ ╿ ╿ ┡━─ GitSavvy.common.util.parse_diff
GS [reload]  ╿ ╿ ╿ ╿ ┡━─ GitSavvy.common.util.dates …
```

dev_mode: Reliable plugin reloads

---

core/commands/commit.py
syntax/branch.sublime-syntax
syntax/make_commit.sublime-syntax
syntax/rebase.sublime-syntax
syntax/status.sublime-syntax
syntax/tags.sublime-syntax

These are subtle syntax changes to be able to write a better color scheme and create a better UI
-  Adding a spacial scope to the last `-` of the key-binding-menu
-  The extra \n helps the background color set by color scheme to expand to the
end of viewport.
-    better commit help section
- The extra \n helps the background color set by color scheme to expand to
the end of viewport.
- the spacing between help section is replace with empty ## to be captured
by syntax and colored as a single section by color scheme

Syntax improvements for custom color schemes

---

core/commands/inline_diff.py

* this view relies heavily on keyboard interaction, it only makes sense
to enable insert mode if we're vintageous friendly

Handle Vintageous in Inline Diff

---

common/theme_generator.py

Preventing generated color schemes to appear in Sublime's color scheme menu.
This is a trick that sublime itself uses to hide some color schemes and syntaxes

Preventing generated color schemes to appear

---

core/commands/custom.py

As title.
Also replace \r by \n in output panel.

Fix: refresh status bar after custom git command

---

core/interfaces/status.py
github/commands/open_on_remote.py
github/git_mixins/remotes.py

`github: open file` and `open repo` are now remote sensitive. They will check if the current tracking remote is the same as the integrated remote. If they are the same (or there is only one remote), the browser will be opened directly. Otherwise, the list of remotes will be displayed to choose from.
depends on #459 
close #335

Enhancement: github: open file and open repo

---

github/commands/configure.py
github/commands/pull_request.py
github/git_mixins/remotes.py

This is needed to produce a correct comparision when the integered
remote is a forked remote.
For example, if the integrated remote is configed as randy3k,
the original code opens
https://github.com/randy3k/GitSavvy/compare/randy3k:comparision?expand=1
However, github redirects it to
https://github.com/divmain/GitSavvy/compare/master...randy3k:comparision?expand=1
To adderss the issue, the new link used is
https://github.com/randy3k/GitSavvy/compare/randy3k:master...randy3k:comparision?expand=1

Enhancement: add github integration config GitSavvy.ghBranch

---

Default.sublime-keymap

df95ea3f7276bb5b50bbdf79f3064ff5b8054a55 did not allow remote tags.

Fix: allow remote tags using gs_tag_delete and gs_tag_view_log

---

git_savvy.py

It seems that sublime.set_timeout_async still slow down the start up of
Sublime Text. For instance, the quick panel (e.g., `git: log`) is not ready until a few second
after ST opens. I suspect that they share the same second thread.
Changing `sublime.set_timeout_async` to `threading.Thread` so that the quick panel
(and other UI) does not have to wait for util.file.determine_syntax_files

Enhancedment: use thread.Thread to execute util.file.determine_syntax_files

---

GitSavvy.sublime-settings
core/commands/log.py
core/commands/log_graph.py
core/git_command.py

- Copy the full SHA in log quick panel
- Show commit in output panel while scrolling the log quick panel
- fix default indexes

Feature: Copy the full SHA and show commit in log quick panel

---

core/commands/quick_stage.py

I don't know if it makes sense or not. But I think it is more intuitive to call `git: quick commit` other than `git: commit` in `quick stage`.

Enhancement: use quick commit instead of commit

---

core/commands/quick_stage.py
core/git_mixins/status.py
core/interfaces/status.py

move to `sort_status_entries` to mixins and use `sort_status_entries` to fix `quick stage` issues of handling merge conflicts.

Fix: quick stage handles merge conflicts

---

core/commands/log.py

I did a mistake in #466, log by branch should show merges.

Fix: log by branch should show merges

---

Default.sublime-commands

There are two reasons for such a rename.
1. `git: graph` is now consistent with `git: log` to show commits of the current branch.
2. typing `git: gr..` in command palette always select `git: graph all branches` first. However `git: graph current branch` is far more frequently used (at least for myself). Renaming it to `git: graph` makes it appear before `git: graph all branches`.

Enhancement: rename `git: graph current branch` to `git: graph`

---

GitSavvy.sublime-settings
syntax/graph.sublime-syntax

Fix the highlight of "Merge Branches" and show date and author info.
Before
After
The update is backward compatible to the original default
```
"git_graph_args": ["log", "--oneline", "--graph", "--decorate"]
```
Also, it changes the scope of the graph lines from comment to punctuation. As comments are italic for most color schemes and italic lines do not align.

Enhancement: graph syntax shows author/date and highlights merge branches

---

core/git_mixins/status.py
core/interfaces/status.py

- both files will now be displayed according to the rename/copy direction:
old file -> new file
More info: https://git-scm.com/docs/git-status
Close #339

Fix: allow renamed/copied status to correctly render

---

core/constants.py
core/interfaces/rebase.py

Use the constant `MERGE_CONFLICT_PORCELAIN_STATUSES` to detect conflicted entries in rebase dashboard

Others: use defined constant to detect conflicted entries in rebase dashboard

---

core/commands/diff.py
core/commands/git_add.py
core/exceptions.py
core/git_command.py
github/commands/pull_request.py
github/github.py

* Import GitSavvyError to always log the thrown error
- move GitSavvyError to exception module
- refactor modules to correct import location
* Add status updates when fetching pulling requests
- This shows users what's going on, and when fetching finished whether any pull requests were found or not.
- Moving FailedGithubRequest to exceptions and inherit from GitSavvyError will keep
the exception logic seperate, while also logging the errors more visibly

Better exceptions

---

common/quick_panel.py
core/commands/log.py
core/commands/reset.py

Added two helper functions `show_paginated_panel` and `show_log_panel` 
- `show_paginated_panel` opens quick panel with pagination
- `show_log_panel` shows log entries with pagination
They are then used in `GsLogCommand` and `GsResetCommand` to display commits.

Enhancement: use paginated panel to show log and reset

---

common/util/view.py

Some open files (maybe without project), would otherwise occasionally raise the following exception in console:
```python
File "/Users/pavel/Library/Application Support/Sublime Text 3/Packages/GitSavvy/common/util/view.py", line 72, in refresh_gitsavvy
view.window().run_command("refresh_folder_list")
AttributeError: 'NoneType' object has no attribute 'run_command'
```

Fix: Avoid exception when window is None

---

core/commands/log_graph.py
core/commands/navigate.py

Always move the cursor to center when using the navigating keys. The duplicated code in `GsLogGraphNavigateCommand` is also removed.

Enhancement: always show at center when navigating

---

core/git_command.py

This avoids blocking the user from using sublime by spamming her/him with endless messages about git executable not found. It displays the alert dialog once and continues to log further failures as exceptions.
This allows GitSavvy to start functioning once git is on path (or the settings are updated to point to it's explicit location).
Fixes #551

Fix: display the "git binary not found" error message only once

---

core/commands/diff.py

Refreshing the page should not execute `gs_diff_navigate`.

Fix: only trigger gs_diff_navigate on initialization

---

core/interfaces/branch.py

`get_selected_branch` returns a tuple `(remote, branch_name)`, we need to compare the second element.

Fix: do not merge current branch

---

Default.sublime-keymap
GitSavvy.sublime-settings
common/commands/view_manipulation.py
common/ui.py
core/commands/log_graph.py

Arrow key navigation is enabled on dashboards allowing users to use arrow keys to navigate between branches, files, commits etc.
However, it is not enabled in `diff_view`, `inline_diff_view` and `show_commit_view` . These views are showing commits, may be still useful to have arrow keys.

Feature: use arrow key to navigate on dashboards

---

core/commands/blame.py
core/commands/changelog.py
core/commands/commit_compare.py
core/commands/log.py
core/commands/log_graph.py
core/commands/reset.py
core/commands/tag.py
core/git_command.py
core/git_mixins/tags.py
core/interfaces/rebase.py
core/ui_mixins/quick_panel.py

This  PR adds two reusable mixins that replace much repetitive and sometimes inconsistent code. 
Hopefully this way the commands has less cruft and easier to read.
In  this refactor I only touched panels with "static options". The next step would be to replace the remaining panels that prompt for branch/remote. By default most of the updated commands run in a synchronous manner (in the current thread), since the panel options are available immediately.

Feature: refactor quick panel for (mostly) static options

---

Default.sublime-keymap
core/commands/push.py
core/interfaces/status.py
docs/remotes.md

- `GsPushCommand` only push current branch, fix #566 
- change the keybind from [P] to [p] in Status dashboard so that it is consistent with the branch dashboard.
- extend `GsPushToBranchNameCommand` default arguments to accept a prespecified branch name.
- push current branch to a remote branch with the same name if `prompt_for_tracking_branch` is false
- fix `GsPushToBranchCommand` when the name of the remote branch is not the same as the local

Fix: various fixes for the push commands

---

core/interfaces/__init__.py

Fix #562
The bug was because the previous dashboard is closed before the next dashboard is created.
Using `set_timeout_async` will correct the order of the events.

Fix: use set_timeout_async to cycle tab

---

core/commands/push.py
core/git_mixins/remotes.py

Enhancement: rename push command argument as "remote_branch" and minor refactoring of PushBase.
Previously, the [push][1] command will do 
1. `git push remote local_branch:branch` if `local_branch` is not empty
2. `git push remote branch` if `local_branch` is empty
I found that it is a kind of counterintuitive, now, the function is refactored such that
1. `git push remote branch:remote_branch` if `remote_branch` is not empty
2. `git push remote branch` if `remote_branch` is empty
Additionally, I have refactored some logic of [GsPushCommand][2] to make it more straightforward.
[1]: https://github.com/randy3k/GitSavvy/blob/7df4d5a449d295ab9723056fc71579c49693cc01/core/git_mixins/remotes.py#L57
[2]: https://github.com/randy3k/GitSavvy/blob/4fb608a15fd0ee94e0b41551e74ff25d654f02c2/core/command …

Enhancement: rename push command argument as "remote_branch"

---

core/interfaces/__init__.py

The following error occurs if `tab_order` is set as
```
"tab_order": ["status", "rebase", "graph"]
```
and <kbd>tab</kbd> is prssed on the Branch dashboard.
```
Traceback (most recent call last):
File "/Users/Randy/Documents/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 28, in <lambda>
sublime.set_timeout_async(lambda: self.run_async(source, target, reverse))
File "/Users/Randy/Documents/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 31, in run_async
to_load = target or self.get_next(source, reverse)
File "/Users/Randy/Documents/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 47, in get_next
source_idx = tab_order.index(source)
ValueError: 'branch' is not in list
```
It is becaused the `branch_view` is not in `tab_order`.

Fix: check if the current dashboard is on the list

---

Default.sublime-commands
core/commands/show_file_at_commit.py

Showing current file history, it is essentially a shortcut of `git: log current file` -> `For current branch` -> `show file at commit`.

Feature: show current file history

---

core/interfaces/branch.py

Pass the correct variable to git. The bug was introduced in #573 while refactoring GsBranches commands.

Fix: rename branch

---

core/interfaces/tags.py

When triggering the command `git: push all tags` in a non-interface view, `interface` would be `none`.

Fix: git push all tags from non-interface view

---

core/commands/cherry_pick.py

The bug was introduced in #580 as the variable `_selected_branch` was renamed as `_branch`.

Fix: cherry-pick branch variable has changed

---

core/commands/reflog.py
core/commands/reset.py
core/git_mixins/history.py
core/ui_mixins/quick_panel.py

- refactor GsResetBase to ResetMixin
- added RefLogMixin (mirror of LogMixin)
- added RefLogEntry (mirror of LogEntry)
after it is merged, we can provide command `git: reflog` similar to `git: log`.

Other: refactor GsResetBase, RefLogEntry and RefLogMixin to handle ref logs

---

core/git_mixins/stash.py

The `GsStatusCreateStashCommand` and `GsStatusCreateStashWithUntrackedCommand` commands are (according to the comments) meant to create stash from unstaged changes - for that, the `-k` flag is needed.
Stashing only the unstaged changes does indeed make more sense.

Stash unstaged files only

---

README.md

Once travis-ci, appveyor and coveralls.io are activated, these badges are ready to be displayed.
[![Build Status](https://travis-ci.org/divmain/GitSavvy.svg?branch=master)](https://travis-ci.org/divmain/GitSavvy)
[![AppVeyor branch](https://img.shields.io/appveyor/ci/divmain/GitSavvy/master.svg)](https://ci.appveyor.com/project/divmain/GitSavvy)
[![Coverage Status](https://coveralls.io/repos/github/divmain/GitSavvy/badge.svg)](https://coveralls.io/github/divmain/GitSavvy)

Enhancement: add badges

---

core/commands/init.py

Fix: Clone doesn't need to be executed from a git repo

---

Default.sublime-keymap
core/interfaces/status.py

Fix: Trigger stash command outside of stash section
fixes #600
Fix: Drop a stash is destructive
fix #609

Improve Stashs

---

.gitignore
github/github.py

This commit also logs an error in case parsing fails.
Fix #612

Fix: support parsing "git://" remote URI to Github URL

---

core/commands/inline_diff.py

`self.file_path` and `self.repo_path` are None when view is cached.
Fixes #624

Fix Issue 624

---

core/interfaces/rebase.py

It is not necessary to check if HEAD is rebased. Manuplicating commits should be always possible (if there are no merges).
close #619

do not check if HEAD is rebased

---

core/git_mixins/rewrite.py

Check that file exist before opening

---

common/global_events.py

This is used by `hub pull-request` and is identical to a commit message
https://hub.github.com/
Related #402

Enhance GitCommandFromTerminal w/ PULLREQ_EDITMSG

---

CONTRIBUTING.md

Often needed to debug the user's underlying systems, since
both Python and Git communicate to each OS differently.

Docs: Add OS type and version in bug information requested

---

core/commands/blame.py
core/commands/log.py
core/git_mixins/history.py

One step closer to blame walker. I think I will make it the next couple of days. 
closes #654 
Read commit messages for details
Recorded a small screencast http://recordit.co/oyfUHn7YQG

Generally improve the git blame feature

---

common/global_events.py
common/util/view.py
core/commands/status_bar.py

Do not refresh status bar using `GsInterfaceFocusEventListener`, it is handled by `GsStatusBarEventListener` already.

Improvement: refresh status bar and related fix

---

GitSavvy.sublime-settings
core/commands/init.py

As discussed in #589 and solves #664.
This could probably also have been implemented directly in [core/git_command.py](https://github.com/divmain/GitSavvy/blob/2b10772530437f7088f8fcebdba459f05efb2c7c/core/git_command.py#L101).
Feel free to squash or make any changes.

Adds a setting to disable git init prompts

---

common/util/view.py

Fix: If refresh_gitsavvy get called without a view, it is fine

---

common/util/debug.py

Some command in inline diff are workning with binaries so
when we try to log. Try to decode it as utf-8, otherwise
fail.
closes #662

Fix: Log all output even binaries

---

core/commands/log_graph.py

The commit message might include asterisks everywhere, we just have to replace the first one.
Fixes Issue #676

Fix: graph, only replace the '*' before the commit sha

---

CONTRIBUTING.md
docs/debug.md

As the commands were modified in commit 2cd23be, we need to update the documentation to show the correct command names.
I also took the opportunity to add the step-by-step instructions which we can refer to from CONTRIBUTING.md

Docs: Update to new command names and add use case

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
Default.sublime-keymap
common/ui.py
common/util/view.py
core/commands/blame.py
core/commands/cherry_pick.py
core/commands/fixup.py
core/commands/log.py
core/commands/reset.py
core/commands/show_file_at_commit.py
core/git_mixins/history.py
core/interfaces/branch.py
core/ui_mixins/quick_panel.py
docs/history.md
popups/blame_view.html

closed #102 #152 
First off, sorry for the big PR. Bit it is a big feature. 
I would like to have some review of the code of one other contributor.
Hello, @yyyc514, @benmosher, @stevage, @rchl, @reagle, @dlnsk, @jipumarino, @jipumarino, @jipumarino, @maxim, @zx8
Finally, I got around to implement this. If you are running GitSavvy from git pull down the branch a see if there is something we can improve further?

Blame walk

---

.maintainerd
.travis.yml
scripts/deploy.sh

Alright @stoivo @asfaltboy @randy3k, this thing is ready for a test run.  What this will do:
1. Auto-edit the description of new pull requests with the following checkboxes:
a. I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
b. All related documentation has been updated to reflect the changes made.
c. My commit messages are cleaned up and ready to merge.
2. Require that all of these checkboxes are checked off before CI goes green.
3. Requires the submitter (or one of the maintainers) to select a semantic version that corresponds with the change represented by the pull request.
4. Enforce formatting guidelines for commit subjects:
a. They must be between 8 and 72 characters long.
b. They must start with one of `Fix`, …

Enable maintainerd

---

Default.sublime-commands
core/commands/commit_compare.py

The commit b7359f0 in PR #694 is not good enough. In this PR, I have extended `gs_compare_against` to accept both `base_commit` and `target_commit`. Only one of them should be specified. The panel prompt will ask for another commit and automatically fill in the missing one.
-----
_(required)_

Enhancement: compare against now accept both base/target commits

---

github/commands/open_on_remote.py

It allows me to do `git: show file at commit` then `github: open file on remote`.

Enhancement: allow open file on remote when opening file at commit

---

core/git_command.py

Fix #718 and the hope to also address #716 
The fix in #712 doesn't handle multiple folders. Git root is now detected in the following logic
1. if the current file is in a repo, use that repo
2. if sidebar exists and the first folder is in a repo, use that repo
3. if sidebar exists, show the initialization popup
4. else, show "Unable to determine Git repo path."
-----
_(required)_

Fix: find_git_root handles multiple folders

---

Default.sublime-keymap
core/commands/inline_diff.py
popups/inline_diff_view.html

The concept of reseting lines an hunks in cached mode is confusing. What it does now is exactly equal to unstaging lines or hunks. So, "l" and "L" (also "h" and "H") are doing the same task in the cached mode. This PR disables the "reset" keys "H" and "L" in the cached mode.
We actually also disabled "reset hunk" for the diff view, so it does also make sense to disable it for the inline diff view.
-----
_(required)_

Enhancement: disable "reset line" and "reset hunk" in inline diff cached mode

---

core/commands/status_bar.py
core/git_command.py

continue the discussion in #719 for not setting "git_savvy.repo_path" if the current file is not in the found repo.
close #726
-----
_(required)_

Fix: avoid setting repo_path when a file is not in the repo

---

common/util/view.py
core/commands/blame.py
core/commands/log.py
core/commands/reflog.py
core/commands/reset.py
core/ui_mixins/quick_panel.py

Now it supports on_highlight(entry) and is used in GsBlameCommand.
It also fixes a bug when canceling the panel of `Pick a new commit to blame`
-----
_(required)_

Refactor show_log_panel

---

GitSavvy.sublime-settings
core/interfaces/tags.py

I found that the tags dashboard is nearly useless if there are too many tags.
-----
_(required)_

Enhancement: limit of items in tags dashboard

---

core/commands/inline_diff.py
core/commands/show_file_at_commit.py
core/git_mixins/history.py

This one should be easier to review. It matches current line of the current file when using `show current file at commit`.
-----
_(required)_

Feature: find matching line when showing current file

---

GitSavvy.sublime-settings
core/commands/diff.py
syntax/diff.sublime-syntax
syntax/show_commit.sublime-syntax
syntax/show_commit_diffstat.sublime-syntax

diff stat is currently shown in `show_commit_view`, this PR makes it also available to `diff_view`. Also, contains a small tweak to the syntax files.
-----
_(required)_

Enhancement: show diff stat in diff_view

---

core/commands/pull.py
core/git_mixins/remotes.py

It may be confusing to pull to a branch other than the active branch
https://github.com/divmain/GitSavvy/issues/729#issuecomment-322219945
close #729
-----
_(required)_

Fix: always pull to the active branch

---

GitSavvy.sublime-settings
core/ui_mixins/quick_panel.py
github/commands/add_fork_as_remote.py
github/commands/commit.py
github/commands/pull_request.py
github/github.py

Github API has a limit of 30 items per request (can be changed to 100), this PR uses `show_paginated_panel` to show all the items in various commands.
1. `github: add fork as remote`, fix #528
2. `github: review pull request`
3. contributors and issues completion
-----
_(required)_

GitHub integration API limit

---

core/commands/checkout.py
core/commands/commit_compare.py
core/commands/fetch.py
core/commands/log.py
core/commands/log_graph.py
core/commands/merge.py
core/commands/pull.py
core/commands/push.py
core/commands/remote.py
core/commands/reset.py
core/interfaces/branch.py
core/ui_mixins/quick_panel.py
github/commands/configure.py
github/commands/open_on_remote.py

close #546 
It is a major refactor of the branch and remote panels. The two related functions are [show_remote_panel](https://github.com/divmain/GitSavvy/blob/194ef3cbac540501e94b7c904aab35ff4c63b5f3/core/ui_mixins/quick_panel.py#L116-L116) and [show_branch_panel](https://github.com/divmain/GitSavvy/blob/194ef3cbac540501e94b7c904aab35ff4c63b5f3/core/ui_mixins/quick_panel.py#L175-L175).
The git flow related code is kept untouched as they are written in a different style with the other code. 
I tried very hard to make sure it doesn't break any functionality, though not 100% sure. 
-----
_(required)_ …

Other: show_branch_panel and show_remote_panel

---

core/interfaces/branch.py

The usage of `groupby` is broken if the branches are sorted by recency.
-----
_(required)_

Fix: sort_by_recent_in_branch_dashboard breaks the branch order

---

github/commands/pull_request.py

Close #738 
when creating PR without tracking remote, prompt to push to remote instead of asking to configure remote tracking branch.
PS: this PR is created by this feature.
-----
_(required)_

Enhancement: offer push to remote rather than configuring remote

---

.maintainerd
Default.sublime-keymap
common/ui.py
common/util/view.py
core/commands/checkout.py
core/commands/navigate.py
core/interfaces/branch.py
messages.json
messages/2.15.0.txt

~~This PR depends on #713~~ It is merged
- The `checkout new branch` and `checkout remote branch` functions are combined.
- The cursor is set a the newly checkout branch.
close #371 close #608 
-----
_(required)_

Enhancement: Redesign checkout functionality of Branch dashboard

---

core/git_mixins/branches.py
core/git_mixins/remotes.py
github/commands/open_on_remote.py

close #723 
Open file at merge base if the remote branch doesn't contain the opening commit.
To test this PR, checkout a branch which has a tracking remote. Add a new commit and open the file at remote. It should prompt a message asking to open the file 1 commit earlier.
-----
_(required)_

Enhancement: more robust to open file on remote

---

core/git_command.py

Another enhancement of issue #726.
Throw RuntimeError If the current view is detached, it will result in a `GitSavvyError` without showing panel.
cc: @asfaltboy, hope this would be the final fix.
-----
_(required)_

Enhancement: do not open panel when window doesn't exist

---

core/commands/log_graph.py

First `cherry_pick`, `revert_commit ` and `show_file_at_commit` have already been defined in the parent class `GsLogActionCommand`. Also, insert `revert_commit` to a different index to make it more consistent with `git: log current file`.
-----
_(required)_

Other: refactor GsLogGraphActionCommand

---

common/util/debug.py
core/git_mixins/merge.py

Might be useful for logging `subprocess.Popen` commands, other than git, in the debug log. Currently logs launch of `mergetool` which is the only other `Popen` call we have.
Related to #681
-----
_(required)_

Other: refactor log_git and add log_process

---

messages.json
messages/2.16.2.txt

There was a typo in `messages.json` so the release was never announced. Instead of 2.15.0, we have bumped the version to 2.16.0.
Actually, I believe a lot of users have upgrade to 2.16.1 (the most recent release), shall we tag 2.16.2?
-----
_(required)_

Other: release 2.16.2

---

core/git_command.py

Address the issue in #761.
As @stoivo  and I discussed before, we should merge it in a week to allow users to read the release note of 2.16.2.
-----
_(required)_

Enhancement: don't show "following output" when stderr is empty

---

.maintainerd

Temp. workaround due to  wrongly reported commit structure issue as in divmain/maintainerd#1
I dug in the code and it seems it's the right thing to toggle, as in:
https://github.com/divmain/maintainerd/blob/master/event-handlers/pull-request/handle-action/synchronize.js#L36-L57
-----
_(required)_

Internal: maintainerd - don't enforce empty line

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

I accidentally removed my origin repo.
-----
_(required)_

Internal: add ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md

---

core/git_mixins/rebase.py
core/interfaces/rebase.py
docs/rebase.md

Before, we used a base ref that was specified in settings, otherwise defaulting to hardcoded "master".
Now, we find the nearest common ancestor branch and use that as our default base, still allowing override in settings.
Fixes #499
-----
_(required)_

Feature: better selection of base ref branch

---

core/commands/fetch.py
core/ui_mixins/quick_panel.py
docs/remotes.md

This PR addresses a couple annoyances I've noticed with `GsFetchCommand`:
- The quick panel prompts you to select a remote even when the repository only has a single remote, which feels redundant.
- The quick panel can remember the last choice you selected if it's an individual remote, but can't remember if your last choice was `All remotes`.
- If there is only one remote, fetch from that immediately without requiring a second user interaction. To support this without impacting other remote commands (e.g. `GsRemoteRemoveCommand`) I added an `allow_direct` keyword argument to `show_remote_panel`.
- If there are multiple remotes, make the preselected choice "All remotes." if `GitCommand.last_remote_used` hasn't been set.
- Allow the quick panel to remember `All remotes.` as the previous …

Enhancement: Improvements to fetch quick panel

---

.github/PULL_REQUEST_TEMPLATE.md
.maintainerd
CONTRIBUTING.md

maintainerd semver feature is confusing for a PR targetting a branch other than master
-----
_(required)_

turn off semver of maintainerd

---

GitSavvy.sublime-settings

so that PackageDev will be able to pick up the setting
-1 is in effect of selecting all tags.

set the default for max_items_in_tags_dashboard to -1

---

core/exceptions.py

It is to handle the issue `GitSavvyError does not take keyword arguments` in [this](https://github.com/divmain/GitSavvy/issues/772#issuecomment-342436635) comment.
Note: it does NOT fix issue 772

do not pass kwargs to Exception

---

core/commands/blame.py

For `blame` to detect moved or copied lines in all commits, the command line argument is `-CCC`, this was changed to `-CC` in the blame refactor.
- `-C` detects in the modifying commit
- `-CC` detects in the modifying commit AND the commit that created the file
- `-CCC` detects moved or copied lines in all commits
See: https://git-scm.com/docs/git-blame#git-blame--Cltnumgt

Fix: Use correct argument for blame all commits

---

core/commands/ignore.py
core/git_mixins/ignore.py

close #781
- set default ignore file as current file
- catch the error when running `config --global core.autocrlf` when the setting was not set.

Fix: ignoring file was not working

---

core/interfaces/rebase.py

`selection` would be `None` if the quick panel was canceled.

Fix: handle cancellation of the panel

---

core/commands/changelog.py

When the pattern is not found, `find()` returns -1 instead.

Fix: find() returns index instead of True/False

---

Default.sublime-commands
core/commands/remote.py
core/ui_mixins/quick_panel.py

- new command `git: remote rename`
- Enhancement: show url when using `git: remote`

git remote rename and show remote url

---

core/interfaces/rebase.py

It should be safe to manipulate commits when there are untracked files. Related to #825, #644 
close #789

Enhancement: manipulate commits with untracked files

---

core/commands/remote.py
github/commands/add_fork_as_remote.py

`https://github.com/randy3k/GitSavvy.git` -> `git@github.com:randy3k/GitSavvy.git`

Enhancement: use ssh url instead of clone url when adding fork

---

core/commands/commit.py

My last PR #827 was not correctly done.

Fix: only show diff patch when `show_commit_diff` is "full"

---

common/ui.py
core/commands/amend.py
core/commands/blame.py
core/commands/checkout.py
core/commands/cherry_pick.py
core/commands/custom.py
core/commands/diff.py
core/commands/fetch.py
core/commands/flow.py
core/commands/ignore.py
core/commands/init.py
core/commands/log_graph.py
core/commands/pull.py
core/commands/push.py
core/commands/quick_commit.py
core/commands/quick_stage.py
core/commands/remote.py
core/commands/show_commit.py
core/commands/tag.py
core/exceptions.py
core/git_command.py
core/interfaces/branch.py
core/interfaces/status.py
core/interfaces/tags.py
core/ui_mixins/quick_panel.py
github/commands/commit.py
github/commands/configure.py
github/commands/create_fork.py
github/commands/pull_request.py

`sublime.status_message` is no longer officially there in the api doc so it is better to use in on a window. 
And  if we don't know which window we can use `sublime.active_window().status_message`

Internal: Use window.status_message instead of sublime.status_message

---

core/commands/pull.py

Fix: use sublime.active_window() in GsPullBase

---

GitSavvy.sublime-settings
core/commands/commit.py
syntax/make_commit.sublime-settings

- The ruler appears when you are on those lines
- If the lines are too long they will be marked with the scope `invalid.deprecated.line-too-long.git-commit` where `invalid` is the same scope as SublimeLinter uses to is should be coverd by all Themes
fix #41 
fix #423

Pedantic commit

---

core/commands/log.py

I don't know who to write it nicer. 
in ruby I would do 
```
"123".index("24") || 0
Integer("ff") rescue 0
```

Fix: log by author, also when you are not found

---

core/git_mixins/history.py

The only benefit is to reduce the number of calls to git.

Internal: Reduce calls to git

---

Default.sublime-commands
Default.sublime-keymap
core/git_mixins/active_branch.py
core/git_mixins/status.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
github/commands/pull_request.py
gitlab/commands/merge_request.py

Rebase dashboard has commands `use version from your commit` and `use version from new base` to manage rebase conflicts. The main contribution of this PR is to bring those commands to the Status dashboard when there are merge conflicts.
This pr also improves active branch status when merging.

Tools to handle merge conflicts

---

core/git_mixins/rebase.py

an attempt to fix #860 
It seems it was caused by an incorrect regex. The original regex returns something like `foo~9^2` but not just the branch name `foo`.

Fix: branch relative regex

---

README.md
core/git_command.py
core/git_mixins/branches.py

The original branch status failed to parse the tracking remote correctly if the commit message starts with something like `[Fix] bla bla bla`.
```
(randymbpro)-git_mixins$ git branch -a -vv                                                                                         (pull_request)
* branch_status                                         f6a0ee0 [origin/branch_status] Fix: tracking remote detection
dev                                                   f7de5a8 [origin/dev] [Internal] more typos
exception                                             1c83450 [origin/exception] [Internal] more typos
master                                                3c5b1ab [origin/master] Merge pull request #837 from divmain/release/2.16.7
pull_request …
```

Fix: tracking remote detection

---

core/git_mixins/branches.py

`for-each-ref` may list `HEAD` as one of the branches.
Before
After

Fix: filter branch HEAD

---

github/commands/pull_request.py
github/github.py
gitlab/commands/merge_request.py
gitlab/gitlab.py

revert some of the changes in #883 
It turns out `urllib.urlencode` is a wrong function to use and we should not encode the entire url.

Fix: use urllib.parse.quote_plus

---

GitSavvy.sublime-settings
common/commands/log.py
common/util/log.py
core/git_command.py

This is an exploration for new feature to show stdout/stderr output in a Sublime Text panel while a hook is running, as discussed in #812
Currently pre-push (logs to stdout) and pre-commit (logs to stderr) hooks have been tested on OS-X.
Some demos (bad gif conversion results in 2x slower playback, sorry for your time :) )
**Commit** (Commit view closes automatically)
**Push**

Log githook progress

---

common/util/view.py
core/commands/checkout.py

Proof of concept implementation of #835.
Add a `refresh_all_visible_views` method.
It iterates through all the current window groups and refresh the active view of the group.

Refresh all GitSavvy view on branch checkout

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
Default.sublime-commands
core/commands/__init__.py
core/commands/stage_diff.py
docs/staging.md

Per https://github.com/divmain/GitSavvy/pull/889#issuecomment-372092537, 
rename `git: add (edit)` command to `git: edit and stage diff`.
Also, close #888 by showing the hint at the top of the diff instead of showing a popup.

Enhancement: rename `git: add (edit)` command

---

core/commands/checkout.py
core/git_mixins/branches.py

Instead of using a regular expression to validate branch name, use the git command `check-ref-format` to validate it. It should give a better result than using a regular expression.

Fix: use check-ref-format to check branch name validity

---

GitSavvy.sublime-settings
core/git_command.py

Fix: use the decoded output

---

Default.sublime-commands
Main.sublime-menu
common/global_events.py

Many Thanks to OdatNurd[1]
https://forum.sublimetext.com/t/open-key-sublime-keymap-with-edit-settings-with-specific-platform-in-mind/35604/3?u=stoivo
fix #884
[1] https://forum.sublimetext.com/u/OdatNurd
Two tabs on the left side
Should this be merged into `dev` or should to merge this one in to `release/2.17.0`?

Add Key Binding setting shortcut

---

core/git_command.py

Pass startupinfo to `subprocess.check_output`

---

README.md

Update the codacy badge in README. Currently, it is a dead image.

Doc: update codacy badge address

---

core/interfaces/rebase.py

`target_commit` could be `None` if the panel is canceled.

Fix: check target_commit is empty when the panel is canceled

---

GitSavvy.sublime-settings
core/interfaces/rebase.py
docs/rebase.md

This PR makes `rebase_default_base_ref` more consistent with project-wise settings.  Originally, `rebase_default_base_ref` was put under the key `settings` which is not consistent with the project-wise settings.

Enhancement: make `rebase_default_base_ref` more consistent

---

GitSavvy.sublime-settings
core/commands/blame.py
core/commands/log.py
core/ui_mixins/quick_panel.py

1. added an option `blame_detect_move_or_copy_within` in settings
2. match line with picking another commit to blame, instead of showing the new blame in the current view, I find that it is more useful to open a new view of the select committee.
3. refactored `LogPanel` to make some of the options more configurable.

Some refactoring of the blame view and LogPanel

---

github/commands/create_fork.py

Make it easier to add fork as remote by using the URLs returned by the api call.

Enhancement: get remote url from api call

---

common/global_events.py

Respect use_syntax_for_commit_editmsg
fix #921

Enhancement: Opening commit from commadline respect setting

---

docs/custom.md

This PR warns users of custom commands to pay attention to the run_in_thread flag (giving it the wrong value may cause GitSavvy to hang).

Emphasize in docs when to use run_in_thread

---

common/ui.py

If you startup Sublime, obviously all in-memory state is empty. But you can
still have an actual interface open from the last session.
We simply guard the singleton/factory against `KeyError` and instantiate
a new interface object bound to an already present interface view. This,
of course, is very subtle and implicit programming style. But at least we don't 
change the caller side.

Fix: On startup in-memory `instances` cache can be empty

---

core/git_command.py

subprocess.check_output crashes with message:
OSError: [WinError 6] The handle is invalid
The issue seems to be with stderr
I'm not very familiar with python or subprocess, I only tested a couple of things and this seems to work.

Fix subprocess command crashing with OSError

---

core/commands/log.py
core/ui_mixins/quick_panel.py

It is a lot more convenient to just set on_highlight.
When you need a different on_highligh you just overwrite the current one. Either
by a new call or as a kwargs to show_log_panel
For #956 to go easier

Internal: Refactor away show_commit_info from LogPanel

---

common/global_events.py

Apology, I didn't test #959 thoroughly.

Fix: do not continue when the window is not a project

---

core/commands/init.py

I personally find this more useful than typing the path every time

Allow using ~/%HOME% when providing clone path, by expanding user home dir

---

Default (OSX).sublime-keymap
Default.sublime-keymap
core/commands/changelog.py
core/commands/checkout.py
core/commands/commit_compare.py
core/commands/custom.py
core/commands/ignore.py
core/commands/init.py
core/commands/mv.py
core/commands/push.py
core/commands/quick_commit.py
core/commands/remote.py
core/commands/stash.py
core/commands/tag.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/ui_mixins/input_panel.py
core/ui_mixins/quick_panel.py
github/commands/pull_request.py
gitlab/commands/merge_request.py

I always accidentally hit `super+enter` instead of `enter` in the input panel. This PR makes such keys an `noop`.
Ideally, the input should be accepted if `super+enter` etc is hit, however, the existing sublime api doesn't allow us to do such an operation.

Input panel

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
GitSavvy.sublime-settings
common/util/view.py
core/commands/commit.py

Additionally, no prompt will be made if the message is empty and the default
value of prompt_on_abort_commit is set as true

Enhancement: better message when prompt_on_abort_commit

---

core/commands/log.py
core/commands/show_commit_info.py

When runing git log current file is executed the highlight of the commit with only show the diff for the current file.

Git log current file will highlight commit diff for current file

---

.github/ISSUE_TEMPLATE.md

To help users reach the guide faster when opening a bug report
Hotfixes should be submitted to `master` branch. As part of the PR process,
you will be asked to provide the information necessary to make that happen.
Pull requests on new features should be submitted to `dev` branch and will be
regularly merged into `master` after evaluations over an extended period of
time.

Make the debug log link absolute

---

github/github.py
gitlab/gitlab.py

Fix: incorrect log_error call

---

Default.sublime-commands
GitSavvy.sublime-settings
core/interfaces/__init__.py

For consistency and the changes are hidden from users.
Rationale:
1. the command line is `git tag` instead of `git tags`
2. The Branches dashboard is also triggered by `git: branch` not `git: branches`
There are also things like `tags_view`, `gs_show_tags` which may also need to be renamed. But they don't bother me.

Enhancement: rename tags to tag

---

core/commands/commit.py

Make `COMMIT_EDITMSG` formatting a little bit better by adding a newline before it and remove the trailing newlines.

Enhancement: better formating the initial text

---

core/commands/push.py

`get_upstream_for_active_branch` may fail if there is no remote tracking
close #993

Fix: always use get_local_branch to get remote tracking

---

syntax/diff.sublime-syntax
syntax/test/syntax_test_diff.txt

This commit addresses the following flaws of the diff.sublime-syntax
1. missing rules for git output:
- deleted file mode
- rename from
- rename to
- similarity index
2. the whole git output is scoped as as `punctuation`
3. the linefeed \n is not included in the git output rules which
causes bad results if a color scheme wants to highlight the
background of the git output.
This commit therefore
1. adds rules for the missing output messages
2. introduces normal keyword, constant, string scopes for the output
and encapsulates everything in a meta scope based on the existing
`meta.diff.header` for easier color-scheme creation.
3. optionally includes the \n? in any rule.
Hotfixes should be submitted to `master` branch. As part of the PR process,
you will be asked to provide the information …

Enhancement: Add more complex git output scopes to diff syntax

---

GitSavvy.sublime-settings
core/commands/commit.py

The cleanup flag controls how a commit message is cleaned up.
https://git-scm.com/docs/git-commit/2.0.0#git-commit---cleanupltmodegt
In command line, the default mode strips out comments started with `#` if an editor is opened interactively. However, GitSavvy only passes the message to the stdin, and the default mode only strips `whitespace`. This PR is trying to reflect the very same behavior on cli.

Enhancement: cleanup commit message

---

core/settings.py

Fix: check the nullness of project_savvy_settings

---

GitSavvy.sublime-settings
core/git_command.py
docs/commit.md
scripts/stgpg.sh

As in #596, this change documents a proper GPG setup on tty-enabled OS (Linux/MacOS), and correct credentials docs. This commit also adds the `global_pre_flags` setting to allow specifying options `BEFORE` the command, such as [the "-c" git per-command config option](https://git-scm.com/docs/git#git--cltnamegtltvaluegt).
The GPG prompt will only work in Sublime if user sets up `git config` with the options:
```
gpg.program=./scripts/stgpg.sh
commit.gpgsign=true
```
or instead of last one, passes the `-S` flag to commit command. So, I added the options in the GitSavvy settings comments.
TODO / Discuss:

GPG no-tty helper script and options

---

core/commands/blame.py

This avoid additional "line break" symbols in source code from being considered as line breaks in our parser. Git seems to only ever `'\n'` as a newline character, but python's `splitlines()` method considers many others by default.
Refs:
https://github.com/python/cpython/blob/3.4/Objects/unicodetype_db.h#L4317-L4338
https://github.com/git/git/blob/master/blame.c#L1633-L1637
Fixes #1011  (more info there)

Bugfix: avoid splitlines in blame

---

common/theme_generator.py

Fixes some issues (#1029) with the sublime-color-scheme format. For details refer to the commit messages, please.
I started fixing at the dev branch. If you feel this to be a hotfix, feel free to move it to master.

Fix errors with sublime-color-scheme format in inline diff

---

.travis.yml

The (currently failing) `brew update` dance is not necessary anymore. We just skip it, they ship py36 which is enough.

Fix travis osx builds

---

core/commands/commit.py

Fixes #1055
Regardless of what #1016 does or eventually will do, this needs a hotfix bc right now, the user can't close the commit view using `ctrl+w` if `prompt_on_abort_commit` is false.

Fix: Allow closing the commit view if `prompt_on_abort_commit=false`

---

common/commands/view_manipulation.py
core/git_mixins/active_branch.py
core/git_mixins/status.py
core/interfaces/status.py
syntax/dashboard.sublime-syntax
syntax/test/syntax_test_dashboard.txt

Fixes #1032 
DONE: 
- short-circuit staging/unstaging files (still not optimistic)
- render view as data arrives, whereby `git stash list` has the lowest priority
- optimize `git status` calls
- only draw when view changed
TODO:
- ~~Optimize `git status` calls~~
- ~~User looses selections / not multiple cursors but selected ranges collapse after each render~~ (This is actually implemented in `GsNewContentAndRegionsCommand` so I don't touch that) 
- ~~Only re-render if state actually changes / this should be trivial now since the actual render is a pure function on `state`~~

Optimize status interface

---

core/git_command.py

If we're not given decode, it means we're going to be dealing with binary sequence here, and substitution will fail. An error occurs when I use the [M]erge command without this fix.
P.s It's important to merge this before release so we don't introduce the regression

Fix: don't ansi-decode a binary string

---

core/interfaces/tags.py

Fixes #1046 
Because showing `** Press [e] to toggle display of remote branches. **` is lame when no remotes have been configured, we just suppress this help message in such cases.

Show toggle remotes help message only if there are any remotes

---

setup.cfg

Currently, GitSavvy uses pycodestyle but it is easy to include
appropriate settings for flake8 and will make contributors happy.

Include flake8 config for convenience

---

core/git_mixins/active_branch.py
tests/test_repo_status.py

Add tests for parsing the repo branch status. 
Expose bugs reported in #1043.
Fixes #1043

Repo status tests

---

common/commands/view_manipulation.py
core/commands/log_graph.py
core/commands/show_commit_info.py
tests/fixtures/log_graph_1.txt
tests/test_graph_view.py

Fixes #1052 
Fixes #1053 
Fixes #1054 
PLUS:
- Commit info panel can be hidden via `<ESC>` or mouse
- Commit info panel can be shown via mouse
- Don't fight with other panels the user might open. E.g. find or console
- Cache `git show <commit>` calls
Let's see how this one goes. `commit_compare` is actually the same as graph, that was super confusing first. 🍭 
🚶 🍷  🛌 
~Needs https://github.com/divmain/GitSavvy/pull/1033/commits/50c68a323006ed00f76afda62c662913fc29e403 which is included in #1033 for vintagous~ #1033 has been merged

Improve graph view

---

Default.sublime-keymap
core/commands/diff.py
popups/diff_view.html
syntax/diff_view.sublime-syntax
tests/test_diff_view.py

This is pretty much to get early feedback. I saw #856 and implemented it. The keybinding I used is `<tab>` to quickly switch between *cached* and *non-cached* (in git parlance) mode. 
`<tab>` is convenient, however, if we ever want to use 'diff all files' as a dashboard view it would clash with our 'cycle views' command.
I also added a basic header/prelude to the diff view. This is similar to the prelude we have e.g. in the status dashboard. And I think it's really easier to grasp what the view is currently showing. (Esp. with the implemented fast toggle.) It currently shows the file you're diffing if any, the two commits you're comparing if any. For the typical `git diff` it tells you either 'UNSTAGED CHANGES' or 'STAGED CHANGES (Will commit)'. This is the exact wording git GUI uses, and …

Iterate on diff view

---

common/util/view.py

Now, `log_graph_view` is basically a irregular 'interface' so it should be here. Note that `refresh_gitsavvy_interfaces` is only called after checkouts, otherwise the similar `refresh_gitsavvy` is used. 
That doesn't seem correct, and a picky differentiation. We *should* always call `refresh_gitsavvy_interfaces`, but rename it to `refresh_gitsavvy`.

Refresh graph view after checkout

---

syntax/graph.sublime-syntax
syntax/test/syntax_test_graph.txt

Improves #1051
- Mark the whole line so that we can style the dot
- Fixup regex for detached heads
- Really mark the literal 'HEAD'

Mark the whole line containing 'HEAD' as headline

---

GitSavvy.sublime-settings
core/commands/commit.py

As discussed with @kaste (see #1070 ), we will revert the PRs related to 
"cleanup commit message" and check "nothing to commit".
This PR will then be cherry-picked to the next release branch.

Revert commit check

---

core/commands/log.py

The three calls herein used `self.view` which is not defined since
`GsLogActionCommand` is a `WindowCommand`. So basically all commands raised
and did nothing.
I think doing nothing is the correct approach here since after closing the
panel, `on_activated` callbacks run for all important views anyway.
To actually refresh _other_ visible views beside the active one would be a
useful feature though.

Do not imperatively refresh ui after Log actions

---

core/interfaces/status.py

The bug basically is that you could not hit `ddd` in a meaningful fast way to discard three files in a row.

Faster responses after discarding or ignoring files from status dashboard

---

core/commands/status_bar.py

Fixes #1099
To what I know, your fix in #1100 is too complicated. Officially, transient views are exactly these views when you have an otherwise empty window. 
So I think we check the window anyway, then the group for the widgets and otherwise just return. 
Basically saying, it was a *feature* of my code that it was not calling `git status` for these temporary views. If we don't want that, I think we can just do this here.

Actually update the status bar for transient views

---

GitSavvy.sublime-settings
core/git_command.py
core/git_mixins/status.py

Git 2.17+ supports the custom environment variable "GIT_OPTIONAL_LOCKS"
which can be set by editors to ask git to reduce the number of file
locks when querying for status information such as "git status". This
helps to speed up some commands and helps improving concurrent status
queries.
This commit therefore introduces the "env" setting in the 
GitSavvy.sublime-setting, which is injected into the "environ" object
before calling a git command.
The "env" setting contains the "GIT_OPTIONAL LOCKS: 0" by default.
A user can override this setting or add other custom environment
variables.
Note:
Newer versions of git also support a command line argument to disable
optional locks. But using it would cause backward compatibility issues
if a user still works with a git version, which does not …

Add support for "env" settings and GIT_OPTIONAL_LOCKS

---

core/git_mixins/active_branch.py
tests/test_repo_status.py

If you create a new repo on GitHub and clone it immediately `master` tracks
`origin/master` without creating it. So the remote is 'gone'.

Edge case for initial commit created e.g. by GitHub

---

core/commands/diff.py
tests/fixtures/diff_1.txt
tests/test_diff_view.py

As title. In the hunk header both `@@ -16,7 +16,7 @@` and `@@ -16 +16 @@` (without the line count) are allowed so we should support both. 
Extracted from #1075

Fix clickable hunk header when it doesn't contain a line count

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
syntax/diff_view.sublime-settings

Bc of the new prelude in the diff view, we at some point had to introduce a new syntax for it. But we forgot to add the typical syntax settings, and the edit settings shortcut.
This PR adds them.

Fix diff view syntax settings

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
Default.sublime-keymap
core/commands/diff.py
popups/diff_view.html
setup.cfg
tests/test_diff_view.py
unittesting.json

Fixes #1036
Fixes #1074 
Bugs/Observations:

Implement Undo for diff-view

---

core/commands/diff.py

`super.run()` already calls 'show_at_center' by default.

Cleanup navigate command

---

Default.sublime-commands
GitSavvy.sublime-settings
core/interfaces/__init__.py

as discussed in #998, we are going to revert the previous commit which changes `tags` to `tag` but only keeping the user command.

Tags refactor

---

core/commands/diff.py

We must ensure that hitting 'h' very fast does run completely ordered, and
always waits for 'gs_diff_refresh' to complete. ('gs_diff_refresh' updates our
model.)
Please NOTE that running a command from the worker will still run that command
on the main thread. T.i. `set_timeout_async(lambda: view.run_command("refresh"))`
is misleading and a footgun because the "refresh" command here will still start
on the main thread. We basically just await the worker and then put a
task/command on the main worker queue.
Fixes #1104

Make hunking block for consistent subsequent actions

---

core/commands/log_graph.py
tests/test_graph_view.py

For merges is totally possible that we get '\\' chars at the right of the '*'.
Added tests.

Fix commit hash extraction for log graph

---

core/commands/log.py
core/interfaces/status.py

`current_file` basically takes precedence and fills `file_path` with
the current filename of the active view (using `self.file_path`). This
is not what we want here.
Fixes #1096

Do not provide both `file_path` and `current_file`

---

core/interfaces/__init__.py

If window is closed / reopened the command may trigger the exception:
Traceback (most recent call last):
File "/Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 28, in <lambda>
sublime.set_timeout_async(lambda: self.run_async(source, target, reverse))
File "/Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/interfaces/__init__.py", line 36, in run_async
self.view.window().run_command("hide_panel", {"cancel": True})
AttributeError: 'NoneType' object has no attribute 'run_command'

Fix: defensive tab cycle

---

core/commands/log_graph.py
tests/test_graph_view.py

Automatically hides or shows the commit info panel if the user activates a
different view/buffer. (Except if the panel itself gains focus.)

Auto-close commit info panel if user moves away

---

core/commands/diff.py
tests/test_diff_view.py

GsDiffCommand either creates a new diff view, or it finds a suitable one
already open and then just focuses it. In both cases we want to make sure
that the view *eventually* shows the most recent diff.
The previous implementation had the following problems:
- `git diff` did run on the main thread (#1092)
- Reusing a diff view called `git diff` twice
We now generally rely on the `on_activated_async` event to update the view
lazy. The init command either creates or focuses a view but it never calls
for a 'refresh' imperatively.
Note that most of the time we actually want a blocking, sync update (to keep
the view and the repo state in sync) so we add a switch to the refresh command.
Fixes #1092

Optimize diff view startup

---

Default.sublime-keymap
core/commands/diff.py
popups/diff_view.html
tests/test_diff_view.py

Fixes #1065
Add `[+]`/`[-]` shortcuts to increase or decrease the contextual lines
`git diff` will output.
Uses the already implemented fuzzy hunk search to place the cursor correctly
after refreshing the view.
Note: We set `"--unidiff-zero"` when hunking if we do not show any contextual
lines which is otherwise discouraged bc it is mildly unsafe.
Added type annotations and some comments to old functions.

Implement dynamic context lines (zooming)

---

.travis.yml

As per discussion here: https://github.com/travis-ci/travis-ci/issues/9133#issuecomment-506211772 , seems travis-ci switched Ubuntu build images to Xenial (16.06) by default, which does not ship with Python 3.3. So we had failures such as [this one][1].
Related docs:
- https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
- https://blog.travis-ci.com/2018-11-08-xenial-release
- https://docs.travis-ci.com/user/reference/xenial/
[1]: https://travis-ci.org/divmain/GitSavvy/builds/547753063

Misc: fix travis linux build

---

core/commands/merge.py

The command `git: merge` should imo not show the branch currently checked out.

Do not offer merge against self

---

core/commands/inline_diff.py

If set to true it will jump to the correct position you were editing in the
inline diff.
E.g. a keybinding
```
{
"keys": ["ctrl+shift+["],
"command": "gs_inline_diff",
"args": { "match_current_position": true }
},
```
Workflow: edit buffer/file, save, issue command, inline diff will show up and jump to the correct position you were on while editing, ctrl+tab or ctrl+w to continue editing on the file, and so on.

Add `match_current_position` flag to `GsInlineDiffCommand`

---

common/ui.py

If the user opens e.g. the status dashboard using keybindings she can be
actually in a panel (like Terminus et.al.) at that time. In that case a simple
`window.focus_view` is not enough to bring the cursor to the view, we must
focus the group first.

Force focus interface view

---

core/commands/diff.py
tests/test_diff_view.py

Fixes #1105 
Multiple hunks can be combined into a patch which then can applied at once.

Efficient hunking of multiple hunks

---

common/util/reload.py

The old reloader did actually not reload the window and text commands which is
very annoying. We could fix it ourself, but there is no real minimal fix for it,
or just use the code from @randy3k's `AutomaticPackageReloader`.
The following is a copy of
https://github.com/randy3k/AutomaticPackageReloader/blob/b568fcdf4e208d403f0fe5ee967016d589efa765/reloader/reloader.py
under MIT but @randy3k is also a member of GitSavvy.
Added the entry point function `reload_plugin`.
Discussion:
I tried a minimal fix but essentially this is the right code. We could remove some superfluous code like reloading dependencies as we don't have them but then we loose the ability to diff easily against a future version of this file upstream.
Since we do not use the reloader on upgrade (actually why?) we could …

Fix reloader code

---

core/commands/log_graph.py

The command graph current file is currently broken bc the actual file_path is not added to the command. So this is a simple fix, but an embarrassing bug.

Fix: Add `file_path` for graph current file

---

core/commands/log.py
core/commands/log_graph.py

Log as well as graph log can "filter by branch". With this PR the last used branch will be remembered.

Remember last branch used by log filter by branch

---

.travis.yml
README.md

Previous URL was missing colon:
```
fatal: repository 'git@github.com/divmain/GitSavvy.git' does not exist
```
Opted for the https URL because it is the default given by Github.

Fix: Git clone URL in README.md

---

GitSavvy.sublime-settings
core/commands/commit.py

Hey! 
I just think that the default commit message length should be 72, as it's stated in the git guidelines here: 
>Capitalized, short (50 chars or less) summary
>More detailed explanatory text, if necessary.  Wrap it to about 72
characters or so.  In some contexts, the first line is treated as the
subject of an email and the rest of the text as the body.  The blank
line separating the summary from the body is critical (unless you omit
the body entirely); tools like rebase can get confused if you run the
two together.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines
Therefore messages for commit command should be also 72 so they don't exceed the character limit and are marked in red. 
I guess this is a hotfix, change it if you think otherwise.

Change the length of the commit messages

---

core/commands/log_graph.py

Two fixes, two commits:
1. On `<enter>` the action panel should only open if the cursor is actually on a line with a commit. (E.g. not on one the decorated lines in-between)
2. On `<enter>` should immediately open a panl even if the commit detail bottom panel is currently open. The current behavior is that on first `<enter>` the detail panels closes, then you have to press `<enter>` a second time to actually open the action panel.

Fixup graph view

---

core/commands/diff.py

We already use `<TAB>` to flip between staged and unstaged changes. We can
use the same command to flip `base` with `target`.
I.e. open the branch dashboard, press 'f' on a branch. Now use '<TAB>'.

Allow flipping `base` and `target` in diff view

---

core/git_mixins/history.py
core/ui_mixins/quick_panel.py

We all know the log panel. This PR adds ref names (branch names, tags) to the list. There is a bit of fancy decoration/formatting around these refs. This makes it easier to search for these names.
E.g. search a tag

Show refs in the log panel

---

GitSavvy.sublime-settings
core/commands/commit.py

Change the length of the commit messages
Now the commit messages and the default length of the rulers is 72.
(Surely this wasn't a hotfix 😬, I want this in dev for testing.)

Pick #1162 for `dev` branch

---

common/util/debug.py

The `disable_logging` context manager sets `enabled=True` on exit which is obviously not what we want. We need to restore the previous state.

Fix: `disable_logging` should reset to previous state

---

Default.sublime-keymap
core/commands/log_graph.py

Actually `GsLogGraphActionCommand` should show the same actions as the base
`GsLogActionCommand`, and the compare commit view is the invariant here.
This is more DRY in that I expect that the actions I can take on a commit should be the same regardless of me using the log panel or the graph interface. E.g. if we add an action here it should up everywhere.

Simplify `GsLogGraphActionCommand`

---

core/commands/diff.py
core/commands/show_commit.py
tests/test_diff_view.py

Jumping from diff to file really was super sloppy implemented. It almost never jumped to the correct position. 
Implements mostly accurate jumping from diff to file by actually
parsing the hunk and recounting its lines.
For lines which are present on the b side (the view we jump to) this
is accurate of course. For deleted lines ('-') we, mildly arbitrary,
have to choose a good enough line.
If the user is not within a hunk, jump to the first visible line with content.

Mostly accurate jumping from diff to file

---

core/git_mixins/rebase.py

Closes #1166
This is the 'cheap' solution mentioned in #1166. We just take the first relative. By that we go from minimal 4 git commands down to 1.

Simplify `nearest_branch` algorithm

---

core/commands/push.py

I don't know how it happened but it actually did happen that the value of `confirm_force_push` becomes `None` after I disable and re-enable GitSavvy.
Anyway, it is a bit safer to assume the default value of True here.

assume the default value of confirm_force_push is True

---

Default.sublime-keymap
core/commands/diff.py
popups/diff_view.html
tests/test_diff_view.py

For the diff view, we have a 'word-diff' setting, but the output was annoying.
Let's fix that 😝 
Note that there is actually no one-size regex for word-diffs. Before, we just used `--word-diff` which uses a "default" which doesn't help in our context because it doesn't split enough. (E.g. it does not even split by word, and actually very often still by line.)  So hitting `w` now is a three state toggle, 'off' and then there come two regexes. The first one looks complicated and tries to match words, the second one (simply a `.`) matches single characters. 
Note that all three modes (t.i. the universal diff included) *can* look confusing. It is really to offer choices. 
Note that word diffs often suppress whitespace changes. The previous default did this, and it is probably okay. (That said …

Colorize word-diff

---

Default.sublime-keymap
common/util/view.py
core/commands/stash.py
core/git_mixins/stash.py
popups/stash_view.html

- Make `apply`, `pop`, and `drop` commands more DRY
- Save `stash_id` on the view
BREAKING: If a user now issues a command e.g. `gs_stash_apply` via
the Palette, it will select the current open/visible stash (if she
is looking at such a stash view.)
- Add typical shortcuts for the stash view.
`<enter>`: will open an action panel to 'apply', 'pop', or 'drop' the
current stash
`<a>`:     apply current stash
`<p>`:     pop current stash
`<D>`:     drop current stash
TODO:
~~- [ ] Really difficult to tell if or why we need three commands here, instead of one 
parametrized?~~
MOTIVATION:
Mostly psycho-safety. Stashes are part of my daily workflow, and often have lots of them. 'dropping' and 'popping' is destructive (well the reflog but..). Before I 'drop' a stash I usually `ts` and look at it …

Iterate on stash view

---

common/util/reload.py
git_savvy.py

Fixes #1190
- Drops ST2 not supported message.
- Add `then` callback to `reload_package` which gets called when
reloading has finished.
- To avoid a reload loop, we watch for install/upgrade flags set by
PackageControl. PackageControl takes 5s to finalize an upgrade.
We need to wait for the same time, to reload after PackageControl
is actually done.

Reload plugin after install or upgrade

---

core/commands/diff.py

Fixes #1176
~Here are two commits. Only the first one is the actual implementation. The second commit splits this functionality into two commands, and uses "proper inheritance" for the late binding.  However, I'm not super confident this is a strong step.  After all, I've learned that for the key-bindings a `setting.x` only matches true bool values, so we have to introduce a settings pair `show_word_diff, word_diff_mode` just for that.  `word_diff_mode` still is of type int, and actually selects which diff we show. `show_word_diff` mirrors this setting, and exposes it as `bool` just for the key bindings.~
~It's probably not worth it.  Keep in mind that we also have duplication and confusion with the "ShowCommit" view/commands. They don't support (inherit) the new word diff color modes, …

Accurate jumping in word diff mode

---

common/util/reload.py

This is merely for devs which reload once per minute while hacking
on this code base.  Once you see the message you can start testing.
When you don't see the message you know you have a syntax error and
reloading failed.

Flash status message after reloading

---

core/git_mixins/ignore.py

Python automatically converts newlines ('\n') for files opened in text
mode (e.g. 'at') to the OS's preferred line endings ('\n' on Linux and
'\r\n' on Windows). The manual line-ending handling in the IgnoreMixin
class therefore leads to extra '\r' bytes on Windows. This can be fixed
using the 'newline' argument of open().
Further, the IgnoreMixin currently always appends a newline before and after
the new entry. This leads to every second line being blank. The second
commit fixes the issue by appending the first newline only if the file does not
already end with a newline.

Fix/Enhancement: Improve newline handling in IgnoreMixin

---

core/commands/show_commit_info.py

Fixes #1202 
From the graph you can open a "detail" panel using `<m>`.
If you after that move around and the cursor lands on a line not
containing a commit, the panel showed the HEAD commit which is a
bug.
I apply a fix here but go one step further.
The panel now remembers the last scroll position for *each* commit
which makes it easier to read and compare different commits. (Before
it always jumped to the top position when switching between commits.)

Improve show commit panel

---

core/commands/commit.py

Also in ST 4. For a brief moment before the syntax is applied, `view.settings().get('syntax')` could be `None` and an exception is thrown (Nonetype is not iterable).

[ST 4] set a default value for syntax

---

core/commands/intra_line_colorizer.py
core/commands/log_graph.py
core/commands/stash.py
core/runtime.py
core/utils.py

Fixes #1233
Stash views can be long-lived. Since we identify stashs using a list
index (number), this number can get outdated rather quickly, e.g.
the user created a new stash, or dropped any of the previous ones.
We thus revalidate before we actually apply an action.
Some minor drive-by refactorings, also fixes one wrong `Thread` usage in `log_graph`.

Defensive stash view actions

---

core/git_mixins/rebase.py

Fixes #1224
We proper parse the `show-branch` output, t.i. we first lookup the
column our branch got in the prelude and then traverse the body content
always just looking if that exact column has an indicator.
Note that this doesn't make `nearest_branch` super-smart. It just fixes
the parsing. I.e. it might be the better option to present a list of
good candidates to the user instead of popping the first one.

Fix parsing of `show-branch` output

---

common/util/reload.py

Fixes #1205
Before we reload we `unload_module` every plugin. In case of a hard
error while reloading (e.g. often a syntax error), we actually try
to bring the old modules back via `reload_missing` but did not register
the actual plugins. We thus have all the code somehow (inconsistent)
loaded but none of the commands for the plugins which actually raised.
(In GitSavvy we only have *one* plugin, so actually no commands are
registered after that.)
With this patch we call `reload_plugin` again after failures. The goal
is to keep at least the reload command itself working.
This is good for developers but could be bad for users. However, we
really don't expect reload failures for end-users.

Permissive reloader

---

core/commands/reset.py

We basically always call resfresh after git actions so this is just an oversight.

Fix: refresh interfaces after `reset`

---

common/util/log.py
core/commands/custom.py
core/git_command.py

Fixes #1020 
For the panel output, generally normalize newlines to `\n` only. 
For #1020 we already had a patch at ea98d36 which stripped ANSI sequences from `self.git` output. This is probably not what we want (the OP sees ANSI sequences in the push log, this can only mean in the output panel) because the return value of `self.git` is not passed to the panel. So we revert said commit and instead strip for the panel only.

Normalize (live) panel output

---

core/commands/diff.py
tests/test_diff_view.py

Fixes #1225 
Fixes #1226 
Fix a regression since merging the intra diff annotations where we did not draw blocking but --cheaply to implement-- always putted a draw task on the ui thread even if we were already on the ui thread.

Small diff iteration

---

core/interfaces/status.py

Use-case: If you really dislike the changes you can unstage and then
discard the introduced changes.

Fix: Allow unstaging merge conflicted files

---

core/commands/inline_diff.py

Fixes #1195
After c8aaef1 ("Restore cursors after drawing inline_diff_view")
the `elif` is generally redundant here since we switched to drawing
with `"restore_cursors": True`.

Fix: Do not place cursor at col 0 on refresh

---

Default.sublime-keymap
core/commands/commit_compare.py
core/commands/diff.py
core/commands/log.py
core/commands/log_graph.py
core/commands/reset.py
core/commands/tag.py
core/fns.py
tests/test_describe_graph_line.py

Fixes #1260 
The graph actions were really limited. We add all commands usually found e.g. in `git k` or possibly `Sublime Merge`. 
Esp. 
- Checkout a branch (not only a commit detached)
- Create and delete tags
- Reset HEAD to 
- Allow cherry-picking and reverting multiple commits
Add `[f]` (unset `F`) to enter additonal filters via a typical input panel.  That's not the best UI because it requires the user to know all the flags (it is thus not really accessible) but it is otherwise just too useful. 
Examples: 
- set `--reflog` to immediately display "gone" commits e.g. after a rebase or deletion of a tag, branch. 
- set `-Ssearch_term` or `-Gsearch_term` to quickly pick-axe
- quickly limit via `-n` or `--since` etc.
Probably all these use-cases could be supported more directly, e.g. …

Redo the graph actions

---

Default.sublime-keymap
core/commands/blame.py
core/commands/diff.py
core/commands/show_commit.py
core/commands/show_commit_info.py
core/commands/show_file_at_commit.py
core/git_mixins/active_branch.py
core/git_mixins/history.py
core/parse_diff.py
syntax/make_commit.sublime-syntax
syntax/show_commit.sublime-syntax
tests/test_diff_view.py
tests/test_graph_view.py

Fixes #1204 
Fixes #1242 
- Enable keyboard shortcuts for the commit info *panel* (#1204)
- If the commit you're looking at is actually the `HEAD`, open the workspace file on `[o]`. (T.i. the normal writable version.)
- Add `[O]` to open the workspace (checked out) file a hunk is showing. 
(T.i. `[o]` shows the historical version of the file (readable) except you're looking at the HEAD commit, and `[O]` shows the current version of the hunk (read- and writeable).)
- Add `[g]` to open a graph focusing the current commit. (Aka: What is the context of this commit?)
Minor syntax improvements: highlight references (for example to issues or users) in the commit message, style commit meta header as a block.

Iterate on `show commit`

---

core/git_command.py

To show the command and working dir us usually useful information.  Otherwise
you probably see a "Verzeichnis ungültig" without ever seeing which directory was used.

Show command and working dir on fatal git errors

---

core/commands/log_graph.py
core/fns.py
core/git_command.py
core/runtime.py
core/utils.py
mypy.ini
syntax/graph.sublime-syntax
tests/test_graph_diff.py
tests/test_graph_view.py
tests/test_run_for_timeout.py

For the graph view the real bottleneck is painting huge graphs. 
- We switch to reading the git output in streaming mode.  Doing so we get the first meaningful bytes fast.
- We implement a view differ so that redraws get cheap.
- We implement a chunker so that long histories are drawn over a long time rather than blocking (in cases basically freezing) Sublime.
- We implement an aborter which aborts long running git processes or more often just aborts the draw-queue.
Notable:
- Implement a variadic `replace_region` render function.
Basically before:
And after:

Optimize graph render

---

core/commands/log_graph.py

Sublime's `intersects` surprisingly does not count the edges as in.
For example `Region(10, 20).intersects(Region(10)) == False`.

Fix: A cursor on the border of the viewport counts as in

---

core/git_mixins/rebase.py
tests/test_nearest_branch.py

Fixes #1261
If the repo has only one branch git changes the output format of
`git show-branch` completely and doesn't show a prelude anymore.
Also no column indicator. Example output:
```
$ git show-branch
[master] 0.22.2
```
We branch that off by handling the `ValueError` because it is an
edge-case.

Fix: nearest branch throwing if there is only one branch

---

Default.sublime-keymap
core/commands/show_commit.py
core/git_mixins/history.py
github/commands/open_on_remote.py
gitlab/commands/open_on_remote.py
tests/test_history_mixin.py

`find_matching_lineno` uses some obscure technique to compare two blobs, iirc this is the same as we had for the inline-diff. We switch to simple `git diff`.

Optimize `find_matching_lineno`

---

core/commands/show_commit.py
core/git_mixins/active_branch.py

For now revert the new behavior of `[o]` opening the current workdir
file if the change/hunk you're looking at is the most recent change
to that file.
We first just checked if the commit is the "HEAD" commit, then switched
to `newest_commit_for_file` which is more accurate behavior but shows
that this UX is confusing. (It is also relatively slow because we now
always need multiple git queries to answer the action.)
We state for now: either the user is in forensic mode, t.i. searching,
reading and looking around to understand a change; or the user sees a
change and then wants to edit (e.g. "fixup" that particular location).
The first interaction mode is bound to `[o]` again, for the latter we
have `[O]`. There is probably no need to mixmatch both.
The bevahior was first introduced in …

Revert `[o]` opens workspace file

---

GitSavvy.sublime-settings
core/git_mixins/branches.py
core/interfaces/branch.py
tests/test_fetch_branch_descriptions.py

- Only fetch descriptions for the branch dashboard. It's the only place where we actually use them, all other calls to `get_branches()` just throw that costly information away.
- If we fetch the descriptions, fetch them in one-go, and not per branch in a for-loop which never scales on any earth. 
- Fix bug: Descriptions can actually be real messages. If you `git branch--edit-description` a normal editor will pop up, only within GitSavvy we restrict it to one liners. Anyhow, we actually read the whole message and just printed it in the dashboard. This breaks the UI of the dashboard; only subject lines are supported here. I try to address this as well
- Remove the setting "enable_branch_descriptions" which seems not necessary anymore. (Iirc the UI still shows the `[E]` shortcut etc. even if …

Optimize fetching descriptions

---

Default.sublime-keymap
core/commands/log_graph.py
core/commands/show_file_at_commit.py
popups/log_graph_view.html
popups/show_commit_view.html
popups/show_file_at_commit_view.html

- In the graph view, `[o]` to open/show the commit
- For the file revision, `[o]` to open then commit, `[O]` to open the same file but currently checked out, and `[g]` to see the context[1]. 
- Add documentation to the help popups
[1] In the file revision view, we could either show the context of the commit or the context of the file log (t.i. applying a file filter). I took the first one, we'll see.

Complete `[oOg]` navigation

---

core/commands/__init__.py
core/commands/branch.py
core/commands/log_graph.py
core/interfaces/branch.py

We add a "delete branch" command to the graph actions. In the graph you can clearly see for example if a branch has been merged, and is not needed anymore. So this is a good fit.
We generally extract the command from the `branch` dashboard, and add the feature to offer a forceful deletion if the branch is not fully merged yet. (This is thus available for both views.) Before we just showed the git error to the user.

Add "delete branch" as graph action

---

syntax/show_commit.sublime-syntax

For merge commits git does not output "---\n" before the diffstat, so
we expplicitly check for it.

Fix: Markup diffstat for merge commits again

---

.travis.yml
README.md
core/git_command.py

#1287 and #1289 revealed that we require "2.16.0" since GitSavvy
"2.22.0". Make this hidden requirement explicit so that users know
what to do.
Note: The version jump was actually not intended, I misread the release notes. Then we could also revert some introduced changes. But just clearly bumping gives us the advantage of knowing a good minimum version as the new base. Clearly not all parts were 1.9.0 before. Having "2.16.0" makes it possible to use basically all known git features.

Bump required git version to "2.16.0"

---

core/commands/commit.py
core/commands/log_graph.py
core/view.py
syntax/make_commit.sublime-syntax
tests/test_commit_view.py

Fixes #980 
Fixes #1240 
- Refresh diff on `activated`
- Show "Nothing to commit" if there is nothing to commit

Dynamic commit view

---

core/commands/log_graph.py

Fixes #1301
As explained in https://git-scm.com/docs/git-log#_history_simplification
`<file_paths>`, `--simplify-by-decoration`, and `--sparse` interact.
For the common "Repo History" "sparse" is easy to follow and to
understand, but when showing a "File History" it is not a good default
mode anymore. The settings "--sparse", "--dense" etc. become rather fine
grained research methods. Git's "Default mode" (again see their docs)
becomes the only understandable mode.
So we just follow here and use history simplification only when showing
the "Repo History".

Do not use "simplify history" features for "File History"

---

Default.sublime-keymap
core/commands/diff.py
core/interfaces/status.py

When reusing diff views it is often desired to not force a specific
"cached" mode but just switch to the view. For example, a user might
have a key binding to diff the current file. Here it is better to
just have *one* binding to open or focus the diff, and switch the
"cached" mode via `<TAB>`.
We thus make `in_cached_mode` a three-state toggle, t.i. not setting it
(`None`) becomes also meaningful in that it only focuses the view.
Fixes regression introduced by c74159fef38729bb2c179b74b6831991a31ce70f
("Update "cached" mode when reusing diff views"), thus related to #1299.

Do not force a "cached" mode when reusing views

---

common/commands/debug.py
common/commands/view_manipulation.py
common/util/view.py
core/commands/changelog.py
core/commands/checkout.py
core/commands/commit.py
core/commands/custom.py
core/commands/diff.py
core/commands/inline_diff.py
core/commands/log_graph.py
core/commands/show_commit.py
core/commands/show_commit_info.py
core/commands/show_file_at_commit.py
core/commands/stage_diff.py
core/commands/stash.py
core/view.py
github/commands/commit.py
github/commands/pull_request.py
gitlab/commands/merge_request.py

A rather boring refactoring PR. We apply the `replace_view_content` function all over the place. This function has been introduced by the rewrite (or rather the diff rendering implementation) of the `log_graph`. 
Some drive-by refactorings has been made in some modules.
Fixes #1194 
Fixes #1196

Replace "replace view text" command

---

core/commands/__init__.py
core/commands/inline_stage_hunk.py
core/commands/stage_hunk.py
core/parse_diff.py

Implements #1304 
Comes without any bindings.  Add a key binding, e.g.
```
{ "keys": ["ctrl+alt+s"], "command": "gs_stage_hunk"},
```
or to command palette on your own.

Inline stage hunks

---

Default.sublime-keymap
GitSavvy.sublime-settings
common/util/__init__.py
common/util/diff_string.py
common/util/file.py
common/util/parse_diff.py
core/commands/inline_diff.py
core/git_command.py
core/git_mixins/history.py
core/interfaces/status.py
core/utils.py
popups/diff_view.html
popups/inline_diff_view.html

~~On top of #1305 for testing convenience.~~
It is recommended to bind `gs_inline_diff` to a key combo so it becomes a main entry point into the GitSavvy world. E.g.
```
{
"keys": ["ctrl+shift+["],
"command": "gs_inline_diff",
},
```
Now, this key acts like a toggle. You press it to switch to the inline view. Press it again to close it. Extra care has been taken that the viewport doesn't jump around while doing that. 
Being in that view, you can stage, undo staging, or discard changes. Use `[TAB]` to switch between the staged and unstaged mode. 
Use `[c]`, `[C]` or `[m]` to enter the commit message view.
Notable changes:
- Uses the builtin color scheme (just like the intra line colorization for the normal diff views).  You can compare toggling the built in "Show modifications" feat, (iirc …

Iterate inline diff

---

common/interwebs.py
github/github.py
gitlab/gitlab.py

Fixes #1312
Generally header keys must be read case-insensitive because a specific
casing is not enforced by any spec.  We go the simple route as we don't
have many use-cases in the code base and just normalize to lower case
when reading the response headers.

Lower case HTTP Response headers keys

---

common/commands/help.py
common/util/file.py
core/commands/inline_diff.py
core/commands/show_file_at_commit.py
core/interfaces/status.py

Fixes #1028 
Fixes #666 
- Avoid yaml parse errors by extracting the wanted key "file_extensions" via an ordinary regex.  This is actually faster as well. By a lot.
- Additionally, parse "tmLanguage" syntaxes because why not. 
- For a better "guess" for which syntax to use look at actual views currently open.  Remember these used syntaxes.
Side fix:
- Normalize line endings in the help files
- Normalize abs paths coming from the status view

Improve syntax parsing

---

core/commands/diff.py
core/commands/inline_diff.py
core/interfaces/status.py

There is no new binding attached here.  Assuming you have these already setup, you can now jump from a diff view mildly accurate to the inline diff.  This basically shows the whole context of the hunk, and allows small line by line operations. 
Howerer, this is only "mildly" accurate.  I wanted to make this easy and just reuse existing functionality.  For the "diff" view, we have `jump_position_to_file` which computes the correct position in the workspace file.  Since the workspace file is on the `b` part of the diff, the function interpolates locations on the red `a` side by jumping to next available context or `b` line. 
The same is true for the inline diff. Here we only have code to jump from the workspace file *to* the diff, again `b` (workspace) to green `b` (diff). 
Still, I maybe …

Implement jumping from "diff" to "inline-diff"

---

core/interfaces/rebase.py

Here, our `GsRebaseContinueCommand` wants to be smart by commiting the
staged files, assumely so that the user doesn't need to edit the commit
message.
But this approach here leads to wrong commit messages because git added
comments in the prepared message, and `--no-edit` will not strip these.
Also, this will literally do a new commit, for example with a new date
and author et.al. which is not what we want.
Example:

Fix: "rebase --continue" command

---

core/commands/commit.py
core/commands/log_graph.py
core/commands/show_commit.py
core/commands/show_file_at_commit.py

Reuse existing views more often.
- The prepare commit message view is actually unique per repo path
- "Commit view" is unique per `(repo, commit_hash)`
- "File Revision" is unique per `(repo, file, commit)`
- For the `log_graph`, having some `filters` applied makes the graph always unique (t.i. not to be reused.
If we don't do this, navigating between the views (for example `[oooo]`) clutters really quickly.

Reuse views more often

---

Default.sublime-keymap
core/commands/__init__.py
core/commands/next_hunk.py
popups/show_file_at_commit_view.html

With the Sublime gutter markers, they also introduced the commands
"next_modification" and "prev_modification".  Unfortunately, they
jump really between single, recognized edits, leading to frustrating
fine-grained jumps.  On the other side, GitGutter always jumped from
hunk to hunk but is slightly discouraged becuase of the - as it seems -
unnecessary overhead.
We introduce the commands "gs_next_hunk" and "gs_prev_hunk" which jump
hunk per hunk *using* Sublime's basically instant, and computational
cheap markers.
They can be used from normal views; for this PR we bind it for standard 
hunk-per-hunk navigation to the "File Revision View" on `[.,]`.

Implement smart next/prev hunk commands

---

common/util/__init__.py
common/util/parse_diff.py
core/commands/inline_diff.py
core/commands/show_file_at_commit.py
core/commands/stage_hunk.py
core/git_mixins/history.py
core/parse_diff.py
core/store.py

Teach the "inline_diff" and the "File Revision View" to recognize and handle initial revisions of a file correct. 
This includes a refactoring to the `util.parse_diff` code which now uses and follows the newer `core.parse_diff` code.  This is necessary here because the old parser could not parse diffs introducing/adding files at all.  (Basically it assumed a diff header length of 4 lines which breaks here.) 
The refactoring combines and touches `stage_hunk.py` as well because we now basically use functionality exposed there.  Within `stage_hunk` we again confused "row" with "line" so I fixed the types and names here in one go. 
The actual hotfix is after that rather smallish in c2f9148 and c4219e6.

Fixups for initial revisions of a file

---

core/commands/__init__.py
core/commands/fetch.py
core/commands/log_graph.py
core/commands/log_graph_smart_copy.py
core/commands/pull.py
core/commands/push.py
core/git_mixins/active_branch.py
core/git_mixins/remotes.py
github/commands/pull_request.py
syntax/graph.sublime-syntax

- Add "pull"/"push"/"fetch" to the action menu only when on the HEAD
E.g.
I think this will be convenient.
- Tweak syntax and mark "fixup!" and "squash!" prefixes as `string.other.rebase-hint.git-savvy`.  Just being "string" probably makes it yellow by default but you can fancy style as well
E.g.
This is should make it easy to spot if you still need to rebase before pushing or merging.
- Fine-tune "diff against" action: When on the head, open the normal diff views where you can actually stage etc.  Otherwise usually open a diff "commit..HEAD" (t.i. **not** workdir) which is best suited for reviewing topic branches (PRs). 
- Implement a smart copy feature to copy the commit hash, commit message, or a combination of both to the clipboard. 
E.g.

Small graph iteration

---

core/commands/inline_diff.py

As a follow up from #1327.  Already being in that "inline_diff.py" apply some basic refactorings.  Among others, again make a better distinction between "line" and "row". 
User facing changes:
- Flash a status message if the undo stack is empty.
- Maybe slightly better cursor movement after staging a single line.

Small refactor inside inline diff

---

Default.sublime-keymap
core/commands/diff.py
core/commands/show_commit.py
docs/staging.md
tests/test_diff_view.py

Fixes #1322
Removes the "word-diff" feature completely. Remaps `s` to `w` in the diff and commit view. 
As of now, no deprecation policy, no warnings.

Remove "word-diff" feature

---

common/ui.py

On resurrect, for example starting up Sublime with the status dashboard
open, we first `focus_view` in `__new__` which will run `render`
`on_activated`, then we `render` a second time in `__init__`.
This patch removes the (imperative) call in `__init__`.

Do not render dashboards twice on resurrect

---

syntax/diff.sublime-syntax
syntax/test/syntax_test_diff.txt

We switch here, and mark `b` instead of `a` as the filename for the
Goto funtionality.  This is (more) correct here because we generally
have the current workstate on the b-side.
Imagine you check in a new file or you renamed a file.  In the first
case, `a` doesn't point to any file, in the latter `a` points to the
old file.

Fix: Take the `b` filename as a goto symbol

---

core/commands/inline_diff.py
core/view.py

`row_offset` tells you for example that a given row is the 20th
in the viewport.  The algorithm didn't count for hidden rows which
happens if the user folds the code.
We switch to comparing the y values of two vectors.  `viewport_position`
return the top `y`, and `text_to_layout` returns the current `y` the
cursor is on.

Fix `row_offset` if the view has some folded content

---

Default.sublime-commands
Default.sublime-keymap
core/commands/__init__.py
core/commands/line_history.py
popups/line_history.html
syntax/show_commit.sublime-syntax

A "Line History" (aka "log wtf" or "log why") basically calls
"git log -L<some_file>,1:3".  Rarely used on the command line because of
its syntax, it is a super easy to write and then very useful tool in
the editor.  It is usually the faster (in terms of you get the info
you're looking for faster) "blame" and also the faster "File History"
because often you're only interested in some part of a file. Really
answering "Why is this line or section of code here?".
Comes with `[o]` to open the complete commit under the cursor;
`[O]` to open the file revision;
`[g]` to open the graph context.

Implement "Line History View"

---

Default.sublime-keymap
GitSavvy.sublime-settings
common/theme_generator.py
core/commands/log_graph.py
core/commands/log_graph_colorizer.py
core/commands/navigate.py
core/commands/next_hunk.py
core/fns.py
core/utils.py
core/view.py
popups/log_graph_view.html
tests/test_graph_diff.py

First implement following the graph upwards and colorize the graph. 
Use this walking to implement a new `gs_log_graph_navigate_wide` command which roughly follows the first parent and thus allows faster navigation. 
- Bind `alt+up` and `alt+down` for "wide" navigation.
- Bind `up` and `down` for normal per commit navigation.  (This was hidden behind the feature flag `arrow_keys_navigation`.)
Improve this jumping around by not showing the location we jump to "at center" position.  This, especially for the simple `up|down` movements, produces way to much viewport scrolling.  Instead show the location with some context using `show_region` introduced before.
When jumping "wide" inform Sublime's history machinery and save the previous location to enable the native `jump_back|jump_forward` …

Implement "wide" first parent navigation in the graph view

---

GitSavvy.sublime-settings
core/commands/log_graph.py

We used to store the state of the commit info panel (t.i. for the graph view) only globally, which of course didn't work non-buggy if you have multiple graph views open, be it in one window or multiple.  (Basically hiding the panel in *one* graph, also closed the panel for other graph views.)
We make this state local to a graph view.  We still also store globally (but only in-memory) which is then the initial state for new graph views.
Flip the default of `show_full_commit_info=true` because that is the standard behavior of git UI's when walking the repo history.

Remember commit info panel state per graph view

---

core/commands/show_commit.py
core/commands/show_commit_info.py
core/git_mixins/history.py
tests/test_graph_view.py

We already cached `git show <commit>` for the commit info panel.  We
now add this to the ordinary commit view.
We use the global app cache `store.cache` to share the cache between
both.

Optimize "show commit" caching

---

core/commands/inline_diff.py
core/commands/next_hunk.py
core/commands/show_commit_info.py
core/commands/show_file_at_commit.py
core/view.py

Our usage of `set_viewport_position` always is to fully control the
viewport, often to prevent any scrolling.  I thought the default
here is `False` but actually the default is to follow the global
`animation_enabled` setting (which in turn is `true` by default).
We hence force `False` in all[*] calls.
This removes some flicker and glitches when the user has animation on.
Fixes #1349 
[*]  Not fixed in `GsNavigate` to avoid a merge conflict because this call has been removed already in *dev*

Force no animation when setting the viewport

---

core/commands/inline_diff.py

Rewrite the logic for when we attempt a jump to the first hunk for
clarity.  Be defensive and avoid the more complicated and costly
call for `capture_cur_position`.
Related #1349

Be defensive when deciding to auto jump to first hunk

---

core/git_command.py
core/interfaces/__init__.py
github/github.py
gitlab/gitlab.py

Since b9e9928 (Rewrite settings abstraction for performance and
reliability) settings are cached and MUST NOT be mutated.
The code base is small here so instead of sending a copy of a setting
on access it is sufficient to make this small change here. We already
do not mutate settings anywhere else.

Hotfix reverse tab cycling

---

core/commands/commit.py

The commit view is now a hybrid, in the top you can write the message,
in the diff we make the view read only.  Unfortunately, replacing the
diff *always* creates an undo entry which can get in the way (a bit)
when writing the message.
This is not huge because we only refresh on focus. But we do it async
so from time to time the refresh can end after the user typed again.
We reduce this effect by just not drawing when the view is already
up-to-date.
This helps especially *if* the diff was up-to-date because in that
case `ctrl+z` is a no-op for the user.  (T.i. hitting `ctrl+z` gives
no visual feedback because both states were the same.)

Only re-paint commit message view if diff has changed

---

core/commands/next_hunk.py
core/view.py

We used to just show the first line of the hunk which is a mistake.  Instead show the full hunk (if it fits).  
Differentiate between wide and short jumps.  Short jump being jumps to a region already within the viewport (or parts of it).  For that, try to minimize the scrolling.  
Wide jumps on the other hand are jumps to locations *not* currently in the viewport.  In that case, try to bring the first line of the region *around* the center of the viewport. 
a1f27b8 (Extract `show_region` to `core/view.py`) is cherry picked from dev to reduce merge conflicts.

Show the whole hunk when using `gs_next_hunk`/`gs_prev_hunk`

---

core/commands/log_graph.py
core/view.py

After a26f976 (Improve `show_region`) wide jumps could easily lead to
overscrolling because in the log graph we only passed the target line
to highlight. So we adjust the code here to follow the `show_region`.
Fixes an edge case where we didn't jump at all if on the sibling commit
just before a commit chain ends. 
Also fix the help text.

Adjust wide jump feature for log graph

---

core/commands/diff.py

Since the "word_diff" feature is gone, we can make a clear message here easily.

Improve error message when staging with ignore_whitespace on

---

common/global_events.py
syntax/branch.sublime-settings
syntax/diff.sublime-settings
syntax/diff_view.sublime-settings
syntax/graph.sublime-settings
syntax/make_commit.sublime-settings
syntax/rebase.sublime-settings
syntax/show_commit.sublime-settings
syntax/status.sublime-settings
syntax/tags.sublime-settings

The general move here is to turn the "gutter" on because otherwise
Sublime will never highlight the current line.  But because we don't
show line numbers in our dashboards we shift the view content to the
left (with a negative margin) to reduce the empty whitespace area.
For some dashboards it looks nice to have the fold buttons on.  This
really just adds some visual guidance, although you can fold out for
example the stashes section using these.  Note that we must turn off
"fade_fold_buttons", because the negative margin shifts the hover area
of the buttons away from them.
Also: Intercept the native "Settings - Syntax Specific" command, as run 
by the "Preferences" menu, and show *our* settings.  This works towards
a replacement for our `ctrl+,` binding because `ctrl+,` is now used for …

Modernize syntax settings

---

syntax/show_commit.sublime-syntax

The commit syntax (used by `Show Commit` or the `Line History`)
incorrectly assigns `meta.commit_message` twice on the message itself,
and then does not *pop* that meta scope in the diff section.
We fix by flattening the stack and handling all "embeds" in `main`.

Fix commit syntax

---

Default.sublime-keymap
core/commands/log_graph.py
core/commands/log_graph_colorizer.py
core/commands/navigate.py

Navigation using for example using `up|down` was a bit laggy and jumpy.  
1. We implement a cached version of `view.find_by_selector` which speeds-up looking for fixup/squash commits.
2. We generally cache following a dot. 
3. We implement a local `GsNavigate` variant with constant performance. 
4. We don't own the cursor and try to respect the column the user was on.
Successor of #1367

Performant and sane graph navigation

---

syntax/diff.sublime-syntax

For combined diffs, like
```diff
diff --cc core/commands/next_hunk.py
```
teach the diff syntax to recognize this as a git diff header. 
Not included is proper highlighting the actual hunk, for example if a line starts with ` +`.

Teach diff syntax "--cc" headers

---

core/commands/show_commit.py
core/git_mixins/history.py

Fixes #1368
Do not cache reading the HEAD commit. Everywhere else, we already checked if the `commit_hash` is `""` or `"HEAD"` to skip caching, so this one was missing here.
We go one step further, special case "HEAD", and dynamically update and thus follow HEAD.
The use case is a user binding to `gs_show_commit` with `commit_hash`
set to `HEAD`.  For example:
```
{
"caption": "git: show HEAD commit",
"command": "gs_show_commit",
"args": {
"commit_hash": "HEAD"
}
},
```
However, arbitrary references, like for example tags or branch names, are not supported.

Do not cache reading the HEAD commit

---

Default.sublime-keymap

We always jumped to HEAD using `g` from the status dashboard.  This is not helpful when reusing the graph view and the user actually did a research some pages down.
Switch that off.  Now `g` will just *focus* the graph view. (And technically follow whatever it followed before.)  
If *not* reusing the view, the first commit will be marked.  Often the HEAD but if not `h` to jump to the HEAD is maybe good enough.

Let `g` in the status view not forcefully jump to "HEAD"

---

common/global_events.py

If "subl -w" is set, Sublime has problems focusing the active view
but only if we start the git command from within Sublime itself, for
example using GitSavvy itself or Terminus.
We mitigate by trying to force focus the just loaded view.  (A way to
bring the view's window to front would be handy here.)

Force focus for native git files on load

---

core/commands/commit.py

The interaction between automatically setting the `read_only` state and
automatically updating the diff in the background confuses Sublime
in a way that it freezes and shuts down.
A reproduction was:  Put the cursor in the read only area, for example
the help comment.  Try `ctrl+z` for undo **while in the read-only area**.
Note that it tells you in the status bar "Undo: ..." without any visual
difference.  Move to the writeable area, `ctrl+z` again.  Now, Sublime
freezes.
The fix is to switch the `read-only` state not sync, t.i. using the
`on_selection_modified_async` callback.  From the perspective of the
fix it looks like "undoing" triggers a cursor movement *to* the
read-only area, and a sync selection-modified event then toggles the
read-only state which crashes Sublime.

Fix possible freeze when undoing in the commit message view

---

common/global_events.py

For example, the user might `rebase --abort` while looking at the
"git-rebase-todo" file which will in turn delete the file.

Do not attempt to save a git file if it doesn't exist

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
Default.sublime-keymap
core/commands/commit.py
core/git_mixins/history.py
core/ui_mixins/quick_panel.py
syntax/make_commit.sublime-syntax
syntax/test/syntax_test_make_commit.txt

In addition to the `@<tab>` and `#<tab>` helper, 
1) add `fixup<tab>` and `squash<tab>` helpers.  When invoked a custom log panel opens.  On selecting a commit, we construct a fixup (or squash) commit message subject.  The user can add some further comments after that or `ctrl+enter` to actually commit.  (T.i. we don't commit automatically.)
2) Hitting `<tab>`exatly on BOF position, t.i. usually immediately after opening the view, will also show the recent log.  Either just for reading, or, on `enter`, to use the commit subject, usually as a template for further editing so we stay at BOF position after that.
Also some small fixes and glitches around that code. 
Fixes #487 
Ref #1355

Implement "fixup" helper in the commit message view

---

Default.sublime-commands
Default.sublime-keymap
core/base_commands.py
core/commands/__init__.py
core/commands/branch.py
core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py
core/git_command.py
core/git_mixins/history.py
core/interfaces/rebase.py
core/runtime.py
syntax/graph.sublime-syntax
syntax/test/syntax_test_graph.txt

This adds rebase functionality to the graph view. 
- `[r]` to open above rebase menu 
- `[W]` to reword/edit the commit message of the selected commit
- `[E]` to edit the selected commit
- `[R]` to start automatic autosquashing beginning with the selected commit  (t.i. apply all fixup and squash commits without further asking)
If the cursor is on a fixup or squash commit, the menu has an additional item "Apply fix" which just applies the selected fixup. 
What's not in:
[1] `rebase-merges` requires git v2.18; the `preserve-merges` we used to emulate is deprecated.  Sublime does not ship a syntax for the new todo format, so it looks very ugly.  But it is very powerful, for example "Extract selected commits to a new branch" is possible.  
[2] Examples: "Squash selected commits", "Flip …

Rebase actions in the graph view

---

Default.sublime-keymap
core/commands/log_graph.py
core/utils.py
popups/log_graph_view.html
stubs/sublime.pyi

- For `f`, maintain a history of previous filters.  Use `up|down` while in the input panel to access them.  Pre-populate the history with some common good settings, for example "--reflog" is very useful.  Also compute  a "--author" arg based on the current commits author.  
- Add `l` (**ls**-tree), to add or remove paths to the command.  This is really a dynamic variant of our "File History".  You can also select paths, not just concrete files; and of course multiple ones.
- For `F`, document the binding in the `?` tooltip 🙄.  Make it a toggle which will toggle `filters` and the file paths.  (Also `filter_by_author`, which can probably be deprecated with the new helper for `f`.)  For example, looking at a "File History" `F` will show the commit with full context.

Improve dynamic filtering the graph view

---

core/commands/log_graph_rebase_actions.py

- Do not offer autostash if only one commit is selected because it is then a noop
- Prefer the checked out branch name

Fine tune rebase menu

---

Default.sublime-keymap
core/commands/commit.py

1. Allow the helpers at EOL position if the line is a fixup or squash
line.
This is actually the position the user lands on after using the helper,
and we want to allow selecting a different commit easily.
2. Only trigger the helper if there no text follows.
Here, for example the user first wanted to do a "fixup" but then decides
to edit the first word from "fixup" to "squash".  The user therefore
goes to BOL, deletes the right word, and types "sq<tab>" to autocomplete
to "squash".  This just works now because "squash" is via the help text
always in the buffer.
3. Preselect a possible given commit in the subject line.

Fine tune fixup helpers

---

Default.sublime-keymap
core/commands/log_graph_rebase_actions.py
popups/log_graph_view.html

`[R]` was always bound to start an interactive rebase session in the pre-release phase. 
This was not a stupid idea and we switch it on again.

Add `[R]` binding to start an interactive rebase

---

core/commands/log_graph_rebase_actions.py

Fixes #1391
We closed the panel automatically if it didn't contain the text
"rebase --continue" which works okay unless the command itself is
"rebase --continue".  (The idea was rather to check the output help
text from git.)
We switch to check for `not in_rebase()` which seems a natural fit.

Fix: Close rebase panel automatically if the rebase finished

---

common/commands/view_manipulation.py

Fixes #1395
In NeoVintageous/NeoVintageous#749, pushed as 1.22.0 (Oct 2020), the
relevant commands were renamed.
We follow the new names, but for now also call the old ones.

Fix `vintageous_enter_insert_mode` for NeoVintageous 1.22.0

---

core/git_mixins/status.py

The current behavior is to *not* list `i-t-a` files at all.  Basically
they disappear after adding.
We move the `i-t-a` files to the unstaged section, following git cli
behavior here.  This indicates that diffing the file will work.

Fix: List `intent-to-add`ed files as unstaged

---

core/commands/log_graph.py

We currently work visually here, t.i. on the actual drawn graph, and
have to expect shortened commit messages.  We always worked with a
cleaned original message (see: `message_from_fixup_squash_line`) but
have to do the same (`.rstrip(".")`) when comparing with other messages.
The code also assumed the original message is the truncated one.
This is often but not necessary always true. We therefore sort by length
before comparing with `startswith`.

Fix: Compare longest with shortest commit message

---

core/ui_mixins/quick_panel.py

The active branch cannot be a remote branch (you can only do
detached checkouts on these).
Let's save the call to `get_current_branch_name()` here.

Do not guess `selected_branch` if only remote branches are shown

---

core/commands/log_graph.py

Since 0bcabc7e (Add "fetch"/"push"/"pull" to the graph menu) published
with 2.26.0 (Sep 2020) a user cannot open the actions menu if on a sole
detached HEAD commit.
Generally, the idea of having a sparse dict to represent the line or
commit info makes the handling here brittle and hard to read.  We can
handle that later, for now `info["local_branches"]` can fail and must
be made safe using `.get()`.

Fix: Graph menu should open if cursor is on a detached HEAD

---

core/git_mixins/remotes.py
github/commands/open_on_remote.py
github/commands/pull_request.py
github/git_mixins/remotes.py
github/github.py

While investigating #1384, cleanup and optimize code in `github.remotes.py`. As a refactoring, to be read commit for commit. 
Only notable change is to consider "upstream" (not only "origin") as a good automatic integration candidate.  (Actually the GitHub tooling puts the fork under "origin" and the original "source" repo under "upstream", see https://github.com/timbrel/GitSavvy/issues/1384#issuecomment-706601919, so this change provides better inter-op.)
The last commit implements option (2) from https://github.com/timbrel/GitSavvy/issues/1384#issuecomment-707134940
Fixes #1384 
I decided for (2) here (although there is really no clear winner) because
- It is generally simpler *and* faster
- ~Asking the internet (GitHub API) is way more flaky.  It is unclear what we should do if the …

GitHub remotes simplified

---

core/commands/flow.py
core/commands/push.py
core/git_command.py
core/git_mixins/active_branch.py
core/git_mixins/branches.py
core/interfaces/branch.py
github/commands/pull_request.py
github/git_mixins/remotes.py
github/github.py

Fixes #1273 
Continue the work done in #1386.  Reduce side-effects (git calls).
```
Create PR master (before)
(D) [ 78ms] $ git rev-parse --abbrev-ref --symbolic-full-name @{u}
(M) [ 85ms] $ git branch --no-color
(D) [ 67ms] $ git remote -v
(D) [6052ms] $ git push --set-upstream fork test:test
(D) [ 78ms] $ git rev-parse --abbrev-ref --symbolic-full-name @{u}
(D) [ 62ms] $ git rev-parse --abbrev-ref --symbolic-full-name @{u}
(D) [ 78ms] $ git for-each-ref --format=%(HEAD)%00%(refname)%00%(upstream)%00%(upstream:track)%00%(objectname)%00%(contents:subject) refs/heads refs/remotes
(D) [ 94ms] $ git status --porcelain -z -b
(D) [ 66ms] $ git remote -v
(D) [ 66ms] $ git remote -v
(D) [ 78ms] $ git config --local --get GitSavvy.ghRemote
(D) [ 62ms] $ git remote -v
(D) [ 78ms] $ git config …
```

Iterate "Github: Create Pull Request" and "git: push"

---

core/commands/intra_line_colorizer.py
core/commands/log_graph.py
core/commands/log_graph_colorizer.py

- Switch to iterative (instead of recursive) depth first traversal.
In Sublime Text/Python we have a recursion depth of 1000 after that we crash.  
The recursion algorithm is also very slow for deep or long paths.
- Use cooperative thread hopping
Since we need to run on the UI thread (because of excessive queries 
against the view) slice the work into 17ms so that Sublime doesn't
freeze on long paths. 
Tested with paths 3000-5000 commits deep.  The recursion algorithm throws
after for example 1.5s.  The iterative algorithm runs in a fraction of time,
for example 350-500ms but obviously blocking too long.  Using thread hopping
we basically draw the viewport immediately, and thus give the illusion of
immediacy we actually don't have.

Faster dot colorizer

---

core/commands/log_graph.py

We switch to the order "fetch/pull/push" as fetch is used to often,
basically to preview the upstream changes.

Move "Fetch" to the top of the actions menu

---

syntax/make_commit.sublime-syntax
syntax/test/syntax_test_make_commit.txt

Fine tune syntax highlighting of references in the commit message
- Do not highlight sole "@" characters. 
- Generally, do not highlight the surrounding spaces.
- Narrow down sha highlighting.  Usually these are surrounded by spaces (not `\b\`) or (seldom) in the form of `master@3fc528c`

Fine-tune ref highlighting in the commit message

---

core/commands/push.py

Fixes #1130 
Replaces #1387 
On `gs_push`, if we're already behind upstream offer to do a forceful push instead.  The default is to do nothing.  (Similar to the UX when deleting a branch.)

Offer forced push if behind

---

core/base_commands.py
core/commands/checkout.py
core/commands/commit_compare.py
core/commands/fetch.py
core/commands/log.py
core/commands/log_graph.py
core/commands/merge.py
core/commands/pull.py
core/commands/push.py
core/commands/remote.py
core/commands/reset.py
core/git_command.py
core/git_mixins/remotes.py
core/interfaces/branch.py
core/store.py
core/ui_mixins/quick_panel.py
github/commands/configure.py
github/commands/open_on_remote.py
gitlab/commands/configure.py
gitlab/commands/open_on_remote.py
stubs/sublime.pyi

- For both, `show_remote_panel` and `show_branch_panel` implement a separate `on_cancel` callback.  We usually abort on cancel (value `-1`) which makes all our usages simpler. 
- We had a property `last_remote_used` very visible on `GitCommand` but its getter was never used actually because the caller didn't liked its side-effects.  Remove that and use the `store` for it. 
- Save another git call: `show_branch_panel` used a separate git call to get the current branch name.  Don't do that. Because `get_branches()` returns rich information we already have what we want *if* we don't reduce the info to `.name_with_remote` straight.

Cleanup quick panels

---

core/commands/push.py
core/interfaces/branch.py
core/ui_mixins/quick_panel.py
github/commands/open_on_remote.py
gitlab/commands/open_on_remote.py

`allow_direct` has been introduced by #791.  If `True` we will not ask
the user for a remote if there is only one configured.
We hereby turn this on for more commands, actually as suggested in
https://github.com/timbrel/GitSavvy/pull/791#issuecomment-338007502
See also the recent #1411

Use `allow_direct=True` for more commands

---

GitSavvy.sublime-settings
core/base_commands.py
core/commands/log_graph_rebase_actions.py
core/commands/push.py
core/git_mixins/branches.py
core/interfaces/branch.py
core/ui_mixins/quick_panel.py
docs/remotes.md
github/commands/pull_request.py

Fixes #1411 
- Remove setting "prompt_for_tracking_branch". 
a) If there is only one remote, take it.  Ask for the remote branch name, but the input handler is prefilled with the name of the current branch.  That essentially leads to one `<enter>` to push. 
b) With more remotes, we first ask for the remote, then for the branch name, again prefilled with the name of the current branch.  Ideally, coming down to two `<enter>`s.  
At any time `ESC` aborts the process.  `-u` is always set. 
If we'd just take the local branch name for granted, we could go to no question, t.i. an immediate push, if there is only one remote.  I don't think that this is a good idea. 
For b) we came down from two to one question because we would pause the process with the remote question.  But the flow would be a …

Streamline push

---

core/commands/fetch.py
core/store.py
core/ui_mixins/quick_panel.py

With "show_option_all" the panel gets an imaginary first item, namely
"All...".  We want to make it possible to save this selection, and to
not interfere with all other remote panels which do not set this option.
(Currently, only `gs_fetch` uses it.)
For example, we want to support a user always fetching all but pushing
to (of course) a specific remote.
Enhances #791. We change the initial value back to the common "origin"
in all cases.  Generally, fetching all does not scale, and it is an
edge-case feature.

Enhance `last_remote_used`  

---

core/commands/commit.py
core/commands/diff.py
syntax/diff_view.sublime-syntax

After committing, we often land on an empty diff view, close these views automatically.

Automatically close "used" diff views after commit

---

core/commands/commit.py

As quality-of-life hack: If you enter the commit process with nothing
staged, assume `include_unstaged`.
This is transparent as we always commit what's visible in the diff in
the commit message view.  If `-a` is not what you want, the user can
either just close the view, stage something and usually using `[c]` in
some of the views enter the commit process again.  She can also just
switch to a diff view, stage something and hit `[c]`, t.i. without
closing the view, as the view will update.

Assume `commit -a` if nothing is staged yet

---

core/commands/commit.py
core/commands/log_graph_rebase_actions.py

Fixes #1355
As suggested in #1355, add a menu entry to "create" a fixup commit from the Repo History.  
In reality, we don't actually "create" the commit but rather prepare the commit message and then open the commit view.  Another `ctrl+enter` will then create the commit. 
This need some discipline as a user might select the option here prior editing, saving and staging the wanted change.  It totally feels like a very useful, "correct" option though here in this menu.  Maybe further tweaking is necessary.

Add "Make fixup commit" to the rebase menu

---

common/global_events.py
common/util/debug.py
core/commands/status_bar.py

Fixes #1094
The old throttler had a 100ms wait time but this is not a functionality
we need here. E.g. if you create a new view, Sublime puts two events on
the queue, namely 'on_new' and 'on_activated'.
By using the `runtime.throttler` we ensure that only one task on the
worker wins and gets executed.
Note that the implementation does not differentiate between different
views, windows, or repo paths. So there is a risk to undercall now.
Although it is very unlikely to get multiple triggers from different
sources in exactly one task, we capture and merge such events until the
worker thread is ready again which can be at any time in the future.
Note though that the *last* event wins in such cases.
This is not the best we can do, merely a baby step.  #1151 was ahead of this 
approach …

Rewrite throttler for the status bar

---

core/commands/next_hunk.py

For `jump_to_hunk`, if there is no hunk to jump to still bring the
selection, which might be on the only hunk currently available, into
the viewport.
Basically, show the cursor if a "jump" is requested for orientation.

Always bring hunk into viewport

---

core/commands/commit.py
core/commands/diff.py
core/commands/inline_diff.py
core/exceptions.py
core/git_command.py
core/git_mixins/history.py
syntax/show_commit.sublime-syntax
tests/test_commit_view.py
tests/test_diff_view.py

Fixes #1426
Showing the diff is optional in the commit message view.  (It is of
course good to have but a user can commit anyway.)
In the case the diff is not decodable, do not show the error modal
dialog anymore.  Instead print an error message in place of the diff.
- Do the same in the diff view fixing a regression from 4060ae79 (Other: 
improve catching errors, Jul 2017).
- Do not open an inline diff view if the diff is not decodable.  (Just 
show the error modal, as we don't have a view to print the error message.)
- Fix: The implicit logging used the same `decode_stdout` procedure, t.i.
with showing a modal.  Do not do that but use a defensive way so we can 
actually opt-out of automatic decoding. 
- Also decode the "Show Commit" output safely.  Ref #1371

Catch decode errors in the commit message view

---

core/runtime.py

Reading `THROTTLED_CACHE` seems safe as we never pop items from it.
Unless we hot-reload.  Then we evict everything, and the code can
possibly throw.
Just choose the safe `.get()` variant.

Safely access `THROTTLED_CACHE` dict

---

core/parse_diff.py
tests/fixtures/diff_2.txt
tests/test_diff_view.py

For example, the Line History might yield multiple commits, and git
might put branch decoration (for example "(HEAD -> ...)") on the first
line right after the commit hash.
Rewrite `CommitHeader.commit_hash` to not include them.

Fix: Respect branch decoration in commit headers

---

core/commands/log_graph.py

Especially with feature branches of different lengths it happens that
we already see commits from the main line while other branches are
still running.
Although not an error per se it is confusing and often wasteful.  Sort
the dots by `dot.pt` to restrain exact visual order.

Traverse dots in visual order

---

core/commands/diff.py

The "jump-to-file" algorithm did not count that combined diffs actually
have a wider "line-mode" section than the usual patches.
We change from `max(col, 1)` to `max(col - mode_len + 1, 1)`.
Note that for `mode_len = 1` nothing changes.

Teach "jump-to-file" to compute columns for combined diffs

---

core/interfaces/rebase.py

Fixes #1418
Fix a regression introduced by 1e31e247 (Let `LogPanel` continue
synchronous on `enter`).
Commit 1e31e247 introduced that `show_log_panel` continues on the main
thread on `enter`.  Hence actual users of `show_log_panel` must
explicitly opt-in and hop to a different thread if they want to.
Even for the rebase dashboard running on the main thread had the
advantage that the user could not issue different commands *while*
a rewrite was in progress.  Generally though, these rewrites possible
take a long time so it can feel like Sublime freezes.  Running on the
worker might be the better solution here.
The actual bug #1418 describes is a bug in the long distance.  When the
user uses the "live_panel" panel feature for "git commit" commands,
we deadlock for "live_panel_output_timeout" …

Fix: Ensure rewrite actions run on the worker thread

---

tests/fixtures/diff_2.txt

This reverts commit cc4cb033795f58f83852de91a825ec5024df8685.
There is actually no newline in the git show-commit output, so the
the change was non-sense and we revert.

Revert "Add newline after the commit message in a fixture"

---

Default.sublime-keymap
core/commands/diff.py
core/commands/stage_hunk.py
core/fns.py
popups/diff_view.html
tests/test_diff_view.py
tests/test_hunk_counting.py

Ref #1435 
- For consistency with the status dashboard, bind `sud` to stage, unstage, or discard.
- Allow to act on arbitrary selections, t.i. allow partially staging a hunk or multiple hunks, for example a single line.
- Bind `SUD` to stage, unstage, discard the complete file under the cursor.
Staging single lines or generally parts of a hunk usually comes with some complications as to where to apply these lines, t.i. basically which starting lines we compute for them.  Both our inline-diff and for example `git gui` apply some heuristics and maybe artificially move a `+` to a (maybe, hopefully) desired line.  We don't do this here but instead expect that the user indicates making *multiple* selections which lines do belong together.  E.g.:
As there are two lines selected, we handle them …

Improve staging (et.al) in the diff view

---

GitSavvy.sublime-settings
core/git_command.py
core/runtime.py

Fixes #1437
For the live logging feature we basically implement `communicate` on our
own.  `communicate` generally works with three threads, two *reader*
threads, one for stdout, one for stderr, and one fan-in or *join*
thread.
Let's make the reader threads short reading loops over the buffer io
streams.  Zip both streams `out` and `err` to keep the order of output
close to the original order.  Use no-op classes `Out(bytes)` and
`Err(bytes)` to tag the output messages for later processing.
The fan-in thread is the thread which initiated the git call, it is in
a busy loop.  Log while unzipping the input lines.
Since the fan-in thread is already busy looping we cannot deadlock with
`M`.  Note that we basically do *not* log *live* if the initiating
thread is actually `M` because we cannot …

Fix live logging feature

---

core/git_mixins/status.py
syntax/dashboard.sublime-syntax

Let's read out more detailed rebase status info when rebasing halts.
The status bar shows the progress `(n/m)`
The dashboards show which todo item we're currently trying:

Add detailed rebase info to the status

---

core/parse_diff.py
tests/test_hunk_counting.py

Fixes #1452
We currently parse the whole line which can fail because the text after
the second "@" marker can contain arbitrary context information.
The fix is to parse only the text between the "@" markers.

Only parse text between "@" markers in the hunk header

---

core/commands/amend.py
core/commands/init.py
core/commands/inline_diff.py
core/commands/mv.py
core/commands/status_bar.py
core/git_command.py
core/git_mixins/history.py
core/utils.py
tests/test_status_dashboard.py

This is mostly a boring refactoring around `self.repo_path`.  Some guidance:
* Make the dependencies more clear.  Do we need a *view*, or a *window*, or a *filename*?   
* Avoid repeated "realpath" calls.  On Windows we never had this functionality anyway, it was a noop.  But also `git --show-toplevel` already returns the resolved path.
* Implement `resolve_path` (as a primitive `realpath`) for all OSes.  (We still need this for `file_path` as `repo_path` is always resolved.)
* Do not cache the `file_path` nor the `repo_path` on the view.

Refactor getting the repo path

---

common/util/debug.py
core/commands/log_graph.py
core/git_command.py
core/utils.py

- Instead of asking `git --show-toplevel` traverse the path upwards looking for a `.git` file/folder.  This is of course significant faster.
- Instead of working with a resolved ("real") repo path, try to use the user visible, non-real path.  
For example, if the user maps a folder to `D:\my-project` and starts `subl` from there,  do **not** show `C:\\Users\foogar\da\dum\my-project` as the "real" top folder.  The "real" folder is a detail the user should not see.
Replaces #1081

Search for toplevel git dir without asking git

---

tests/test_json.py

`os.walk` already walks the tree recursively, hence calling
`self._get_files` recursively is not what we want.
For one, it actually does not ignore the dirnames as the outer `walk`
will just walk away, then it emits everything twice.

Fix walking the directory tree using `os.walk`

---

core/commands/commit.py
core/git_command.py
core/git_mixins/rewrite.py
core/git_mixins/status.py

Fixes #1461
Usually `{repo_path}/.git` is a folder but for workspaces it is a file
pointing to another folder in the main repository.  Introduce
`git_dir()` which returns the resolved, "real" git dir.
We use this where on the command line `git rev-parse --git-path FILE`
would be appropriate.

Implement `git_dir()` and use it

---

common/ui.py
common/util/view.py
core/commands/fixup.py
core/commands/quick_stage.py
core/commands/status_bar.py
core/git_mixins/status.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
core/interfaces/tags.py
core/store.py
mypy.ini
tests/test_git/common.py
tests/test_graph_view.py
tests/test_status_dashboard.py

Fixes #1095
Fixes #1102
Replaces #1151 
Store `git status` information in `store["status"]`.  Implement a triangle where we fetch the status of a workdir, update the store, and in turn notify subscribers.  Note that `get_working_dir_status()` still returns the state for ease of use after notifying interested subscribers.
Whenever we fetch an update of the current status, the status bar view and for now the status bar dashboard react and redraw itself.  This replaces #1151 which did really the same thing in an earlier state of the repo.  Thus it does not reduce status calls anymore as this has been implemented already but use the information of status calls more efficiently. 
Also has some refactorings, basically simplifying outdated code (for example see `reset_cursor`, `tab_size` etc.) …

Iterate on workdir `status`

---

core/base_commands.py
core/commands/push.py
core/git_mixins/remotes.py
core/store.py
core/utils.py

Instead of always offering the remote/branch-name wizard suggest
a `remote/local_branch_name`.  This keeps the eye at the top of the
view on the Command Palette for the normal case.
For the remote branch name, always suggest the local name.  For the
remote name, respect the values `gitsavvy.pushdefault` and
`remote.pushdefault` from the config, and fallback to "fork", origin",
and then any other known name.
Always use an in memory cache `last_remote_used_for_push` which stores
the last used value.  This key is now distinct from `last_remote_used`.
Automatically persist a used remote in `gitsavvy.pushdefault` if the
suggestion was overriden by the user so it will be suggested the next
time; even after restarts.  Persist after the comlete wizard has been
finished, just before pushing, t.i. …

Suggest remote branch when creating a PR

---

Default.sublime-keymap
github/commands/__init__.py
github/commands/open_issue.py
popups/line_history.html
popups/log_graph_view.html
popups/show_commit_view.html

Whenever we land on an issue, in a commit message or graph view, let
`[o]` open the issue (or PR) in the browser on GitHub.  
Show a simple popup to do the same on hover.

Open issue at hand on `[o]` or via popup on hover

---

common/util/log.py
syntax/output_panel.sublime-settings
syntax/output_panel.sublime-syntax

Start with just a little touch.  We want the settings to apply because
Sublime Text 4 renders the panel with line-numbers and gutter etc., t.i. 
with different defaults.

Add simplistic output panel syntax plus specific settings

---

core/commands/init.py

Do not quote the name and email.
The original author maybe thought we need to quote here like on the
command line, but we pass args down so quoting would result in storing
a quoted name which is not what we want.
The old code did produce something like

Fix `gs_setup_user`

---

core/commands/init.py
core/fns.py
core/git_command.py
core/settings.py
tests/test_gsclone.py

Fixes #1469 
Fixes #1470 
- Read a possible url from the clipboard to use in the clone wizard
- Suggest a sibling parent of the current open folder as the target to clone to
- Use the output panel as a progress indicator.  
- Open a new window which will host the to be cloned project immediately.  This leads to a much nicer UX.  But reuse an empty window.
- If there is no open folder, suggest `~` or, on Windows, `~\Desktop`.
For `gs_init`, suggest to initialize the repository in the currently open folder.
We want to support two workflows:
- Cloning as a sibling project
Invoke `gs_clone` from any, already used window
- Cloning possibly temporary projects to a default location
Invoke `gs_clone` after (`ctrl+shift+n`) creating a new, empty window.
TBC:  It seems plausible to let the user …

Improve `gs_clone` and `gs_init`

---

core/parse_diff.py
tests/test_diff_view.py

If the filename contains spaces, git adds a "\t" at EOL.  Strip this
tabulator sign as it's not part of the name.

Fix: Extract filename from diff if it has spaces

---

core/git_command.py

As an edge case, for example when viewing a file in a zip container,
Sublime Text might return a "correct" looking file path although the
later `resolve_path` will throw as the file does not exist.
That case was generally handled by a later call to `os.isdir`.  It is
only within this subroutine we might use the invalid filename.
Bug introduced by a5561c59 (Fallback to first folder only if necessary).

Test if the reported filename is accessible

---

core/commands/stash.py

Applying or popping stashes might fail with merge conflicts.  Always
`refresh_gitsavvy()` so that for example the status dashboard reflects
those merge conflicts immediately.

Always `refresh_gitsavvy` when applying stashes

---

core/commands/diff.py

We implemented this for "inline-diff" views, let the diff views follow.
The idea is to setup one key binding, for example
```
{
"keys": ["ctrl+shift+."],
"command": "gs_diff",
"args": { "current_file": true }
},
```
which will then either create or switch to a diff view *or* close the
diff view if it's already active.

Let `gs_diff` key bindings act like a toggle

---

Default.sublime-keymap

For example: a user just writes "fix lirum" and now wants to complete
"lirum" using `tab` completion.
The trailing `.*` were introduced in b1f59acc (Fine tune fixup and
squash helper triggers).  The idea was to allow running the helper again
just on `tab` at EOL position in case a user selected the wrong commit.
Revert `.*` to `$` and add a special explicit branch, e.g. `fixup! .+`,
for that exact use case instead.

Fix: Do not bind fixup helpers if the message just begins with "fixup"

---

syntax/output_panel.sublime-syntax
syntax/test/syntax_test_output_panel.txt

Highlight links in GitSavvy's output panel

---

core/commands/show_file_at_commit.py

Show the historical file revision as verbatim as possible as we're
comparing the file with the previous version read from git directly.
(Using `set_reference_document`.)

Disable indentation guessing for historical file views

---

core/commands/log_graph.py

Checking `returncode` and not if `stderr` is non-empty is consistent
with `git_command`'s behavior.
The previous behavior leads to a bug in conjunction with git v2.33 which
emits encoding warnings on stderr. Without this patch, we would throw
and fail although we actually lax decode git's output just fine. (This
behavior of git has been reverted in v2.34.)

Check `returncode` to decide if `git log` failed

---

core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py

Fixes #1473
E.g.
That is being on the commit that **has** fixups (or squashes) above highlight them.  
(We already did the reverse:
being on the fixup, highlight the commit we want to apply this fix on.)

Look upwards in the graph for potential fixup commits

---

core/commands/show_commit.py

As "COMMIT: " is taken by the make commit view, use "SHOW-COMMIT" to
distinguish them better.

Use distinct title for "Show Commit" views

---

core/commands/diff.py
core/commands/inline_diff.py
core/view.py

Diff views are usually created or switched-to from the status dashboard
or any possible source file.  They can be reused in which case we just
switch to them.
If we create a new diff view it always is created on the right of the
current view, so that upon closing the diff view the user lands again on
the original view.
We want the same when switching (or "re-using") existing views so we
move the diff view in the correct position so that closing it works as
expected.

Place diff views next to the current view

---

core/commands/diff.py

Fixup for 856abd25 (Let `gs_diff` key bindings act like a toggle)

Fix typo when getting view settings

---

GitSavvy.sublime-settings
common/util/debug.py

Delete unused functions from our debug module.  Remove the setting `dev_trace` which is only used within those (unused) functions.

Cleanup `debug.py` from unused functions

---

common/util/debug.py

We used `functools.lru_cache` here because we're lazy.  Ignore
whitespace changes properly.
Seen here: https://github.com/timbrel/GitSavvy/issues/1527#issuecomment-1077610112

Fix: Do not log same working dir in a row

---

core/commands/checkout.py

Colorize intra-line differences from `gs_checkout_current_file_at_commit`

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
Default.sublime-keymap
core/commands/diff.py
core/commands/inline_diff.py
core/interfaces/status.py

Ideally we would support discarding staged files or hunks but it gets complicated rather quickly:
a) a file can have staged and unstaged parts
b) a file can be actually untracked, only "i-t-a"
For now, flash status bar if discarding cannot be applied to inform the user.  This is better than doing nothing.

Flash status message when trying to discard staged files

---

core/commands/log.py

Within `LogMixin` we use members from `GitCommand`, this fixes mypy complaints.

Let `LogMixin` inherit from `GitCommand`

---

core/commands/show_file_at_commit.py

Note (again) that `rowcol` returns 0-based information but `open_file`
expects 1-based line/col values.

Fix off-by-one error when jumping from historical to working dir file

---

GitSavvy.sublime-settings
core/interfaces/tags.py

Fixes #1540
In the tags dashboard we were showing all but the last tag by default.
This bug was introduced by be511d8 ("set the default for
max_items_in_tags_dashboard to -1", Nov 2017) via #803.
Note that the intention of #803 was to show all tags but slicing `[:-1]` 
is incorrect and we change it to `[:None]`.  Note that `None` in Python 
translates to `null` in JSON.

Fix: show all tags by default

---

core/commands/log_graph.py

Fixes #1545
It is likely that processes we kill (intentionally) do not exit clean.
Suppress the error panel in that case.

Do not show error panel if a killed process throws

---

core/git_mixins/branches.py

When using `--branch` you must not construct `refs/head/<name>` as git
will do this for you.  In fact the *branch* 'refs/head/-+' is valid.

Fix `validate_branch_name`

---

syntax/show_commit_diffstat.sublime-syntax
syntax/test/syntax_test_show_commit_with_stat.txt

For example
```
docs/testing.md                 | 32 +++++++++++++++++++++++++++
tests/test_git/__init__.py      |  0
tests/test_git/common.py        | 49 +++++++++++++++++++++++++++++++++++++++++
```
Here: the `0` was not highlighted.
Also do count trailing spaces *between* the filename and the `|` separator as part of the filename.
E.g. before
After:

Recognize empty files in the diffstat

---

core/commands/line_history.py
core/commands/show_commit.py
core/commands/show_commit_info.py

For the views `show_commit`, `show_commit_info` (the panel), and the `Line History`, actually the views showing patches, make the filenames double-clickable.  A double-click will "jump-to" or open the corresponding file.

Make file references in some views clickable

---

core/commands/checkout.py
core/interfaces/branch.py

Fixes #1465
That's a totally minor life-hack so we can enter `fix 43` etc instead of `fix-43` for new branch names.

Convert spaces to dashes for new branch names

---

Default.sublime-commands
core/commands/branch.py
core/commands/push.py
core/interfaces/branch.py

Add command in the command palette `git: rename current branch` to rename the current branch.  This was only possible within our branch dashboard before.

Add global command to rename the current branch

---

Default.sublime-commands
core/commands/branch.py

Fixes #1035
Add command `git: unset tracking branch` to the command palette

Add command to unset tracking of a remote branch

---

core/commands/branch.py
core/commands/log_graph.py

As deleting the active branch is forbidden by git, offer to detach
first.
Typical usecase is that the user is on a feature branch which has been
merged upstream.  After `fetch`, the users sees the merge and can just
delete the feature branch without checking out a different branch
before.

Allow deletion of the active branch

---

core/commands/checkout.py
core/git_mixins/status.py
core/store.py

- Do not manage `last_branches` as a by product of `gs_checkout_branch`
but rather as a side-effect of `get_status`.  
- *Always* checkout on the ui thread.  This is debatable and can be changed later,
for now we want consistency here ("always").  Although we typically avoid blocking 
Sublime Text, checking out means changing the files we probably currently looking
at.   It is probably not desirable to allow editing at the same time; of course a ProgressBar 
would be nice

Iterate on `checkout.py`

---

syntax/make_commit.sublime-syntax
syntax/test/syntax_test_make_commit.txt
syntax/test/syntax_test_show_commit_with_stat.txt

GitHub usernames can have `-` which we did not consider.  Also fix that
they can appear on the first column.

Fix syntax highlighting github usernames

---

syntax/show_commit.sublime-syntax

- Do not include the trailing "\n" in the message subject
- Make the message subject a "Goto" reference (`ctrl+r`) (useful to navigate a longer `Line History`)

Iterate on the show commit syntax

---

core/commands/commit.py

SublimeLinter will otherwise not lint scratch views but for the commit view
we can imagine spelling etc. linters.

Mark commit message view as "lintable" by `SublimeLinter`

---

Default.sublime-keymap
core/commands/commit.py
core/commands/diff.py
core/commands/line_history.py
core/ui_mixins/quick_panel.py
popups/diff_view.html
popups/inline_diff_view.html
popups/line_history.html

Add fixup helpers -- bound to `[f]` -- to the `diff`, `inline-diff`, and the `Line History`.  
This is especially useful for the Line History as a user may fix a line, stage it and then search for the last commit that exact line has been modified recently.  Then looking at the Line History `[f]` will immediately open the pre-filled commit message view.
For the diff/inline-diff, opening a line history (or in that case: hunk history) would be very promising.

Add more fixup helpers

---

core/commands/log_graph.py

For slow graph outputs, for example when searching and filtering,
reading "2**14" locks for too long.  Just read line by line, just
like we do in `git_command.read_linewise`.

Draw log graph more async, more streaming 

---

github/commands/open_on_remote.py

When you want to open a file on GitHub, often enough the current version is not pushed.  In that case, open the last modified revision of that file.

Show the last-modified commit when showing a file on GitHub

---

core/commands/commit.py

We unconditionally added a newline (`"\n"`) after the commit subject which just looks not 100%.  Instead check if we actually have a message subject already and only then move that subject two(!) lines down so it becomes part of the message body.
We decided earlier that we *don't* replace old subject lines but only prepend.  Adding two newlines makes a perfect commit message ready to commit.

Makeup for fixup commit messages

---

common/util/debug.py
core/commands/branch.py
core/commands/checkout.py
core/commands/commit.py
core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py
core/exceptions.py
core/git_command.py

To allow copy-pasting the git commands, quote the arguments.
Note that `shlex.quote` is already a noop if the command doesn't need
to be quoted which simplifies the work we have to do a lot.

Quote git command when logging

---

core/commands/diff.py
core/commands/inline_diff.py
core/commands/show_file_at_commit.py
core/view.py

The old algorithm was not correct if Sublime Text word wrap was set.
Instead of computing the relative `row`, e.g. the cursor is on the 20th
visible row from the top of the viewport, stay in the pixel land and
compute the cursor is "231px" from the top border.  Then after
modifying the view, read the new cursor position (`cy`) in pixel via
`text_to_layout` and set the viewport so that we're still "231px" from
the top (`cy - row_offset`).
😊
Probably fixes #1349

Fix computing the new viewport position y value

---

core/commands/commit.py
core/commands/line_history.py

Since 2.34.0 we can initiate a fixup commit from the `Line History`.  We already close unneeded diff views after committing; and we follow here because that makes a nice workflow.

Automatically close a Line History view after committing

---

core/commands/diff.py
core/commands/merge.py
core/git_mixins/status.py
core/interfaces/status.py
core/parse_diff.py

Fixes #1353
Fixes #1579 
- allow restarting conflict resolution even after staging (`git checkout -m -- <path>`)
- warn when staging files with conflict markers 
- allow staging in the diff view (but all conflicts must be resolved)

Iterate on merge conflicts

---

Default.sublime-commands
Default.sublime-keymap
GitSavvy.sublime-settings
core/base_commands.py
core/commands/merge.py
core/runtime.py
core/utils.py

- Use canonical `git merge --abort` instead of `reset --merge`
- Rename to "merge --abort" (was: "abort merge").  We replicate the namespacy structure of the git command.
The user types "merge" and then the Command palette will ouput what commands we have for merge. We do the same for the rebase commands: "rebase --continue", "rebase --abort", ...
- Remove `merge_log` setting.  This specialized setting is not necessary because it is the same as setting:
```
"global_flags": {
"merge": ["--log"]
}
```
T.i. we have a generalized solution for custom flags already.

Iterate `merge.py`

---

core/commands/log_graph.py
core/commands/show_commit.py

- When moving out of the panel, e.g. via `[o]` or `[O]`, automatically close the panel.
- Remember that the panel had the focus, and give it the focus back when you switch back to the graph view.

Improve focus management of the commit info panel

---

core/commands/log_graph.py

When comparing the current branch, use the branch name instead of the bare commit hash as the base.
By doing so, the to be shown history becomes dynamic, e.g. you can rebase and add commits and the history view will reflect that.

Compare against the branch name not the commit

---

core/commands/diff.py

Here especially, the used `self.add` forcefully adds to the index t.i. it adds all the ignored files, just everything.
Solving #1490 would have prevented this bug here (probably).

Fix: Do not add all files if none is appropriate

---

core/interfaces/tags.py

There is no need for trailing spaces here and the last space gets interpreted as "comment" from our syntax.

Fix: Remove trailing spaces from local regular tags

---

core/commands/inline_diff.py

Support jumping from historical diffs (`gs_diff`), commit views (`gs_show_commit[_info]`), and the line history **to** the inline diff with correct cursor position and the viewport scrolled.

Improve jumping to the inline diff

---

Default.sublime-commands
core/commands/fetch.py
core/commands/log_graph.py
core/git_mixins/branches.py
core/git_mixins/remotes.py
core/interfaces/branch.py
tests/test_git_mixins.py

Fixes #1466
Very typical use-case is to just update the master/main branch from upstream **without** checking it out.  (You stay on the feature branch!)
Really the same as `git fetch origin master:master`.

Add "Update branch from upstream" action to the Repo History

---

gitlab/commands/merge_request.py
gitlab/gitlab.py

`gitlab: review merge request` is using the `List merge requests` GitLab API endpoint: https://docs.gitlab.com/ee/api/merge_requests.html
The default behavior for the `state` query parameter is to `return all merge requests`.
In order to be consistent with the documentation (`Display open merge requests on the base repo`) + how the `github: review pull requests` work, I added a `state=opened` query parameter to the API call to display only opened MRs.
I also slightly refactored the helper methods to correctly differentiate the params from the path and the params from the query.

GitLab: correctly fetch opened merge requests

---

Default.sublime-keymap
github/commands/open_issue.py
syntax/graph.sublime-syntax
syntax/make_commit.sublime-syntax
syntax/test/syntax_test_graph.txt
syntax/test/syntax_test_make_commit.txt
syntax/test/syntax_test_show_commit_with_stat.txt

In the "graph" we captured e.g. `Fixes #3` (as a whole) as issue reference.  Also `aziz/git#4` is recognized as an issue reference.
Add a meta scope `meta.git-savvy.issue-reference` to mark issue references.  Then check in the code if we actually support the ref because at the moment we only support refs to the same repo.

More robust extraction of issue references

---

core/commands/diff.py
core/parse_diff.py

Fixes #1490
Apparently `head_for_pt` was already implemented though unused.

Let `[SUD]` also work in the header of a (diff) patch

---

core/git_mixins/remotes.py
github/commands/commit.py

The code surprisingly used just the *first* defined remote for `GsGithubShowContributorsCommand` (=listing contributors; a helper command in the commit message view when typing `@<tab>`).
Fix that, and then as always, modernize and type check the associated file.

Correctly use integrated remote

---

core/interfaces/branch.py

As I changed the scopes in the syntax, the goto command has to follow here.

Fix: Move cursor to active branch initially

---

common/ui.py
common/util/view.py
core/commands/checkout.py
core/interfaces/branch.py
core/interfaces/status.py

Fixes #776
Fixes #1252
General, `nuke_cursors` is only used by the branch dashboard, and here 
to follow the active branch.  But being an imperative this was for example
not implemented for renaming the current branch.  Or the user just switch
branches in Terminus?  
The subproblem to follow the active branch is much easier to solve than
the general problem to follow any branch so we do the simple thing here
first and obsolete `nuke_cursors`.

Follow the active branch and remove `nuke_cursors` instruction

---

common/ui.py

This did not work previously in that the callback run before meaningful content was rendered, so I had this artificial "async" delay here (`enqueue_on_worker`).  But it does now and feels so much faster, well ... because it is instant now.
Note for testing: we use `on_new_dashboard` to move the cursor to a meaningful position for new views.
And it was the `nuke_cursors` thing that needed the delay. So this PR relies on the previous #1632

Run after first render callback immediately

---

core/commands/log_graph.py

I.e. it is not necessary to check if we're on the checked out branch, being on the "HEAD" commit is enough.
Otherwise we open the explicit diff "HEAD against the head commit" which is -- of course -- always empty.

Fix: Always show "Diff against workdir" if on HEAD commit

---

core/commands/log_graph.py
tests/test_describe_graph_line.py

A typical other ref name is for example `refs/bisect/bad` etc.  These should not count as local "branches".
Filter them here so they do not show up under "Delete <x>" or "Move <x> to ...".
In reality we even raised because other code assumed everything under `local_branches` would be also in `get_branches()`.  Fix that.

Fix: Ensure refs in "local_branches" are actual branches

---

core/interfaces/branch.py

Fixes #1643
With the setting `sort_by_recent_in_branch_dashboard` users can opt-into sorting the branches.  This sorting is (surprisingly) done on the git side (so we don't see it here) and thus resorting is not allowed.

Do not sort remote branches by name

---

core/commands/log_graph.py

When we have two cursors and hence two "infos", these are sorted and naturally the *base* commit should be the older commit of the two.

Flip base and target commit

---

tests/test_status_dashboard.py

At this point the view shows the data from the mocked "status" call, so there is literally no point in verifying the actual git call.

Remove redundant `verify`

---

core/base_commands.py

Symptom: the innocuous looking
```
class gs_reset(ResetMixin, LogMixin):
pass
```
did not work because it did not call `LogMixin.run()`.  Flipping there did not call `ResetMixin.do_action()` but the one from `LogMixin`.
The bases were defined as follows:
```
class ResetMixin(GsWindowCommand):
class LogMixin(GitCommand):
```
I can't calculate the MRO here so this is more intuition and hopefully luck
Introduced-by: 84c8c719 (Use `GsWindowCommand` in `reset.py`)

Symptom: the innocuous looking

---

core/base_commands.py

Symptom: the innocuous looking
```
class gs_reset(ResetMixin, LogMixin):
pass
```
did not work because it did not call `LogMixin.run()`.  Flipping there did not call `ResetMixin.do_action()` but the one from `LogMixin`.
The bases were defined as follows:
```
class ResetMixin(GsWindowCommand):
class LogMixin(GitCommand):
```
I can't calculate the MRO here so this is more intuition and hopefully luck.
Introduced-by: 84c8c719 (Use `GsWindowCommand` in `reset.py`)

Reorder inheritance of `GsTextCommand` and `GsWindowCommand`

---

core/commands/log_graph.py

Typically adding a filter slows down `git log` *and* triggers a complete redraw.  In that case draw the prelude immediately to give early feedback.

Redraw graph prelude immediately on 'drastic' changes

---

core/commands/log_graph.py

Since the introduction of `log_graph_view.paths` there is actually no `self.file_path` anymore (because we can have many).
Reintroduce the actions for when exactly one path is selected.

Enable actions around a file if exactly one file is selected

---

syntax/show_commit.sublime-syntax

The "real" patches for example from GitHub for a PR show a series of commits.  Each commits subject is within the header key-value-pairs.
E.g.

Teach the commit syntax full patches

---

core/commands/blame.py
syntax/blame.sublime-syntax
syntax/test/syntax_test_blame.txt

Fixes #1653
We already truncated the commit message subject but need to follow here for the author value as well.
Adjust the blame syntax to only match the email very loose.  As we may
truncate the field, basically just watch out for the ending: (`>|...`).

Fix too wide left column on blame views

---

core/git_mixins/history.py

If `follow` is on and the `current_commit` is the one where the rename
happens, skip 1 actually skips the rename and we will thus not get the
correct result.
Hence, always take 2 commits and skip the first here in python land.
This is in effect only in the blame view because `follow` is not used
anywhere else.

Fix `previous_commit`

---

common/theme_generator.py

Fixes #1502
Closes #1645
An "auto" color scheme is really just two schemes and then switching
between them.
Implement therefore a composite `ThemeGenerator` which acts on one or
many concrete theme generators.

Implement support for "auto" color schemes

---

Default.sublime-commands
core/commands/log_graph.py

With this `[g]` follows "HEAD" on the status dashboard.  For the global commands we remove the explicit `follow` directive though.
With that set we jump to "HEAD" for *new* views, but we do not move (or "hijack") the cursor if we merely jump to a different tab.

For new graph views follow "HEAD" if nothing else is specified

---

Default.sublime-commands
Default.sublime-keymap
core/commands/blame.py
core/commands/show_file_at_commit.py
core/git_command.py
core/git_mixins/history.py
popups/blame_view.html
syntax/blame.sublime-syntax

This is basically refactoring and fixing the blame view.  
-  Following file renames was disfunctional.  It is still not really working, we can only follow *one* rename.  After that `file_path` is out of sync with what we actually show, and calling `previous_commit` with `(original file name>, <new commit hash>)` cannot work anymore.
- Removed all (🤞) wait times (`set_timeout_async` with a `delay`) because why.  For example why fixing the viewport postition 100ms after drawing?
- Mark chunk from the current blamed commit visually; here with `(CURRENT COMMIT)`
- Support blaming the workdir (checked out, "live") revision of the file
- Actually start with that "live" version when using the command in the Command Palette.  Why asking for a commit here?  We wouldn't call blame if we actually …

Iterate on the blame view

---

common/util/file.py

Regression since 15ebebf2 (Use new `find_syntax_for_file` function in ST4).
For ST4 we never start a thread to read all syntaxes so the global `determine_syntax_thread` stays `None` all the time.  Adjust the conditional, in fact for ST4 we are always ready to determine a correct syntax.

Fix not determining a correct syntax at all

---

core/utils.py

The newer mypy 0.991 wants an `ignore[attr-defined]` on my local machine where "Default" has some local overrides.
On CI there are no overrides and mypy wants `ignore[import]` then.
Just use a wildcard ignore as this is for a compatibility layer anyway.
Fixes #1684

Change one type ignore line because mypy update

---

core/git_command.py

Yeah, of course `git_version` is per git binary and not per git repo.  🤷 again.

Hotfix `git_version` property

---

core/base_commands.py
core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py
core/utils.py
tests/test_graph_rebase_actions.py

The rebase now looks like this
For the quick actions (like re[W]ord, [D]rop) the flags are not switchable but GitSavvy will use whatever is needed- and supported because `update-refs` requires git to be >=2.38.0.
For the other commands we have the checkboxes but of course you don't have to deselect `rebase-merges` if there aren't any merge commits in the commit range you actually reapply here.  Or no refs to update. 
The update-refs feature is pretty awesome, you can put multiple feature branches on top of each other and apply fixes to older (not checked out) branches and it will put the other branch labels (refs) in place.  Or you can extract a branch from a series of commits.  
For example: for the just now sprint this PR is part of I worked basically on a `pu` (`dev`) branch:
T.i. I …

Learn usage of `--rebase-merges` and `--update-refs`

---

Default.sublime-keymap
core/commands/diff.py
core/commands/line_history.py
core/commands/navigate.py

Do not blindly focus the first line of the next/previous hunk.  Instead try to show the whole hunk the user is navigating to.  Try to scroll as minimal as possible.  
Special case the navigation in the Line History as here a commit header is always followed by exactly one hunk.  
So it is natural to try to show whole commits.  
Lastly when wrapping around the edges, ask for some force as it too confusing to jump from the last hunk to BOF.  Often it is not clear that you're on the last hunk even.  So when you're on the first or last commit you need to press multiple times before wrap-around jump actually happens.  A status bar text actually informs the user that the keypress has been registered and the user needs to repeat the key binding.

Tune navigating in views showing patches

---

core/commands/log_graph.py

Until now, we always searched for the commit dot on the line of the
cursor.  But often we ask: where does this line here begin or end?
Therefore, allow putting the cursor exactly *on* or into the graph art
and follow that graph from there.  E.g. place the cursor on the right
or left of a `|` symbol.

Colorize graph art directly at the cursor

---

core/commands/stage_hunk.py

For deletions only regions, Sublime draws a triangle in the gutter which naturally sits between two lines.  
Obviously a user cannot be exactly on such a region.
We needed to special case here but choose to only mark this region when the cursor was right above the triangle.  This is actually annoying so we now enable marking such regions from above or below.
It is unclear if the prior - a bit akward? - implementation was actually required by some means.

Stage deleted lines before or after the triangle marker

---

core/interfaces/status.py

Since #1622 rendering the template is pure so we can safely remove locking here.
It is still forbidden to call `update_state` in the render ("section") functions because it likely yields to a confusing output mixing old and new data portions.  But since we do not acquire the lock, the program will not dead-lock in that case anymore.
Aside: we keep the lock in `update_state` because we cannot guarantee it is called only from one thread sequentially.

Remove lock during `just_render`

---

core/commands/diff.py
syntax/diff_view.sublime-syntax

- Colorize the status information when we're in show-stage-mode.  
- Switch between stage/unstage modes when we for example stage the last remaining hunk.
This comes in very handy when you for example want to initiate a Line History of one the staged hunks.  Maybe to search for the commit you want to fixup.

Two commits for the diff view

---

Default.sublime-keymap
core/commands/stash.py
core/git_mixins/stash.py
core/interfaces/status.py
core/store.py

- Bind `[o]` to open/show a stash (deprecate `[t][s]` therefore. 
- Show the stash description in the title of the stash view.
Likely we can simplify more bindings at a later time.
- cache the stashes info which makes to make the initial render of the status dashboard snappy.  But we also read the description from the store.

nit stashes

---

GitSavvy.sublime-settings
core/git_command.py
core/interfaces/__init__.py

- Remove some unnecessary async'ness
- Deprecate the rebase dashboard.  (T.i. do not remove the functionality but exclude it from the 
default cycling.  Rebasing should be done from the Repo History/graph
- Do not close the graph view when cycling because it is too expensive to draw from scratch

Tune dashboard tabbing

---

core/commands/branch.py
core/commands/checkout.py
core/commands/log_graph.py
core/interfaces/branch.py

Fixes #1683
The create branch is similar to create tag, it labels the commit without 
checking out the branch which was not possible within GitSavvy before.
We actually had a "move" action which was a bit awkward.  Restrict the
latter to show up only when HEAD is detached and you basically pull
a branch to your position.
That was the only useful function of the feature anyway:  you checked
out the upstream and then wanted to move the local branch label to it.
Or you tested out a previous commit and then "reset" a branch to that
position.

Add "create branch" and "move branch" commands to the graph view

---

core/commands/navigate.py

Fixes #1712
When comparing `region.a < current_position` we must account for possible offset we apply automatically.
E.g. if the user is exactly on position `region.a + 4` in one of the dashboards (4 being the offset there), she is of course *on* the jump point and wants to go to the line above.
Just to be correct, do the `min` dance with `region.b`.

Fix upwards navigation in the dashboards

---

common/ui.py
core/commands/blame.py

Fixes #1717
`gs_blame_refresh` draws using `gs_new_content_and_regions` but not using the `regions` part.  That was not implemented since the optimizations in 6a04d2bb (Draw only the changed parts of a view).
Fix that but also change the caller (`gs_blame_refresh`) to use the raw `replace_view_content` function which is what all the other non-dashboard views do.

Fix `blame` not rendering anything

---

core/git_mixins/active_branch.py
core/git_mixins/branches.py
core/git_mixins/tags.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
core/store.py
core/ui_mixins/quick_panel.py
tests/test_git_mixins.py
tests/test_repo_status.py
tests/test_status_dashboard.py

Before:
-  T.i. generally remove the `origin/HEAD` ref (we do this in the graph view too!)
- if on par with the upstream, do not show it here again as it already state "On master tracking origin/master" right above
- If on a semver tag, do not follow up to the next semver.  (What's the nearest tag? The one you're on.)

Tune the new recent commits tagging

---

common/ui.py
core/commands/status_bar.py
core/exceptions.py
core/git_command.py
core/git_mixins/active_branch.py
core/git_mixins/branches.py
core/git_mixins/remotes.py
core/git_mixins/status.py
core/git_mixins/tags.py
core/interfaces/branch.py
core/interfaces/status.py
core/interfaces/tags.py
core/runtime.py
core/store.py
tests/test_fetch_branch_descriptions.py
tests/test_git_mixins.py
tests/test_graph_view.py
tests/test_inject_state.py
tests/test_repo_status.py
tests/test_status_dashboard.py

Since I deprecated the rebase dashboard, move the (easier) remaining ones, branches and tags, to match the status dashboard ("reactive") style.  
T.i. basically decouple state fetching/getting from drawing.  Then also cache most of the data needed to render the dashboards, especially the data we share between all of the them (everything in the header element).
The goal is that on `tab` we immediately draw the next dashboard and then eventually refresh that if the caches are outdated.
Mildly fancy we now inject state into the render functions.  I do this to avoid null objects all over the place, or `except KeyError` catchers.  Now the render functions just don't run if their dependencies are not present.

Snappy reactive dashboards

---

core/interfaces/tags.py
syntax/tags.sublime-syntax

- Fix: `[g]` to annotated tags did not work
- Fix: multiple tags on the same sha on a remote were not visible under some circumstances
- Feat: Add special markers for new (unpushed) tags and changed tag (which are on a different sha than on the remote)
- Further tune the fetch/render order

Iter tags dashboard

---

common/ui.py
tests/test_ui.py

After the hotfix 3266859a (Fix `blame` not rendering anything) we do a
fresh render whenever `regions` becomes empty which is not necessary
(and a bit confusing).  Rewrite that passage for clarity:
We need a full render whenever we have sections not currently drawn;
and also when we haven't drawn any sections at all in the previous
round.  The latter implies `not regions`.
In other words: Instead of `not regions` *or* `not current_region_names`
*and* would have been correct.
Add tests because I did this wrong 3 times now.

Clarify when we need a full render

---

core/commands/inline_diff.py
core/commands/navigate.py

For the first jumpable region, we try to show the BOF which is only correct for views that have a header section at the top.
Inline diffs don't and so we shouldn't do anything particular as well. Note that the historical file view (which is similar in that it shows a whole file without headers) never did this as well.

Fix navigation to the first section in the inline diff

---

git_savvy.py

For the new to come Package Control v4, we need to import the `events` module deeply.
Fixes #1576

Deep import `package_control.events`

---

common/util/view.py

Conditionally undo the workaround just introduced ffd39a81 (Always open new views on the right side of the current view) as the bug got fixed.

Undo placement bug workaround

---

core/commands/show_file_at_commit.py

Probably ideally we would not flash the status bar but have a static label there.  This also includes a hack to make the duration Sublime shows such a message longer.  
That's naive but we have the message parsing in here, and maybe it is good enough or we will catch up on the next iteration.

Less obscure title and better status message when navigating commits

---

github/commands/pull_request.py

The `ok_cancel_dialog` is confusing because "cancel" does not stop
the whole process but essentially means "no, do not set the upstream".
Use `yes_no_cancel_dialog` as it seems the legit use-case here.  
But do not ask if the remote is already configured (because the user did multiple PRs already).  
Use our checkout command for the actual checkout.  This has the better messaging and error handling;
but it also is error-prone because commands can fall off and continue async.  Let's just assume we
can handle and remember the complexity at a later point.  (Generally, the commands do not compose, 
so we can't us `gs_fetch` and then something else; it only is allowed here because it is the *last* command
we run.)

Use yes_no_cancel_dialog to ask for upstream

---

github/commands/pull_request.py

This is especially useful when we also add a remote for tracking
as a probably subsequent "remote remove" will highlight the last
used remote by default.

Remember used remote fetching a pull request

---

core/git_mixins/remotes.py

We always presented the configured remotes ordered by name. 
Switch to order of definition.

List remotes by order of appearance in the config

---

GitSavvy.sublime-settings
core/commands/tag.py

Fixes #1737
This is pluggable via the `only_ask_to_annotate_versions` setting.

Only ask for a tag message if the tag looks like a version

---

core/commands/log_graph.py

Since d19c3f81 we follow "HEAD" if nothing else can be specified when opening a new graph.  In case "HEAD" is not within the graph we want to show (which is only typical for file histories or other searches), the cursor remained in BOF position.
Do a `gs_log_graph_navigate` after the initial, first draw in that case.

Fix initial cursor position of "File History" views

---

core/commands/diff.py
syntax/output_panel.sublime-syntax
syntax/test/syntax_test_output_panel.txt
tests/test_diff_view.py

Implements precise cursor movement after staging/unstaging etc. in the diff. (Surprisingly, we did not had any code here but relied more or less on luck.)

Move cursor to the next hunk after staging (et.al.)

---

unittesting.json

Failing tests are often super-slow because we often wait for a view change, that will never happen so we actually await the timeout.
Set "failfast" for the better initial experience.

Switch unit tests runner to "fail-fast"

---

core/commands/log_graph_rebase_actions.py

For our automatic interactive rebase commands, e.g. "Reword this commit", we rewrite the todo list.  We expect long commands, e.g. "pick", in the todo list but a user *could* change that in their configuration.  Explicitly set `rebase.abbreviateCommands` to make our code more robust.
We could use `-c rebase.abbreviateCommands` but this would show up in the logging which is a bit ugly.  We also had to code this in as yet another argument for `self.git`.
Instead use environment keys to achieve the same thing.  These environment settings are read since v2.31.0 but naturally do not fail on older versions.

Ensure user did not set `rebase.abbreviateCommands`

---

core/commands/blame.py
core/commands/diff.py
core/commands/inline_diff.py
core/commands/show_file_at_commit.py
core/view.py

Fixes #1040
We do this for inline diff for ages now:  when opening (or switching to) a diff view from the source file, try to jump to /or show) the position we're currently at.  
E.g. total seamless:
https://github.com/timbrel/GitSavvy/assets/8558/de9c07ab-087f-4dd5-a589-e0d58868f774
Without this patch the diff would land on the first hunk of the edited file.

Scroll to nearest hunk when switching from file to diff

---

Default.sublime-keymap
core/commands/_help_popups.py
core/commands/log_graph.py
syntax/graph.sublime-syntax

- Show `HEAD*` (the added asterisk) when the repo is dirty
- Mark some special branch names with the (random) scope `constant.other.git.branch.special.git-savvy`.  
The special branches are `(master|main|dev|trunk)\b`
- Add a new "mode" which shows an overview over the branches and maybe tags.  Via `[s]`.  In that mode `[a]` toggle the tags on and off.
In general looks like this:
Note that I underline `master` here but each user has to do this by editing their color scheme.

Fine-tune and polish the graph view

---

core/commands/diff.py

Improving b8c45b55 (Scroll to nearest hunk when switching from file to diff), do not scroll if the diff fits on one screen.

Do not scroll to position for small diffs

---

github/commands/open_issue.py

Until now we only supported simple issue references, e.g. `#<nr>`. Our syntax (and Github in general) also supports cross-linking, e.g. the format `owner/repo#<nr>`.  Implement the issue link generation for such cross-links as well.

Implement issue url generation for neighbor projects

---

core/commands/show_commit.py

Like that:
This makes the feature more prominent and allows navigation by mouse.

Add next/previous commit (`[n/p]`) annotations to the commit view

---

README.md

Unfortunately Package Control does not resolve the images for us and thus does not display any of them on their site.
To resolve the image urls I pasted them in an empty issue textarea on Github, then clicked on the image and copied the url from the address bar.

Resolve image links for Package Control

---

core/commands/commit_compare.py

To reduce flicker (unwanted paints) run especially `show_branch_panel` on the main thread.
Ideally we could fetch the available branches while waiting for user input.  However, just doing it synchronously is still preferable as it prevents the wizard's first menu from closing just to show up again a split second later with a new panel (with the branch names to choose from).
To defer in the second case (`show_single_line_input_panel`) was a mistake in the first place as it only opens up an input box (which is immediate and runs on the UI thread anyway.)

Run the "Compare against..." wizard on the main thread

---

core/git_mixins/history.py

`--topo-order` is what we should show in the graph views and should give in general more "natural" results.  (In the history views we usually use `--simplify-by-decoration` but I don't think that is relevant here and maybe it is just more costly performance-wise. But actually idk and we will see.)

Use `--topo-order` to find the next or previous commit

---

core/commands/show_commit.py

We have bound `[g]` to the tag `setting.git_savvy.show_commit_view` which is true for both stand-alone views and the detail panel below the graph or a log entry quick panel.  We then just call `gs_graph` to do the actual work.
Typically `gs_graph` focuses the graph view but not here because it has been taught to not steal the focus from its own details panel. (This is rather complicated state, refer `PANEL_JUST_LOST_FOCUS` and the `had_focus` setting.)
The fix is to check if the view the command is bound to actually `belongs_to_a_graph`, and if so to just focus the main graph view.

Fix `[g]` not switching from the commit panel to the graph

---

core/commands/line_history.py

When the user selects deleted lines (`is_from_line`) taking the lineno from the "to" side (`b`) is off by 1 as the b numbers don't increment on these lines.  Adjust that by adding 1.

Fix line range computation from a diff for deleted lines

---

core/commands/diff.py
core/commands/line_history.py
core/parse_diff.py

The function actually returns the "b"-part.  The used regex `HEADER_TO_FILE_RE` already indicates that.

Fix the incorrect name `from_filename` -> `to_filename`

---

core/commands/log_graph.py

Fixes #1775
We had a mismatch between the git command we executed and the prelude we show.
The prelude suggested that `[a]` is a toggle, i.e. it did *hide* the set `branches` when `all_branches` was also set.  But the actual git command did not follow.
I think the prelude is right here so we fix the git command.

Let `[a]` act like a toggle when branches are set

---

core/commands/log_graph.py

In 98eed7b (Bind `[s]` to switch to an "branches overview" mode) we
introduced reading some settings twice.  Fix that and then just write 
the function more concise.

Rework prelude generation

---

core/commands/commit_compare.py
core/commands/log.py
core/commands/log_graph.py

Fixes #1778
If the cursor is *not* on the HEAD, just offer to compare the
commit under cursor with HEAD.  (T.i. we don't show the wizard anymore.)
If the cursor *is* on the HEAD commit, show the wizard to let the user
choose a target.  Make sure the wizard does not offer "HEAD" as a target
as that would mean compare "HEAD vs HEAD" which is nonsense.  Add
some typical targets, "main" or "master" and e.g. the nearest tag, to choose 
from quickly.

Improve "Compare with..." command

---

GitSavvy.sublime-settings
common/interwebs.py
github/commands/create_fork.py
github/github.py

Closes #1772
Setting `default_branch_only` is like a sparse fork.  See:
https://github.blog/changelog/2022-07-27-you-can-now-fork-a-repo-and-copy-only-the-default-branch/
We make the default "sparse" and introduce an argument to the command
so users can add a "create full fork" to the Command Palette or where
they wish to at their own.
Additionally, a new setting `sparse_fork` is added whose value is used
as a default when `default_branch_only` is `None`.

Set `default_branch_only` when forking a GitHub repo

---

common/util/log.py
core/commands/init.py
core/fns.py
core/git_command.py
syntax/output_panel.sublime-syntax
syntax/test/syntax_test_output_panel.txt

E.g.
Of course these numbers above move, that's the point of a progress bar/info.
Note that this changes how we measure timeouts as we now "ping" on each byte we receive, thus we only timeout stalled
processes.  (This is what we want probably as before that we actually could have timed out if we fetch big enough repos.  E.g. just clone "git" and it is likely the command would have timed out unless you live in a rich region of the world.)
The interpretation for the timeout has only changed for our implementation though, t.i. when we log to the open panel, as we otherwise just use `proc.communicate` which has its own semantics.  
The progress is only turned on for "clone" and "rebase".  A future PR will enable this for other commands.  Typically "push", "pull", "fetch".

Support progress information in the output panel

---

core/commands/checkout.py

Unlike with remote branches, local branches that were the target of the [b] shortcut, were failing to pass the branch name as the initial text of the prompt for the new branch.
For context, this is a problem for me as I use this flow:
1. when I have a big change planned
2. I create a copy of the local branch by hitting [b]
3. I usually add a suffix in the end of the branch to indicate it's a copy
Tested on a local copy

fix(branch): pass name as initial prompt text

---

core/commands/checkout.py

This reverts commit fdabd46e4dc93ecfbb2f9c9377d12069532d6a8f.
The change introduced in #1797 throws for the command "checkout new branch":
```
Traceback (most recent call last):
File "C:\Users\c-flo\AppData\Roaming\Sublime Text\Packages\GitSavvy\core\base_commands.py", line 75, in run_
self.defaults[name](self, args, done)
File "C:\Users\c-flo\AppData\Roaming\Sublime Text\Packages\GitSavvy\core\commands\branch.py", line 71, in handler
initial_text_ or call_with_wanted_args(initial_text, args),
File "C:\Users\c-flo\AppData\Roaming\Sublime Text\Packages\GitSavvy\core\commands\branch.py", line 48, in call_with_wanted_args
return fn(**{k: args[k] for k in fs.parameters.keys() if k in args})
TypeError: <lambda>() missing 1 required positional argument: 'start_point'
```
Revert as a hotfix.

Revert "fix(branch): pass name as initial prompt text"

---

core/commands/next_hunk.py

Avoid the `else` clause as we're not using a variable coming from the `try` clause.

Small code readability nit

---

core/commands/log_graph.py

If the user was or selected something in the prelude, the cursor would possibly jump from there to the `follow`ed symbol.  Prevent that.

Do not alter selection if in log graph's prelude

---

core/interfaces/tags.py

Esp. deleting remote tags was just not possible.  Deleting local tags worked but still raised as `self.delete_remote` did run unconditionally. 
Unfortunately mypy did not catch fire here as this is a simple left-over from moving to the reactive base class.

Fix deleting tags in the tags dashboard

---

core/commands/checkout.py

Unlike with remote branches, local branches that were the target of the `[b]` shortcut, were failing to pass the branch name as the initial text of the prompt for the new branch.
This commit was already in #1797 which got reverted in #1800 because it threw.  Since then we taught `base_commands.WithInputHandlers` to include arguments with their default values if the command was not called with them, essentially fixing the underlying issue.
Still, Pavel's patch needed an `or = ""` because the default `start_point` is `None` which is not an allowed initial text for an input handler.  Added that.

Pass starting point as initial prompt text when creating new branches

---

core/commands/log_graph.py

The commit message under the cursor can be truncated.  We need to remove the ellipsis signs as we do a prefix search later.

Fix finding fixups or squashes upwards

---

core/commands/diff.py

In a new diff view staging something and then switching the staging area (`[tab]`) should result in showing the top of the view, the prelude, with the cursor on the first hunk.
This did not work and was maybe never implemented correctly.  (It may just have worked by chance, though.)

Fix first switch to the staged area

---

common/util/view.py

Ref: sublimehq/sublime_text#5596
Ref: sublimehq/sublime_text#1358
Directly after creation, t.i. after the views *first* activation,
result regexes (e.g. `result_file_regex`) are not in effect.  The
work-around is to call `focus_view` *after* assigning the regexes.
For now, call this unconditionally to get better insights into this
side-effect.

Ensure new views can act as a result buffer after creation

---

core/commands/log_graph.py

To require empty selections seems like a mistake here, especially since we don't require them in the "cherry-pick" or "revert" commits section.

Do not require empty selections for graph's main menu

---

core/commands/log_graph.py

Add exposing the "dot"-position.  This is required for a later add-on to support "PowerCursors".

Expose where the dot is when parsing a commit line

---

core/commands/log_graph.py
core/git_mixins/status.py

Fixes #1768
Git does not decorate refs from the logs (e.g. "branch@{2}") for us.
Let's implement this esp. to make finding the old tip after rebasing
easier.

Manually decorate refs from the reflog

---

core/commands/log_graph_rebase_actions.py

Add "Compare with" and "Diff against" previous tip commands

---

core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py

In the rebase menu we already offer "Apply fix to <commit>" when the
cursor is on a fixup or squash commit.  Do this also when the cursor is
on the "base" commit searching upwards for fixups.

Add action to apply available fixes to a given commit

---

Default.sublime-keymap
core/commands/_help_popups.py
core/commands/show_commit.py

We have `[E]` and `[W]` implemented in the graph view to quickly
initiate a rebase.  Do this also for the "show commit" and "line
history" views.  Especially "show commit" has since then learned `[n]`
and `[p]` to walk the commit history.  To e.g. reword a commit message
seems a natural fit when reviewing the commits then.

Implement [E] and [W] rebase shortcuts when viewing patches

---

core/commands/show_commit.py
core/commands/show_commit_info.py

When we show patches in the commit info panel, we generally remember the viewport-/scrolling-position and the selection per each commit.
Add this also to the show commit view, which is more or less just the maximized version of the panel and which offers navigation using `[n]` and `[p]`.

When navigating the commit history remember and restore the view state

---

core/commands/show_commit.py
core/parse_diff.py

Fixes #1572
Commit messages are indented by 4 spaces when looking at patches, e.g. the output of "Show Commit" or "Line History", which makes a copy/paste operation (if you want to copy multiple lines) cumbersome.
Fix this by adding a copy helper which strips the leading 4 spaces.  A user can issue the "copy" command twice to get the standard behavior.

Add copy helper for commit messages

---

core/commands/log_graph.py

Fixes #1796
The "plain" fetch and pull commands are confusing to use when no upstream is set.  Both ask for a remote or a remote branch in case of pull.  This might be useful but inconsistent to when the upstream is set.  Hence, omit these menu items.

Omit fetch and pull when no upstream is set

---

core/commands/log_graph.py

Status updates (`gs_update_status`) run lazy ("when idle") and
`gs_log_graph_refresh` calls run often `on_activated` so the state
in the store we use to determine if the repo is dirty can be outdated
easily.
To solve this issue subscribe to state updates and re-render if the
rendered state does not match the repo state by calling out to
`gs_log_graph_refresh` again.
This is costly and can be a waste *if* the refresh just started and is
still running.  We thus keep track of the time window between starting
the refresh process and actually receiving and annotating the HEAD
commit because in that window we don't need to restart the refresh.

Ensure dirty decoration is in sync with the repo state

---

core/commands/diff.py

We introduced scrolling the viewport when switching from a file to its diff.  We omitted this already for diffs that fit on one page.
Omit this generally if the cursor fits on the *first* page of the diff view.  T.i. essentially: try to always show the prelude.

Do not scroll to the cursor if it is on the first "page"

---

core/commands/diff.py
core/commands/inline_diff.py
core/commands/navigate.py

Log current position after navigating in typical `n/m` form.  Turn off "wrap_with_force"  for the diff view as that seems unnecessary
to improve orientation then.

Flash navigation position in the diff views

---

core/commands/commit.py
core/commands/diff.py
core/fns.py
core/ui_mixins/quick_panel.py

As user you don't want to fixup fixup commits but the original ones. Therefore do not preselect possible fixup/squash commits at the start of the shown list but the first typical commit.

Let the fixup log helper not pre-select fixup commits

---

core/commands/diff.py
core/commands/navigate.py

Fixes #1435
If a hunk has multiple chunks, add them to the navigation.  Select the complete chunk to make it easy to act upon that exact part of the diff.  (E.g. `[s]` will then stage that chunk.)

Navigate chunkwise in the diff view

---

Default.sublime-keymap
core/commands/_help_popups.py
core/commands/inline_diff.py

Typically diffs show two sides, a and b, in red and green.  For the inline diff add shortcuts to hide and show one of the sides.  This comes in handy for complicated diffs to quickly switch between the previous and the next state.
https://github.com/timbrel/GitSavvy/assets/8558/a13c7254-8e8d-44a2-b632-6182014771c0

Add `[a]/[b]` to toggle sides in the inline diff

---

core/commands/branch.py
core/commands/checkout.py

If a branch name already exists directly ask if it should be recreated

Offer to forcefully recreate a branch

---

core/commands/pull.py
core/git_mixins/remotes.py
core/store.py

In case of `pull` it should be possible to trigger a `--no-rebase` by
passing in `rebase=False`.  Also reading the default from `git config`
seems superfluous as omitting the argument will let git find out the
default for us.
Fix that by making `rebase` a three-state toggle, hence differentiating
between a `False` and `None` value.
While at it modernize the file.

Make pull's rebase parameter a true `yes_no_switch`

---

core/interfaces/branch.py
syntax/branch.sublime-syntax
syntax/test/syntax_test_branch.txt

- Mark the sha's as `constant.other...` just like in the other dashboards.
- Mark the active branch indicator as `punctuation...`.
- Mark the whole line of the active branch using a `meta...active-branch` scope.
- Do not use `string.other...` at all.  Esp. do not mark the active branch's name as such.  User can target that name with e.g.
``` meta.git-savvy.branches.branch.active-branch meta.git-savvy.branches.branch.name ```

Normalize branch dashboard syntax

---

core/base_commands.py
core/commands/log_graph_rebase_actions.py
core/store.py

A user might not want to update the local branches all the time. Offer remote branches to rebase from to support that mode.

When rebase asks for a branch also include remotes

---

core/interfaces/tags.py

The error messages can span multiple lines and we need to `indent` all of them to make them look proper.

Fix error message formatting in tags dashboard

---

core/interfaces/branch.py

The code only considered that there is always an active branch.  This is obviously not true.
Jump to the next (or first on the initial draw) branch when HEAD is detached.

Fix cursor placement on branches dashboard if HEAD is detached

---

core/commands/branch.py

The error messages changed with 2.43.0 so we need to follow up here.

Fix detecting when a user wants to delete an unmerged or the current branch

---

core/commands/log_graph.py

Standard rebasing is just too common to place it in the rebase menu only.  Place it in the standard menu, where we also fetch, push, and pull.

Add "Rebase on" to the standard graph menu

---

core/commands/log_graph_rebase_actions.py

The idea here is that the first section "Drop, Edit, Reword" act on the specific commit under cursor.  But the second section generally makes "bulk" rebases with a series of commits.

Move "autosquash" item to the second section

---

core/base_commands.py
core/commands/merge.py
core/git_mixins/branches.py
core/ui_mixins/quick_panel.py
tests/test_git_mixins.py
tests/test_repo_status.py

To make the list of branches shorter and sane filter fully merged branches.  T.i. only present branches that would have an effect when merging them.

Let `gs_merge` list only unmerged branches

---

core/commands/log_graph_smart_copy.py

Teach the smart copy helper to copy special branches and tags
The selector for the branches ("constant.other.git.branch.git-savvy")
was too restrictive and did not catch special branch names like "main",
"dev", and so on.  This is a regression from b01ccb0b (Mark some special
branches in the graph view), released with 2.41.0 (Jun 2023).
Add the selector for tag names. It is not clear why that was missing,
so this looks like a bug as well.

Do not reset cursor if assume_complete_redraw

---

core/commands/log_graph.py
core/runtime.py

We cleared `assume_complete_redraw` directly in the `run` handler
before.
- This leads to a relative long time between clearing and drawing again
("git log" hasn't even started!).
- It was done unconditionally when `assume_complete_redraw` was set,
even when the repo was small enough to compute the next graph under
100ms.  But when the graph drawing is fast, clearing early basically
just introduces a flicker which we should avoid as it is a visual
regression.
Do this differently then.  We still always clear the graph when
`assume_complete_redraw` is set.  But we do this immediately before
drawing (t.i. in `draw`) *or* when the first token is not available
within 100ms.
That means for fast repos, we clear and draw in the same tick, and
Sublime Text will not produce any flicker.

Clear graph content lazy when we assume_complete_redraw

---

core/commands/line_history.py

When the user did not select anything in a diff, we construct a virtual
selection by ourself.  Typically it looks slightly better if we only
select the changed lines, t.i. we do not include the leading and
trailing context lines as the history gets too broad quickly.
In case of "addition only hunks" this is counterproductive though as by
definition the added lines don't have any history in the repo.
Therefore select the whole hunk with the context lines in that case.

For addition only hunks assume the hunk is selected

---

core/commands/log_graph.py

The "File History" offers to diff different versions (commits) of files. However, we did not pass the `file_path` down to the diff, so it always showed the complete diff between the revisions.  Fix that!

Fix: diff file from graph menu did not select a file

---

core/commands/log_graph.py

We have two options here, (1) to *not* use graph views which are in overview or (2) to switch them out of overview mode.
I choose the latter as the overview mode is from the intent an intermediate state.

Set `overview: False` when reusing a graph

---

core/commands/init.py

We set this directly after creating the window.  But with a window Sublime also creates a first view and this in turn triggers e.g. `on_activated` et.al. ... and so on ... at the end SublimeLinter may kick in and tell you that `target_dir` does not exists and can't be used as a working dir...
Just do it later to avoid these cascades.

Set `project_data` after cloning has finished

---

core/commands/log_graph_rebase_actions.py
tests/test_graph_rebase_actions.py

👀 
This probably makes the Rebase menu within the graph view feature complete to deprecate the rebase dashboard.

Add extracting, copying, and squashing commits to the rebase menu

---

core/commands/log_graph.py

That's a brutal dev error:  I used `return <expr>` wrong as the `expr` is not evaluated (like a last value).  Instead `yield from` and then a bare `return` must be used here.

Fix: Render graph if `follow` is `None`

---

core/commands/branch.py

The error message does not end with `.` anymore.

Fix detecting when a user wants to delete an unmerged branch

---

core/commands/diff.py
core/parse_diff.py
tests/test_diff_view.py

* Make `gs_diff_open_file_at_hunk` safe when used in the commit/patch views
* Use the first hunk if the cursor is not in a hunk but e.g. in the header section
* Implement line matching when `in_cached_mode`

Tune gs_diff_open_file_at_hunk

---

core/commands/custom.py
core/runtime.py

The special `__daemon` argument of `run_on_new_thread` broke its type, or mypy's understanding of it.
Fix that by providing two functions.  This simplifies the type and actually also looks nicer as the special, hidden keyword argument.

Factor `run_new_daemon_thread`

---

syntax/make_commit.sublime-syntax
syntax/test/syntax_test_make_commit.txt

There is no good solution.  For now *restrict* what we consider to be a commit hash.
Our starting point was the simple `\b<hash>\b`. Maybe I lean towards less colors when in doubt instead of more colors; here we highlighted a part of an url which I disliked.

Fine tune syntax recognition of commit hashes in commit messages

---

core/commands/log_graph.py
core/commands/log_graph_colorizer.py
syntax/graph.sublime-syntax
tests/fixtures/log_graph_1.txt

In the graph root nodes can be very hard to see (if you have multiple
of them) when they appear on the same indentation as the surrounding
"normal" commit nodes.
Let's give them a different char, `"⌂"` for now.  The exact style
does maybe not even matter.

Render root nodes differently

---

common/ui.py
core/commands/commit.py
core/commands/inline_diff.py
core/commands/intra_line_colorizer.py
core/commands/log_graph.py
core/commands/show_commit.py
core/utils.py

Whenever we mark something in a read-only view we can be sure that a practical "undo" is not in reach for the user.
When writing the commit message on the other hand we re-compute the regions in "on_selection_modified", making the undo-stack unnecessary.

Set `NO_UNDO` for basically all regions as an optimization

---

GitSavvy.sublime-settings
core/git_mixins/branches.py
core/interfaces/branch.py
core/store.py
core/utils.py
syntax/branch.sublime-syntax
syntax/test/syntax_test_branch.txt
tests/test_git_mixins.py
tests/test_repo_status.py

Similar of how the overview mode of the graph view sorts the branches,
group the branches in the branches dashboard.
First show the branches that are ahead of HEAD, then the checked out
branch, then the branches that are behind, finally branches that have
diverged (are ahead and behind). Split this last section further and
put stale branches in a separate section.
This leads to a nice representation.
* E.g. the user is on main and sees all feature branches that could be
merged right above.
* E.g. the user is on a feature branch and sees the dependent feature
branches up to main directly below the active branch.
The feature requires git v2.41.0 and is pluggable by the
`group_by_distance_to_head_in_branch_dashboard` setting.
Closes #788

Iterate the branches dashboard

---

common/ui.py
core/interfaces/branch.py
core/interfaces/status.py
core/interfaces/tags.py

This fixes a bug as we did not initialize the `state` object for the
status view at all.  T.i. all status dashboards *shared* the same view.
Duh, this did not hurt but produced flicker when flipping between
projects.
All other dashboards initialized their state in `__init__`.  (It should
have been done in `on_create` rather.)  Move that to a template method
`initial_state()`.

Clearly initialize state for new dashboard views

---

core/interfaces/tags.py

The code opted out to denote anything when no remote had any tags, which
is at least true for the pristine remote repo.  E.g. we checked:
```
if remote_tag_names and ...:
if remote_tags and ...:
```
Remove these (late) checks and instead rely on `self.state.remote_tags`
to be "truthy" which it is as soon as we check any remote for its tags.
This "as soon" is important for the possible initial render where we
don't have any remote tags because we didn't even *start* to fetch any.
Consider that even `self.state.remotes` might not be resolved when the
caches are clean.

Ensure to denote new sem-versions if there are no remote tags

---

core/interfaces/status.py

Ensure discard side-effects are not called with empty lists

---

common/ui.py

Since the state has grown and contains formatted, relative dates, the
state effectively often changes every minute.  Make a second check
against the actual view content as we don't want the cursor to flicker
or jump around.

More aggressively check if a view needs a re-rendering

---

Context.sublime-menu
GitSavvy.sublime-settings
core/commands/__init__.py
core/commands/context_menu.py

Users can opt-out by setting `disable_context_menus: false` in their GitSavvy settings.

Add basic context menu to all views

---

core/commands/inline_diff.py
core/commands/show_commit.py
core/commands/show_file_at_commit.py
core/git_mixins/history.py

Given a random commit we always looked from "HEAD" up to that commit to find (or rather guess) the next commit.  This fails if the user is looking at a commit not contained in the current line.
Tune this and check first for a branch that contains the commit.  If there are many, take the one that has the most recent changes.  Then graph the line from the commit to the tip of the branch.
Since guessing a next commit is not cacheable, this new approach would require two git calls per user action.  To avoid that take the whole log line and store it on the view so that subsequent `[n]ext`-actions are free.  T.i. cache for the lifetime of the view.

Tune guessing the next commit

---

core/git_mixins/branches.py

Fixes #1939
That's an obvious bug due to a obviously wrong interpretation of a
variable.
`supports_ahead_behind` actually means `compute_ahead_and_behind` and
that computation should be done if `slow_repo` is in `(False, None)`
state.

Fix interpreting slow_repo state

---

core/interfaces/branch.py
syntax/branch.sublime-syntax
syntax/test/syntax_test_branch.txt

Fixes #1941
In fact our syntax did not expect timezone information and broke here.
Remove the timezone as it looks better and the information seems not
necessary in this overview format we have in the branches dashboard.

Suppress timezone information in the branches dashboard

---

.gitattributes

This PR adds various development related resources to .gitattributes in order to exclude them from GitSavvy.sublime-package installed via Package Control.
Notably `__init__.py` in root directory is excluded to avoid exceptions, when reloading package after upgrade without impact on current development or test workflows. The file is considered a dev-only resource.

Exclude development files from sublime-package

---

Default.sublime-commands
github/commands/__init__.py
github/commands/create_repo.py
github/github.py

Note that this initial version only supports public, user repos.  That is the minimum valuable enhancement.

Add "github: create repo"

---

core/commands/log_graph.py

Just searching for "...\n" isn't safe to find *our* continuation marker as git itself uses that if the drawn graph has holes.  E.g. if we pick-axe or limit the graph to certain files not all commits are shown. In other words: our continuation marker is not unique.
Just extract the last few characters of the graph view to check for the marker which should be at EOF position all the time.

Fix graph refreshing on every line change under some circumstances

---

core/commands/diff.py

The previous implementation commit message f0e9bf31 (Implement `gs_diff_open_file_at_hunk` when `in_cached_mode`) correctly states that the staged hunks get applied to HEAD and so are its line numbers in relation to "HEAD".  But that doesn't tangle the problem which is that we might still have a dirty diff between the working dir and HEAD and we in fact want to jump to the workingt dir state.
So we basically need to adjust by comparing to the standard diff, e.g. `git diff -- some_file`.
That would be `find_matching_lineno(None, None)` but the function doesn't accept that and switches the first `None` to an `-R`.  T.i it asks for a *reversed* diff.  Hence we use `reverse_find_matching_lineno` which can interpret this correctly.

Fix `gs_diff_open_file_at_hunk` when `in_cached_mode`

---

core/commands/inline_diff.py

Since the underlying data of an inline diff view is hold in memory (under `diff_view_hunks`), it is lost when Sublime Text gets restarted. (Or GitSavvy gets reloaded for that matter.)  Force a refresh to load up that data again.

Refresh inline diff after reloads

---

Default.sublime-commands
github/commands/pull_request.py
github/github.py

Fixes #1937
Add `query` argument to `gs_github_pull_request` (default: "") to filter
the list of PR's we fetch.  As the search API does return a subset of
the information we need, query the full PR response in a second step
(but in the background using a future).
The query parameter is a string and can be basically anything a user
would also type in on Github's website.
Interesting candidates are e.g. "involves:@me" which is also added to
the Command Palette.

Implement `query` parameter when searching for PR's

---

core/commands/blame.py
core/commands/diff.py
core/commands/inline_diff.py
core/commands/show_commit.py
core/commands/show_commit_info.py
core/commands/show_file_at_commit.py
core/fns.py
core/git_mixins/history.py
tests/test_graph_view.py

Internally we switch to short_hashes.  This can be a temporary switch as we gain more information of the places where we actually uses hashes or allow also revs (e.g. branch names).  After all, if we mark all places we *could* implement an internal map from short to long hashes (e.g. whenever we draw the graph), and switch to long hashes without a big cost.  Note: we switch to short hashes here but it actually was wild, no-rules before, so we basically normalize our usages and get a sense of it.
Other than that:  there is obviously no simple solution to which is the best newer or older commit of a given commit (as there might be many), so it is likely there are some decision made I don't remember right now.

Iterate on next/previous commits navigation

---

core/commands/show_commit.py
core/parse_diff.py

(This respects Sublime's `"copy_with_empty_selection"` setting.)

Let "smart copy" select the current line if the selection is empty

---

core/commands/line_history.py
core/commands/log_graph.py

For long running histories, (a) abort if the user closed the view and (b) abort if the view gets too long

Limit log history views

---

Default.sublime-keymap
common/ui.py
syntax/dashboard.sublime-syntax

Allow the cursor to be on the commit, from the sha to the end of that line.

Tune commit selection (`[o]`) in the dashboard headers

---

syntax/graph.sublime-syntax

As it is more and more common to work off the remote branches directly, mark them similar to how we marked the local branches "main" and "master".
This is opt-in as the user has to tweak their color scheme to support that.
The branch are tagged `constant.other.git.branch.special.remote.git-savvy`, the local special branches are tagged `constant.other.git.branch.special.git-savvy` (unchanged).

Mark special remote branches in the graph

---

Default.sublime-keymap
core/interfaces/status.py

We use `[S]` everywhere else for this functionality. `[a]` is still available but not advertised in the help.

Bind `[S]` for "stage all" in the status dashboard

---

Default.sublime-keymap
core/commands/__init__.py
core/commands/help_panel.py
core/commands/show_commit_info.py
syntax/help.sublime-settings
syntax/help.sublime-syntax

I never liked the tooltips because they disappear immediately and I usually forget the shortcut when they do.  So I have to open them again, ... and so forth.  
Just make them a help panel at the bottom.  This could be expanded to a context based help too in the future.

Switch help tooltips to a help panel

---

Default.sublime-keymap
core/commands/help_panel.py
core/commands/log_graph.py
core/commands/show_commit_info.py
tests/test_graph_view.py

Generally we show commits/patches in the panel at the bottom or in a separate view.  (Basically, `m` and `o` when in the graph view.
Let's make that fluid:  In the graph, `m` to toggle the panel (as before), but `M` to open the panel and put the cursor in it.  While in the panel `M` to maximize that to a full view and back.  `m` to close the panel again.

Fancy `[M]` and `[m]` in the graph and commit view

---

core/commands/diff.py
core/git_mixins/status.py
core/interfaces/status.py

Just having "UNTRACKED" in the header is lame, temporarily run
`intent_to_add` on that file, and read the diff again. That is mildly easy.
Staging (and undoing that) actually is more code.  Ensure that the status 
view does not intent-to-add untracked files too (which was esp. annoying.)

Teach diff view to handle untracked files

---

core/git_command.py

"dired" views are directory views from the "FileBrowser" or (original) "dired" package.
Use the shown path to find a suitable git path.  This, for example, allows directly switching to a dahboard view.

Support dired views

---

GitSavvy.sublime-settings
core/commands/remote.py

When adding remotes, we always asked if we should now also fetch this remote.  Add "fetch_new_remotes" and just fetch without asking if set to `True`.
This is also the default because frankly you likely want that.  (Except for huge repos, but then set this in the project settings, no?)

Add setting `fetch_new_remotes: true`

---

Default.sublime-commands
Default.sublime-keymap
core/commands/log_graph.py
core/git_mixins/branches.py
core/interfaces/branch.py
core/interfaces/status.py

Esp. 
* bind `[G]` to go to the overview mode from the status page
* when graphing a branch, usually set all: false now, and compute and include the upstream

Iterate on graph constructors

---

core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py

Probably because of fear, we still had special handling for the "author" constraint, e.g. `filter_by_author`.
(a) But when set, the prelude didn't show it.
(b) The edit filter feature explicitly has the author filtering in its help.
Just remove that and use `filters`.  This way,we have it in the prelude, can edit it with `f` and toggle it with `F`.  Users can still access it from outside as "filters" is exposed in the `gs_graph` constructor.
Win-win?  No compatibility mode included, users must adjust their custom commands.

Remove special "author" handling

---

core/commands/help_panel.py
core/commands/log_graph.py

Since the fixups, squash commits are highlighted enable a way to jump between them.

Include fixup commits in wide jumps

---

Default.sublime-keymap
GitSavvy.sublime-settings
common/ui.py
core/commands/__init__.py
core/commands/commit.py
core/commands/diff.py
core/commands/help_panel.py
core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py
core/commands/multi_selector.py
core/interfaces/branch.py
core/interfaces/status.py
core/interfaces/tags.py

That is huge.  Bind `<space>` to select an item, e.g. a commit in the graph, or a line or hunk in the diff.  Do this multiple times to form a multi selection just with the keyboard, and then do the action as always.  
Implemented for the diff, the graph, and the dashboards.

Add multi selection feature

---

core/git_mixins/tags.py

`distutils` is removed from Python 3.13 so we can't use it here forever.
Replace it with a very dumb "parser" function.
Fixes #2001

Replace distutils..LooseVersion with an even dumber one

---

core/commands/diff.py

This is a fix for `[o]`in the diff view, when the diff shows something like "a...b" (3 dots!).

Compute `effective_target_commit` for diffs over commit ranges
