timbrel/GitSavvy

core/git_mixins/active_branch.py

Fix forward slash ignoring on branch names

---

GitSavvy.sublime-settings
core/commands/commit.py

Still needs a update to the syntax, but it's a start.
Resolves #38.
Note; I'm new to Python.

Add an option to show a diff in the commit

---

core/commands/commit.py

This change properly implements #44 for commits.

Don't commit quietly when outputting to a panel

---

Default.sublime-commands
Default.sublime-keymap
GitSavvy.sublime-settings
common/commands/view_manipulation.py
common/util/view.py
core/commands/__init__.py
core/commands/tags.py
core/git_command.py
core/git_mixins/tags.py
syntax/tags.YAML-tmLanguage
syntax/tags.tmLanguage

As discussed in #10, this is the branch/PR I will implement the tags view feature.
Features:
Todo:

Feature: Tags view

---

Default.sublime-commands
core/commands/checkout.py
docs/README.md
docs/branch_mgmt.md

Adds a command to  checkout the current active file to HEAD without having to go to the status view (from #92 ).
For any change, let me know!
Thanks!
**Edit:** Closes #92.

Add the command `git: checkout current file`. #92

---

core/commands/quick_stage.py

- better status display "x files staged"
- add "git: commit" to allow quick staging to become quick commiting

feature: improve quick stage

---

core/commands/tags.py
core/git_command.py
core/interfaces/branch.py
core/interfaces/status.py

- avoids really long absolutely paths in dashboards
- prefer to show ~ rather than the full path to a users home dir

feature: shorter path display

---

GitSavvy.sublime-settings
core/commands/inline_diff.py

fix(inline_diff): support ignoring EOL whitespace in inline diff (default: True)

---

core/git_mixins/active_branch.py

Attempting to checkout a local tracking branch when the remote branch is gone/deleted causes the following exception in `core.get_mixins.ActiveBranchMixin`:
```
File "/Users/ddevlin/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/interfaces/branch.py", line 73, in render_branch_status
return self.get_branch_status(delim="\n           ")
File "/Users/ddevlin/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_mixins/active_branch.py", line 69, in get_branch_status
self._get_branch_status_components()
File "/Users/ddevlin/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_mixins/active_branch.py", line 48, in _get_branch_status_components
return False, False, addl_lines[0], None, clean, None, None
IndexError: list index out of range
``` …

fix: ActiveBranchMixin doesn't match status when remote branch is gone

---

Default.sublime-commands
Default.sublime-keymap
GitSavvy.sublime-settings
core/commands/log_graph.py
docs/history.md
syntax/graph.YAML-tmLanguage
syntax/graph.tmLanguage
syntax/show_commit.YAML-tmLanguage
syntax/show_commit.tmLanguage

Adding some small functionality to Git graph
I am sure you have something that I should change. I am happy to change it unless you want me to remove all.

Better git graph

---

core/commands/commit.py
core/commands/diff.py
core/commands/inline_diff.py
core/commands/log_graph.py
core/commands/show_commit.py
core/git_mixins/active_branch.py
core/git_mixins/branches.py
core/interfaces/branch.py
core/interfaces/status.py

it look like this
in .gitconfig
```
[color]
ui = auto
diff = always
status = always
branch = always
interactive = always
```

Fix: color output problems if user have set there config to always

---

common/util/debug.py
core/commands/inline_diff.py

Now it work nice with:
- staging\unstage line alone
- staging\unstage line in middle of hunk
- undo staging\unstage for all action on single line
- undo for revert hunk
This have been hard. But now it should be solved :)

Edit inline diff

---

core/interfaces/rebase.py

Some repositories don't use a `master` branch (e.g. GitHub Pages repos use `gh-pages` instead). If a `base_ref` hasn't been actively selected and `rebase_default_base_ref` hasn't been set in the project settings the `base_ref` will default to `master`, and if `master` doesn't exist `merge-base` will throw an exception, causing the dashboard not to display.
This commit checks that the default `base_ref` (either `master` or `rebase_default_base_ref`) is a valid branch, and if it's not falls back to the first inactive local branch, the first local branch, or `HEAD`.
Closes #217 
**After**:

Enhancement: Rebase dashboard handles case where master doesn't exist

---

docs/README.md

Documentation: add more documentation for custom commands

---

core/interfaces/rebase.py

Fix: display all types of unmerged conflicts

---

Default.sublime-keymap
core/commands/diff.py
docs/staging.md

Feature: Toggle option(ignore_all_space, word_diff) for diff view

---

GitSavvy.sublime-settings
core/commands/inline_diff.py
docs/staging.md

Fix: Type inline_diff_auto_scoll to inline_diff_auto_scroll

---

core/commands/flow.py
docs/flow.md

* support git-flow 0.4.1 and above (added note in docs)
fix #272

Fix: always pass the branch name on git flow * finish

---

Default.sublime-commands
core/commands/__init__.py
core/commands/cherry_pick.py
core/commands/log.py
docs/README.md
docs/misc.md

Changes in Docs:
* add cherry-pick to history section
* add unmentioned `reset` commands to history section
* a typo fix
refs #11

Feature: add a simple stand-alone cherry-pick command

---

github/commands/pull_request.py

Enhancement: show user logins, and friendly times in pull request list.

Pull request tweaks

---

core/commands/reset.py

Enhancement: Show a hint next to each "git reset" option explaining what it does.

Reset hints

---

Default.sublime-commands
core/git_mixins/remotes.py
github/commands/pull_request.py

The first attempt to provide "Create Pull Request" feature in #318. There are still a lot to do, for example,
1. check upstream is set and updated
1. allow pr to different branches and remotes.
PS: This PR was launched by  using `github: create pull request` 😊

feature: simple support of create pull request

---

core/interfaces/tags.py

`show_input_panel` doesn't like `None`.
PS: sorry for not testing the new code well..

Fix: the default should be a string

---

Default.sublime-commands

#326 
add `git: push all tags` command in palette.

Feature: add "git: push all tags" command

---

core/commands/__init__.py
core/commands/log.py
core/commands/show_file_at_commit.py
docs/history.md

Fixes issue #328 
moved array in self.window.show_quick_panel() and stored in options_array  so that additional options may be added conditionally

Feature: Git log current file > Show file at commit

---

core/git_mixins/merge.py

* check helper methods return value and abort merge on fails
* store temp. backup of merge target file and revert to it on merge fail
* if mergetool.<tool>.trustExitCode is true simply resolve
* otherwise, resolve only if file changed from original
(git would normally prompt if unchanged as well, we simply revert)

Feature: resolve conflict (stage merged file) on successful merge

---

Default.sublime-commands
core/commands/__init__.py
core/commands/remote.py

Finish up and closes #347 
Now we have `git: remote add` and `git: remote remove`
There exist rename, but it will have to wait.

Manage remote

---

syntax/blame.sublime-syntax
syntax/graph.sublime-syntax

Improve graph and blame syntaxes

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
Default.sublime-keymap
GitSavvy.sublime-settings
common/commands/view_manipulation.py
common/ui.py
common/util/view.py
core/commands/commit.py
core/commands/log_graph.py

Be vintageous friendly

---

Default.sublime-keymap
core/interfaces/branch.py

I made a royal screw-up when I was rebasing and decided it was easiear to redo my changes in a clean branch.
This PR started here: https://github.com/divmain/GitSavvy/pull/397

Navigate branches using hotkeys

---

core/commands/blame.py
core/commands/log.py
core/git_command.py

Enhancement: Remember which option got selected last in quick panel

---

syntax/make_commit.sublime-syntax

Fix diff highlight in commit message (issue #405)

---

docs/flow.md

To help users get over issues such as #321.

Documentation: Add note on `git-flow` path discoverability

---

core/commands/show_file_at_commit.py

I was able to fix #412 with this.

Fix for #412

---

Default.sublime-keymap
common/global_events.py
core/commands/__init__.py
core/commands/rebase_interactive.py
docs/README.md
docs/rebase.md
syntax/make_commit.sublime-syntax
syntax/rebase_interactive.sublime-syntax

Improve rebase interactively `git rebase -i master`
Improve commit `git commit`
Improve ammending commit `git rebase -i master` -> edit commit
closes #402

Enhancement: Improve experience when you use EDITOR=`subl -nw`

---

syntax/branch.sublime-syntax
syntax/dashboard.sublime-syntax
syntax/rebase.sublime-syntax
syntax/status.sublime-syntax
syntax/tags.sublime-syntax
syntax/test/syntax_test_branch.txt
syntax/test/syntax_test_dashboard.txt
syntax/test/syntax_test_status.txt
syntax/test/syntax_test_tags.txt

- Added more granular scopes to be able to make better custom color schemes
- No change for non customized color shcemes
- Added test for status syntax
- More scopes for branch syntax
- No change for non customized color shcemes
- Extractted shared syntax to dashboard.sublime-syntax
- Added test for dashboard syntax
- More detailed scopes 
- No change for non customized color shcemes
- Uses the base dashboards syntax
- Added test
- Uses the base dashboards syntax

Improved syntax denfinition for dashboard syntaxes

---

core/commands/log_graph.py
core/commands/show_commit.py
core/interfaces/rebase.py
syntax/blame.sublime-syntax
syntax/dashboard.sublime-syntax
syntax/diff.sublime-syntax
syntax/graph.sublime-syntax
syntax/make_commit.sublime-syntax
syntax/rebase.sublime-syntax
syntax/rebase_interactive.sublime-syntax
syntax/show_commit.sublime-syntax
syntax/status.sublime-syntax
syntax/test/syntax_test_blame.txt
syntax/test/syntax_test_dashboard.txt
syntax/test/syntax_test_diff.txt
syntax/test/syntax_test_graph.txt
syntax/test/syntax_test_make_commit.txt
syntax/test/syntax_test_rebase.txt
syntax/test/syntax_test_rebase_interactive.txt
syntax/test/syntax_test_show_commit.txt
syntax/test/syntax_test_status.txt

- Improved rebase dashboard syntax + test
- Changed rebase graph unicode characters to make it look better
- The syntax still support old unicode characters 
- more detailed scopes 
- added test
- replaced `*` in graph with `●`
- improved diff syntax and added test 
- Fixed a bug where diff can not detect new file where the header is like `--- /dev/null`
- improved show_commit syntax and added test
- show commit buffer should be read-only
- make commit should use the GitSavvy diff syntax not the built-in diff syntax 
- improved make commit syntax and added test
- improved blamed syntax and test
- Improved interactive rebase syntax and added test
Here is how it looks. you can try it by using [my custom color scheme](https://github.com/aziz/sublimeText3-Userfiles/blob/master/Color%20Schemes/ …

Syntax improvements for various syntaxes

---

core/git_mixins/branches.py
core/interfaces/branch.py

Fix #420
This make it work for multiple selections.
This can be added for multiple lines selections as well, when this will be done
I think we should edit `common/util/view.py@get_lines_from_regions`.

Enhancement: Multi-merging in branch view

---

Default.sublime-keymap
GitSavvy.sublime-settings
common/ui.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
core/interfaces/tags.py
syntax/dashboard.sublime-syntax
syntax/test/syntax_test_dashboard.txt

- toggle help menu using `?` shortcut
- added `hide_help_menu` settings to diable help
- help menu can always be shown again using the shortcut

Feature: Toggle help menu, on demand or through settings

---

Default.sublime-keymap
common/ui.py
core/commands/branch_commit_history.py
core/commands/log_graph.py
popups/log_graph_view.html
popups/style.css

fixed #316 
The shortcut key to view the help popup is `?`
The look and feel could be customized using the color scheme's  `popupCSS` setting

Popup shortcuts for graph view

---

GitSavvy.sublime-settings
common/util/debug.py
common/util/reload.py

As a use case, add tracing to the `reload` module to get the output advertised in #408.

dev_mode: Add debug trace facility controlled through "dev_trace" setting

---

core/git_mixins/active_branch.py
core/git_mixins/remotes.py

It does nothing but just moves the code.

Enhancement: move active branch related code to active_branch.py

---

Default.sublime-keymap
core/interfaces/tags.py

Feature: add smart tag keybind to Tags dashboard

Feature: add smart tag keybind to Tags dashboard

---

core/interfaces/rebase.py

look like 2c89d4d9c4edb1467535fcce52a7b1d3c6d1d448 forgot to update it

Fix: complete_action needs branch_name and ref

---

github/git_mixins/remotes.py

as title and added various fall backs when the integrated remote cannot be determined

Enhancement: return the only remote when there is only one

---

Default.sublime-commands
core/commands/log.py
core/commands/reset.py

Feature: reset to branch and log by branch  …
added two commands
1. `git: reset to branch`
2. `git: log by branch`

Feature: reset to branch and log by branch

---

core/commands/reset.py

Enhancement: show the list of commits again when reset mode selection is canceled.

Enhancement: show the list of commits again when reset mode selection is canceled.

---

syntax/status.sublime-syntax

Fix: allow stage/unstage files when cursor is at EOL

---

core/commands/log_graph.py

This also fixes the navigation issue of commit comparison in log_graph and #481 .

Fix: match hash explictly in log_graph

---

common/util/file.py

Another attempt of #472 
- If the threading is still running, return "Plain text". (Locking mechanism is hard to implement- when get_syntax_for_file is executed in the main thread, and we acquire a lock for get_syntax_for_file, it may block the main thread?)
- Do not run `determine_syntax_files` again when reloading the GitSavvy.

Enhancement: use thread.Thread to execute determine_syntax_files

---

core/interfaces/rebase.py

Fix: argument count for get_branch_state

---

core/git_mixins/status.py

Add: typechange to status dashboard

---

core/commands/commit_compare.py
core/commands/log_graph.py
core/commands/show_commit.py
core/commands/show_file_at_commit.py
core/git_command.py

I always encounter random errors when the working repo is a symlink. Always resolving symlink should fix the issue.

Fix: Always resolve symlink in self.file_path and self.repo_path

---

Default.sublime-keymap
core/commands/commit_compare.py
core/commands/diff.py
core/commands/log_graph.py
core/commands/navigate.py
core/commands/show_commit.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
core/interfaces/tags.py
popups/compare_commit_view.html
popups/diff_view.html
popups/show_commit_view.html

Now, the cursor will be initialized correctly for all tabs.

Fix: fix navigation offset and cursor location when view starts

---

core/interfaces/rebase.py

Feature: allow navigation through conflicting files in rebase view

---

docs/README.md
docs/github.md
docs/history.md
docs/misc.md
docs/tag_mgmt.md

Enhancement: update various docs

---

Default.sublime-commands
core/commands/__init__.py
core/commands/fixup.py
core/commands/quick_stage.py
core/git_mixins/rewrite.py
docs/commit.md

Allow fixup commit and autosquash the fixup commit. If autosquash fails, it will leave the fixup commit.
close #220 
close #503

Feature: Fixup commit and autosquash

---

common/util/view.py

It is particular handful when checkout other branches.

Enhancement: refresh_gitsavvy also refreshes sidebar

---

core/interfaces/branch.py

GsCompareCommit have been changed to WindowCommand

Fix: diff history against active branch in Branch dashboard

---

docs/README.md

Other: fix link in github docs

---

core/commands/log.py
core/commands/log_graph.py
core/git_mixins/history.py

Fix: bring back log and log graph --all

---

core/git_mixins/history.py

I am splitting my PR in #534 into smaller PRs.
This PR adds some of the helper functions for merges.

Others: add history helper functions

---

core/git_mixins/active_branch.py

Enhacement: show "no branch, rebasing" in status when rebasing

---

core/commands/changelog.py
core/git_mixins/history.py

This should be useful to identify related commits.

Show merge hash in changelog

---

core/git_mixins/branches.py
core/interfaces/branch.py

Fix: Send list to merge

---

common/quick_panel.py
core/commands/reset.py

`show_paginated_panel` is now more flexible to handle items.
In many cases, `on_done(index)` is useless for paginated panel. It will be more useful to do `on_done(item)`. It is particularly important when `items` is a generator, as there is no way to pre-store the items,  the function `format_item` can be specified to format generated items on the fly.

Enhancement: make show_paginated_panel more flexible

---

core/interfaces/branch.py

Move method from GsBranchesMergeSelectedCommand to Branch interface

---

core/interfaces/branch.py

Fix: allow checking out a remote branch when no local branches exist

---

core/commands/commit_compare.py

Fix: handle vintageous and arrow keys in commit compare view

---

common/util/view.py
core/commands/checkout.py
core/commands/log.py
core/commands/merge.py
core/interfaces/branch.py
core/interfaces/rebase.py

Problem: The sidebar is refreshed too frequently. It is even refreshed for operations which do not change any files.
Solution: Refreshing the sidebar is now on demand only. Let me know if I have missed any places which need `refresh_sidebar`.

Other: the sidebar is refreshed too frequently

---

core/interfaces/branch.py

A number of functions in `core/interfaces/branch.py` share the same common code to reveal the selected branch. This PR refactors them so that they all use the common function `get_selected_branch`.

Other: refactor GsBranches commands to use interface.get_selected_branches()

---

core/commands/checkout.py

Fix: util.view.refresh_gitsavvy argument typo

---

Default.sublime-keymap
core/commands/log.py
core/commands/reset.py
core/commands/show_file_at_commit.py
core/interfaces/branch.py

Includes a shortcut in the branches dashboard.
I find this valuable as it saves me 1-2 addl. keypresses.

Feature: add command to show log of selected branch

---

Default.sublime-keymap
core/commands/log_graph.py
core/interfaces/branch.py

It is essentially a mirror of #580 for log graph.

Feature: Show log graph in Branch interface

---

Default.sublime-keymap
GitSavvy.sublime-settings
core/commands/fixup.py
core/git_mixins/rewrite.py
core/interfaces/rebase.py
docs/rebase.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/divmain/gitsavvy/534)

Feature: upgrade rebase dashboard

---

Default.sublime-commands
Main.sublime-menu
docs/github.md

This will open default and user settings side by side

Improve: Use the newer API for opening settings

---

core/commands/inline_diff.py
core/git_command.py

First try to read with utf-8 then latin-1

---

docs/commit.md

Add: Docs for `Signing your commits with GPG`

---

.coveragerc
.travis.yml
CONTRIBUTE.md
appveyor.yml
docs/testing.md
tests/test_git/common.py
tests/test_git/test_git_init.py
unittesting.json

[![Build Status](https://travis-ci.org/randy3k/GitSavvy.svg?branch=tests)](https://travis-ci.org/randy3k/GitSavvy) [![Build status](https://ci.appveyor.com/api/projects/status/3t20nyp5y7ulj52e?svg=true)](https://ci.appveyor.com/project/randy3k/gitsavvy) [![Coverage Status](https://coveralls.io/repos/github/randy3k/GitSavvy/badge.svg?branch=tests)](https://coveralls.io/github/randy3k/GitSavvy?branch=tests)
close #195

Other: implement tests

---

common/util/file.py
core/commands/inline_diff.py
core/git_command.py

So the diff renders correctly now. While there is still a problem when we want to apply the diff. I think I know how to solve it. I just want to know If this works.

Render inline diff with correct encoding

---

core/commands/checkout.py
core/git_mixins/active_branch.py
core/git_mixins/branches.py

fix #587 
@divmain, I am proud to announce that you can not start using emoji in you branch names :)

Emoji: Support emoji in branch name

---

core/commands/custom.py
docs/custom.md

Enhancement: Add setting to custom command to open in new buffer

---

core/interfaces/tags.py

Fix: Push tags command is not blocking

---

common/theme_generator.py

Improve: Warn the user when we have permission error

---

core/commands/show_commit.py
core/commands/show_file_at_commit.py
core/git_mixins/history.py
core/interfaces/rebase.py
core/interfaces/tags.py

A quick fix to #641, the function `get_short_hash` can be better written but it works for now.
close #641

Fix: added self.get_short_hash to honor core.abbrev settings

---

common/theme_generator.py
common/util/file.py
core/commands/commit.py
core/git_mixins/ignore.py
core/git_mixins/merge.py
core/git_mixins/rewrite.py

followup to #636
I will use this branch to test that this work as expected. Would be cool it you could too :)
Some places I wrote some code which tries to open with utf-8 and if it fails try latin-1, and we don't want to have a `ok window` open.

Warn the user if GS encounter a disk error

---

messages.json
messages/2.14.2.txt

Release notes for 2.14.2

---

appveyor.yml

fix the appveyor failure at #650

Fix: need to config username and email in appveyor

---

common/util/debug.py
core/git_command.py

Useful to debug to see if there is a long running command

Improve: In log, add seconds

---

CONTRIBUTING.md

... and test `maintainerd` integration.
-----
_(required)_

Add auto-deploy info to the CONTRIBUTING docs.

---

core/commands/cherry_pick.py

branch is passed through kwargs

---

GitSavvy.sublime-settings
core/commands/commit.py
syntax/make_commit.sublime-syntax

close #488
also address #671  which has been closed
-----
_(required)_

Feature: more informative commit view

---

Default.sublime-commands
core/commands/__init__.py
core/commands/reflog.py
core/git_mixins/history.py
docs/history.md

All the codes are there, just have to glue them together
-----
_(required)_

Feature: git: reflog

---

core/commands/push.py
core/git_mixins/branches.py
core/interfaces/branch.py

If remote tracking branch found, push to the remote tracking instead of a banch with the same name as the local branch. The code utilizes the the command `gs_push`.
close #570
-----
_(required)_

Enhancement: push selected branch to the tracking branch

---

Default.sublime-keymap
core/commands/pull.py
core/git_mixins/remotes.py
core/interfaces/branch.py

-  [u] key to pull selected branch from remote at Branch dashboard
-----
_(required)_

Feature: pull from remote at Branch dashboard

---

Default.sublime-commands
Default.sublime-keymap
core/interfaces/tags.py

We are using similar naming rule for Branches
-----
_(required)_

Other: just make sure the commands are named after the dashboard name

---

core/git_mixins/remotes.py

Didn't test it thoroughly.
-----
_(required)_

Fix: pull direction fix

---

Default.sublime-keymap
core/commands/commit_compare.py
core/commands/log.py
popups/compare_commit_view.html

This allow users to compare commits against HEAD while using `git: log` or `git: graph`.
-----
_(required)_

compare commits related enhancements

---

core/commands/diff.py
core/commands/show_commit.py

Fix: missing gs_handle_vintageous in diff_view and show_commit_view

---

.travis.yml

it seems that the container had some problems and failed the previous PRs.
https://docs.travis-ci.com/user/reference/precise/#Virtualization-environments
-----
_(required)_

do not use container based travis build

---

.travis.yml
core/commands/status_bar.py

Enhancement: use async methods in GsStatusBarEventListener

---

Default.sublime-keymap
core/git_mixins/remotes.py
core/interfaces/branch.py

This PR serves for two purposes.
1. fix the not working `fetch and merge into active branch` command (the method `run` was missing)
2. `fetch and merge into active branch` now also works for local branches.
3. remove the confusing feature in my earlier PR #699  `pull selected from remote`. In fact, this feature is identical to `fetch and merge into active branch` for local branches since `pull` basically is `fetch + merge`.
-----
_(required)_

Fix: Fetch and Merge at Branch dashboard was not working

---

core/interfaces/rebase.py

Right now, the rebase dashboard checks 　if the whole list contains merges when dropping a commit. This PR modifies the logic so it checks only up to the base commit of the action (for example, only checks if the commits after the dropping commit are merges).
-----
_(required)_

Enhancement: only check up to action specfic base_commit

---

Default.sublime-commands
core/commands/pull.py
core/git_mixins/remotes.py
docs/remotes.md

close #729 by adding a new command `git: pull with rebase`.
-----
_(required)_

Feature: add git pull with rebase command

---

Default.sublime-keymap
popups/diff_view.html

Enhancement: add h/H key in diff view

---

core/commands/status_bar.py

It should fix #726 finally.
To test its effect, open "Go to Anything" by <kbd>c-p</kbd> and hold the down arrow.
-----
_(required)_

Enhancement: do not update status bar for transient view

---

Default.sublime-keymap
core/commands/inline_diff.py

Other: Inline diff navigation uses GsNavigate

---

common/util/debug.py

Internal: Fix typo secounds => seconds

---

Default.sublime-commands
common/util/view.py
core/commands/__init__.py
core/commands/log.py
core/commands/log_graph.py
core/commands/revert.py

Added to
- Command pallet
- Git log -> Commit action
- Git graph -> Commit action
closes #732
-----
_(required)_

Enhancement: git revert

---

GitSavvy.sublime-project
common/ui.py
common/util/debug.py
common/util/reload.py
core/commands/checkout.py
core/commands/init.py
core/commands/inline_diff.py
core/commands/log_graph.py
core/commands/reset.py
core/git_command.py
core/git_mixins/active_branch.py
core/git_mixins/branches.py

Internal: follow pep8 rules (almost max-length: 120)

---

docs/branch_mgmt.md
docs/history.md
syntax/test/syntax_test_graph.txt
syntax/test/syntax_test_status.txt

Mionor fixes after release 2.15.0

---

.travis.yml
appveyor.yml

Internal: add syntax tests

---

docs/history.md

Docs: better formatting for blame doc

---

core/commands/push.py

Fix: "push to existing branch" was not working

---

GitSavvy.sublime-project

Add a convenient command for testing GitSavvy.
-----
_(required)_

Internal: add UnitTesting build system

---

Default.sublime-keymap

I didn't try if `control` is valid or not. At least for consistency.
-----
_(required)_

Fix: control -> ctrl

---

Default.sublime-commands
common/interwebs.py
docs/github.md
github/commands/__init__.py
github/commands/create_fork.py
github/github.py

Feature: GitHub create fork command

---

core/commands/checkout.py

Select the branch name of the input panel  while creating a new branch, thus any keystroke would replace the original branch name.
-----
_(required)_

Enhancement: select the branch name while creating a new branch

---

Default.sublime-commands
Default.sublime-keymap
core/commands/__init__.py
core/commands/stash.py
core/git_mixins/stash.py
core/interfaces/status.py
core/ui_mixins/quick_panel.py
docs/README.md
docs/stash.md

Feature: git stash in command panel

---

common/util/debug.py

This bug was intoroduces in
Other: refactor log_git and add log_ ...
6fbefaf97720

Fix: Decode stdin to debug log

---

core/interfaces/rebase.py

Fix: default selected_index should be 0

---

Default.sublime-commands
Default.sublime-keymap
core/commands/blame.py
core/commands/diff.py
core/commands/show_commit.py
core/commands/show_file_at_commit.py
core/git_mixins/history.py
docs/history.md
popups/blame_view.html

It replaces my earlier PR #717 by removing the syntax highlight code because of performance issue.
1. line forwarding (the cursor will follow via history instead of going to a random place)
2. use [f], [c] and [a] to switch between `detect within file`, `detect within commit` and `detect within all commits` instead of showing a panel to ask every time. The popup view is also modified to show less text.
3.  the options of the BlameActionCommand are renamed.
-----
_(required)_

Enhancement: refactor blame command

---

tests/test_json.py

See comments in commit https://github.com/divmain/GitSavvy/commit/4bc4bf32636df4a5f620193bbffe34686ec76bf9
-----
_(required)_

Internal: Fix test_json.py from @facelessuser

---

core/interfaces/rebase.py

- allow defining a previous commit as a base ref
- change some wording to avoid confusion between `define base ref for dashboard` and `rebase branch on top of...`
- add a `Rebase to default base` option.

Enhancement: select commit as base in rebase dashboard

---

common/util/file.py
core/git_mixins/rewrite.py
core/interfaces/rebase.py

issue #799
Hmm, this is not a good, though it removes the annoying message. 
This will now raise `RuntimeError: generator didn't yield` in the console.
I think we just need to add some file.exits here and there.

WIP: "OS error" message not going away

---

core/commands/changelog.py

Should result in something like:
```
changelog:
-  [IMP] add BREAKING syntax
BREAKING: Line1 ...
Line 2 ...
Line 3 ...
```

changelog: [IMP] add BREAKING syntax

---

core/commands/commit.py

Commit view will respect include_unstaged

---

Default.sublime-commands
core/commands/__init__.py
core/commands/amend.py
core/commands/quick_stage.py
docs/commit.md

close #822 
- added a new command `git: quick stage current file and amend`.
- add amend option in `quick stage`.

Feature: quick stage and amend

---

core/commands/commit.py

Enhancement: show diff stat when `show_commit_diff` is "full".

---

core/commands/fixup.py

- reset to original commit after fixup 
- fixup should be safe even if there are untracked files

Enhancement: reset to original commit after fixup

---

common/theme_generator.py
core/commands/inline_diff.py

close #829 
ThemeGenerator now understands the new json based color scheme (required dev channel ST).

Enhancement: support .sublime-color-scheme in inline diff view

---

core/commands/inline_diff.py

Fix: remove debug print

---

Default.sublime-commands
Default.sublime-keymap
GitSavvy.sublime-settings
common/interwebs.py
core/exceptions.py
docs/gitlab.md
git_savvy.py
github/commands/add_fork_as_remote.py
github/commands/commit.py
github/commands/configure.py
github/commands/create_fork.py
github/commands/open_on_remote.py
github/commands/pull_request.py
gitlab/commands/__init__.py
gitlab/commands/configure.py
gitlab/commands/merge_request.py
gitlab/commands/open_on_remote.py
gitlab/git_mixins/__init__.py
gitlab/git_mixins/remotes.py
gitlab/gitlab.py

Hi guys, had some time to hack this up today; which, if accepted, would be the beginning of implementing PR #363

Gitlab merge-request review support

---

docs/debug.md

Docs: Add doc for setting PATH environment

---

common/util/file.py

[Internal] Exception

---

github/commands/pull_request.py

These commands have renamed earlier

Fix: gs_push_and_create_pull_request has renamed

---

core/git_mixins/ignore.py

Fix: use unicode to write .gitignore

---

common/util/view.py
core/commands/commit.py

Enhancement: do commit synchronously when commit_on_close is true

---

GitSavvy.sublime-settings
core/commands/blame.py
core/commands/log.py
core/commands/log_graph.py
core/git_mixins/history.py

Added two options `log_follow_rename` and `blame_follow_rename`.  The default values are set to `false`.
see #845

Enhancement: make following file renames optional

---

core/commands/log.py
core/commands/log_graph.py

follow only makes sense when file is provided

fix: follow only makes sense when file is provided

---

.travis.yml

As title. Homebrew has just renamed its python 3 formula as python. We'll try to install `python` or `upgrade` in traivs environment.

Internal: homebrew has renamed its python3 formula

---

core/commands/checkout.py
github/commands/pull_request.py
github/github.py
gitlab/commands/merge_request.py
gitlab/gitlab.py

as title, branch names could contain `#`

Fix: hash tag sign is a valid char for branch name

---

common/theme_generator.py

Hotfixes should be submitted to `master` branch. As part of the PR process,
you will be asked to provide the information necessary to make that happen.
Pull requests on new features should be submitted to `dev` branch and will be
regularly merged into `master` after evaluations over an extended period of
time.

fix miss-spelliing in common/theme_generator.py

---

appveyor.yml

Just a quick PR to see if pip install in appveyor/windows can be easily fixed.

Appveyor pip install fix

---

docs/README.md

I felt settings and key-bindings were always a bit unclear; hopefully this change helps a bit.

Docs: clarify settings & add key bindings section

---

common/util/log.py
core/git_command.py

Fix: make log panel more asynchronous

---

github/commands/pull_request.py
gitlab/commands/merge_request.py

branch name such as `pull-request-900` is pretty much useless. It is more useful to use `{username}/{source_branch_name}`.

Enhancement: use a more meaningful branch name in PR review

---

core/git_mixins/history.py

fix #878
@mercurykd could you test if this fixes your issue?

Fix: replace single backslash by forward slash

---

core/interfaces/tags.py

Fix: it is incorrect to assume hash length = 8

---

core/commands/tag.py
tests/test_smart_tag.py

Some unit tests are also added.

Enhancement: support prefix in prerelease smart tag

---

Default.sublime-commands
core/commands/checkout.py
core/commands/log.py
core/git_mixins/checkout_discard.py

close #914 
1. added `git: checkout current file at commit` in the command palette
2. added a new action `checkout current file at commit` in log panel for the current file.

checkout current file at commit

---

core/commands/commit.py

fix #920
Should we patch this on master and release a patch release?

Fix: Pedantic commit checks allows comment on 2. line

---

common/util/parse_diff.py
core/commands/commit_compare.py
core/commands/diff.py
core/commands/log.py
core/commands/log_graph.py
core/git_command.py
core/git_mixins/active_branch.py
core/git_mixins/remotes.py
core/interfaces/rebase.py
setup.cfg

Fix lint errors. W503 and W504 are too hard to fix, I had to just ignore them.
See https://github.com/PyCQA/pycodestyle/issues/498 for some discussions.

Fix: lint errors

---

core/commands/cherry_pick.py

Fix: cherry pick set status error on done

---

github/github.py

Fix: pagination regex

---

core/git_command.py

Include A traceback when an exception happens and we don't handle it

---

core/settings.py

Typo: Read view settings, not window settings

---

Default.sublime-commands
core/commands/push.py
core/git_mixins/remotes.py

Add `git push --force-with-lease`

Feature: git push --force-with-lease

---

core/git_command.py

Fix: use fallback encoding to decode stderr

---

core/commands/push.py

close #975
use the selected branch instead of the current branch.

Fix: push selected non-tracking branch

---

core/commands/commit.py
core/commands/quick_commit.py

Enhancement: add status message when commiting

---

core/commands/commit.py

This function was updated in https://github.com/divmain/GitSavvy/pull/970
But it opened a possibility that a user may hit `c+enter` repeatedly very quickly to trigger the commit action more than once. This PR closes this possibly by adding a checker.
@stoivo I will make a release once this is merged. Thanks.

Fix: do not allow to commit twice

---

core/commands/status_bar.py

This will allow the status bar to be updated when using [Terminus](https://github.com/randy3k/Terminus).

Fix: update status bar when the view is a widget

---

README.md

Fix: typo in remote address

---

core/commands/quick_commit.py

@stoivo it is a bug introduced by the last release. Let's make a quick release for this one.
close #996

Fix: GsQuickCommitCommand is a WindowCommand

---

core/commands/commit.py
core/git_command.py

use the idea of https://github.com/SublimeGit/SublimeGit/issues/73#issuecomment-292795958 to honor the `prepare_commit_msg` and `pre_commit` hooks
close #161
also check "nothing to commit"
close #980

Enhancement: honor prepare_commit_msg and pre_commit hooks

---

core/commands/quick_commit.py

Fix #1000 
1000! What a great milestone.
@stoivo Sorry for the bug. We will need to release another hot fix release.

Fix: GsQuickStageCurrentFileCommitCommand is also a WindowCommand

---

core/commands/status_bar.py
core/git_command.py

Enhancement: offer initialization for repo_path

---

Default.sublime-commands
core/commands/init.py

With this simple change, git submodules are cloned so they can be used right away.

Clone git submodules

---

common/util/log.py
core/git_command.py

to fix live_panel_output not showing panel until command is complete
fix #1021

Make live panel output optionally sync

---

core/commands/diff.py

Fixes: Basically undefined behavior if you (hH)unk being on the top of the file. See the commit message https://github.com/divmain/GitSavvy/commit/61e442a24515a612a3e70c56a98bfd66ef7ae694
Fixes: After (hH)unking the cursor was misplaced. I just invoke the navigate command and I think it's 👌

Fix and improve diff view

---

core/git_command.py

close #1020
as title, sanitize ansi sequences

sanitize ansi sequences

---

core/commands/checkout.py

Restore: Checkout file at commit will show commit panel

---

.gitattributes
common/ui.py
core/interfaces/status.py
setup.cfg
tests/mockito/__init__.py
tests/mockito/inorder.py
tests/mockito/invocation.py
tests/mockito/matchers.py
tests/mockito/mock_registry.py
tests/mockito/mocking.py
tests/mockito/mockito.py
tests/mockito/signature.py
tests/mockito/spying.py
tests/mockito/utils.py
tests/mockito/verification.py
tests/parameterized/__init__.py
tests/parameterized/parameterized.py
tests/test_status_dashboard.py

The typical double-click we know from "Find in files" can be used to navigate
to files from the status dashboard via mouse.
🎆 🌃 🕺

Support clicking on filenames in the status view

---

core/commands/diff.py
tests/fixtures/diff_1.txt
tests/test_diff_view.py

This is similar to #1058 but for the diff view.  
I mentioned this in #1040.

 Make filenames in the diff view clickable

---

syntax/graph.sublime-syntax
syntax/test/syntax_test_graph.txt

I'm not super smart in this area. 
I just wanted to highlight the branch/tag thing in the graph view. After the fact, I thought maybe it's 'better' to mark the whole line. But I couldn't get that to work ~without spending too much time~ at all, I basically have no idea.

Tag the line containing HEAD for styling purpopses

---

tests/test_graph_view.py

You pulled #1056 but I had these two test cases unpushed.

Add test cases for log graph view not showing the panel initially

---

core/interfaces/branch.py

This regression was caused by a refactor to LogGraphMixin (more details in related ticket)
fix #1072

Fix: branch graph for selected

---

tests/test_git/common.py

Basically again as the title.
Note that I'm not a fan of such tests. They basically test git behavior, and such a side-effecty approach doesn't scale at all.

Suppress subprocess window on Windows

---

core/commands/stash.py

Fix: Refresh UI after dropping stash

---

appveyor.yml
core/git_command.py

Fix the double output issue in #1070 
cc: @stoivo

Fix: remove the double log

---

core/commands/status_bar.py

Sublime widgets are e.g. the command palette, and the input box at the bottom.
For these views we generally do not need to update the status bar.
Views without a window are also now called transient. These are detached views
after close.

Do not update status bar for 'widgets'

---

core/commands/diff.py

As title. 
Extracted from #1036

Show `file_path` in title if given

---

core/commands/diff.py

As title. 
Extracted from #1075

Show `base..target` in prelude

---

core/ui_mixins/quick_panel.py

The observable side effect of the bug is that `git branch`, called via
`get_current_branch_name()`, is asked twice e.g. if you want to checkout a
branch.
Usually we fill in `selected_branch` with the current branch if not set, but
we of course don't need to do that if `ignore_current_branch` is True.
Also simplified `get_pre_selected_branch_index`.
Fixes #1109

Fix branch panel logic if `ignore_current_branch`

---

common/util/actions.py
core/git_mixins/checkout_discard.py
core/interfaces/status.py

- Show 'successfully discarded' message if actually successful.
- Optimize discarding multiple files
Fixes #1111

Fixup discard actions in status dashboard

---

core/interfaces/__init__.py

Do not close panel views when cycling dashboards

---

common/util/file.py

Hotfixes should be submitted to `master` branch. As part of the PR process, you will be asked to provide the information necessary to make that happen.
Pull requests on new features should be submitted to `dev` branch and will be regularly merged into `master` after evaluations over an extended period of time.

Fix: yaml.load deprecation warning

---

core/commands/checkout.py

We remember the last two checked out branches and select the previous one
on `git checkout`.
The workflow here is: You're first on `master`, then checkout a feature,
then checkout again, now `master` is pre-selected. After that the feature
branch is pre-selected, and so on.

Remember last checkouts

---

common/util/debug.py

It is very important imo to get feedback about what commands we actually run fast and simple. 
This PR logs something like this (if logging is enabled) directly to the console where we need it.
```
(D) [ 94ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
(D) [109ms] $ git stash list
(D) [5040ms] $ git push --set-upstream fork simple-logging:simple-logging
(D) [ 78ms] $ git status --porcelain -z -b
(D) [ 78ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
```
There is a small trick to preserve the state of `enabled` during hot-reloads.

Add simple git command logging to the console

---

core/interfaces/__init__.py

Fix: Restore dashboards

---

core/commands/inline_diff.py

We generally get down from 4 to 2 git calls per refresh. We esp.
get rid of the `git hash-object -w --stdin` which persists the
object in the database, but these are temporary objects which
probably often needs to get garbage collected later.
Do I miss something special here? 🤷‍♂

Optimize inline diff refresh

---

GitSavvy.sublime-settings
common/theme_generator.py
core/commands/log_graph.py
core/commands/log_graph_colorizer.py

Nobody can follow these graphs anyway 😦 
Well, let's fix that :grin:
🌶

Colorize the path to the next commit

---

common/theme_generator.py

Fixes #1179
Partially reverts 023a309

Apply `color-scheme` using relative path to theme

---

core/git_mixins/rebase.py

#1167 had a ✔️ but apparently we didn't check flake8 4 weeks ago. 🤷‍♂

Fix: flake8 errors

---

core/commands/status_bar.py

Related #1206 
Tested on both ST3 and ST4.

fix a status badge regression in ST 4

---

core/commands/stash.py

For visibility, flash where the user can find the undo information as well.

Refer the undo instructions in the flash message

---

core/git_command.py
core/interfaces/branch.py

Undo message after branch deletion

---

GitSavvy.sublime-settings
core/commands/log_graph.py
core/commands/log_graph_colorizer.py
core/parse_diff.py

Highlight fixup and squash target commits in the graph

---

popups/show_commit_view.html

Add help for "g" to show in graph in commit popup

---

core/commands/custom.py

Fixes #1212
There is technically no reason for a custom `Thread` class because
the default implements all features we need.
Rearrange the program so that running or not running in a separate
thread has the same features, t.i. setting a `status_message` or for
example `output_to_buffer` works in both cases now.
Especially, running `refresh_gitsavvy_interfaces` after the command
now works (#1212).

Simplify `gs_custom`

---

Default.sublime-keymap
core/interfaces/status.py
popups/log_graph_view.html

- Update `log_graph` help tooltip
- Add `[g]`to the dashboard for consistency

Final touches before 2.22.0

---

core/commands/diff.py

Update "cached" mode when reusing diff views

---

core/git_mixins/history.py
tests/test_repo_status.py

Fix flake8 errors coming from v3.8

---

core/interfaces/branch.py

The `force` argument was missing.

missing force argument

---

github/commands/pull_request.py
github/git_mixins/remotes.py

It is useful to set the upstream to the repo of the PR author because github lets repo admin push to the PR branch.

set upstream after pulling a PR

---

common/util/file.py

Hotfix for 2.24.1 
Fixes #1315

Catch possible errors when parsing ".tmLanguage" files

---

core/commands/next_hunk.py

Generally, the commands `prev_modification` and `next_modification`
already jump, so the `view.show` in `set_sel` was probably never needed.
That being said, the way we jump back likely overjumps because we call
`prev_modification` twice.  We thus revert exactly this second jump
using `dont_move_viewport`.
We slightly optimize the general jump using `show_region` to ensure
some context at the top or bottom of the view is visible.

Fix: Better viewport scrolling esp. when navigating back

---

core/commands/next_hunk.py

Jumping "back" was maybe too tricky implemented.  There is another bug
when we have two modifications at the end of a hunk.  Because we always
choosed the line start of `b` (t.i. `view.line(b).a` in the code) there
was a chance landed in another modification.
Keep it simple, and just use a different algorithm for jumping "prev".
Generally, we want to jump to the start of a hunk even when jumping
"up".  We now jump twice ging up but then just take the `a` part which
is now the first modification of the hunk we want.
In the third commit we refactor again for a generalized algorithm for both
back and forth jumping.  We now basically select the whole hunk we jump to.
Because we're lazy, we're still as efficient as before for jumping forth.
(Because we don't consume the complete hunk but stop …

Hotfix `gs_prev_hunk`

---

README.md
docs/README.md
messages/install.txt

Fixes #1342
We're too low-volume these days to have a chat room. 🤷

Remove references to gitter.im

---

common/ui.py
popups/blame_view.html
popups/diff_view.html
popups/inline_diff_view.html
popups/line_history.html
popups/log_graph_view.html
popups/show_commit_view.html
popups/show_file_at_commit_view.html
popups/stash_view.html
popups/style.css

Always place the popup at the top-left of the view.  Slightly modernize the styling, grouping and wording but there is room for further improvement.  Actually, we should not write the html but rather generate it from a simpler markup structure.
Before:

Slightly modernize css and popup placement

---

common/ui.py

Fixes #1363
We have two code paths actually when creating a new interface object
for an existing view.
1. The user uses a short-cut or any other binding to open a dashboard.
Then we reuse a possible given view using `focus_view` which in turn
fires `on_activated`.
2. The user just focuses such a view.  Then we receive an `on_activated`
event, and must ensure we `render` imperatively.
This patch here addresses 2.
The bug was introduced by f29a0c9 (Do not render dashboards twice on
resurrect).  Just reverting is not a fix but would lead the other bug
(rendering twice) open again.

Ensure dashboard views render on focus

---

docs/README.md

Hello :wave: thanks a lot for this awesome project, and keeping it alive.
This PR fixes some documentation references that had the wrong links, they should now point to the correct place.

Fixes stash docs references

---

common/global_events.py

There is a small behavior change here as well in that we don't trigger
if we *enter* a Terminus view anymore.

Rewrite when to ignore an activate event for clarity

---

.github/workflows/test.yml

- Remove Windows job because it is flaky.
- Remove Macos job because it is not needed.

Cleanup workflow jobs

---

common/util/actions.py
core/base_commands.py
core/commands/branch.py
core/commands/log_graph_rebase_actions.py
core/commands/push.py
core/utils.py

- Extract the new `show_actions_panel` helper to `utils` and use it
- Extract the new input handler `ask_for_local_branch`, and make `gs_delete_branch` a `GsWindowCommand` using it.

Refactor  `gs_delete_branch`

---

core/commands/commit.py

Use our `show_panel` abstraction in `commit.py`.  This hides the `lru_cache` trick for the `on_highlight` callback.

Use `show_panel` in `commit.py`

---

core/commands/commit.py

Fixes #679
Replaces #680
See also #557
On or before the first commit, generating the diff against "HEAD" for
"commit -a" or "HEAD^" for "commit --amend" fails as they don't point
to anything.  Catch such errors, generate the immutable empty tree sha,
and use it as the parent.

Improve committing the first commit

---

core/commands/log_graph_rebase_actions.py

Only showing the previous tip (`branch@{1}`) is a bit easier to read
than the full `--reflog`.  From there a user can easily diff against the
HEAD or reset HEAD to the previous state.
We move to the cursor to the previous tip using the `follow` feature. 
You can also toggle "all" to make the previous tip the top of the graph
view.

Add rebase action "Show previous tip of the branch"

---

gitlab/commands/configure.py
gitlab/commands/merge_request.py
gitlab/commands/open_on_remote.py

This fixes a (one! 😢) mypy error as well.

Snake case and define `__all__` for the GitLab modules

---

core/git_command.py
core/git_mixins/active_branch.py
core/git_mixins/checkout_discard.py
core/git_mixins/history.py
core/git_mixins/ignore.py
core/git_mixins/merge.py
core/git_mixins/rebase.py
core/git_mixins/remotes.py
core/git_mixins/rewrite.py
core/git_mixins/stage_unstage.py
core/git_mixins/stash.py
core/git_mixins/status.py
core/git_mixins/tags.py
core/interfaces/rebase.py
github/commands/add_fork_as_remote.py
github/commands/commit.py
github/commands/create_fork.py

General purpose is to reduce the type errors from mypy.  Introduces some awkward way to type check our mixins. 
Fixes some code/edge cases on the way.

Improve typechecking of our mixins

---

syntax/graph.sublime-syntax

Use a variable for the complex ascii art chars

---

core/git_command.py

Fixes #1458
In #1458 the user has a ".git" directory which only contains some
configuration files.  Naively validate gitdir candidates by testing if
they have a "HEAD" file which is mandatory according to the git
documentation:
https://github.com/git/git/blob/f9f2520108bab26a750bcbb00518dc27672cf0a2/Documentation/gitrepository-layout.txt#L130-L131
https://git-scm.com/docs/gitrepository-layout#Documentation/gitrepository-layout.txt-HEAD
See also git's `is_git_directory` function at https://github.com/git/git/blob/f9f2520108bab26a750bcbb00518dc27672cf0a2/setup.c#L339-L339

Validate gitdir candidates

---

.github/workflows/test.yml

Fix GitHub action which refuses to run on SublimeText 3 right now. Report: https://github.com/SublimeText/UnitTesting/issues/190
Run on Sublime Text 4 for now.

Test and fix github action

---

.github/workflows/test.yml

See https://github.com/SublimeText/UnitTesting/issues/190#issuecomment-850139071

Run tests against ST 3 and 4

---

core/commands/remote.py
github/commands/create_fork.py

Notable
- set the newly created fork as default you want to push to
- automatically select the protocol (e.g. "https") just like we do in "review PR"

Iterate on `github: create fork`

---

README.md
core/git_command.py
core/interfaces/rebase.py

fix rebase dashboard for git 2.34

---

core/commands/checkout.py
core/commands/log_graph.py

Offer "checkout --merge" if normal checkout fails

---

common/commands/debug.py

Snake case all public Sublime Text commands and define `__all__` for `debug.py`

Modernize `debug.py`

---

syntax/output_panel.sublime-syntax
syntax/test/syntax_test_output_panel.txt

Fix marking sha's in the middle of a word and add more tests.
E.g.:

Iterate output panel syntax 

---

core/git_command.py

- print which executable we use and its version.  
- minor rewording

Improve core debug info

---

.github/workflows/lint.yml
messages.json

- Use TrueBrain/actions-flake8 for flake8
- Use kaste/upgrade-messages-test-action to test `messages.json`

Update CI Github action

---

setup.cfg

Add "falsy" and "commitish" to the good words list

chore: add to codespell good words list

---

core/commands/log_graph.py
core/commands/show_commit_info.py
core/runtime.py
git_savvy.py

Notable:
- fix selection handling while browsing the graph view

Iterate `show_commit_info` panel

---

GitSavvy.sublime-settings
core/commands/reset.py
core/store.py

Closes #1523 
Mostly refactoring
Notable: 
- remember last used reset mode
- setting `use_reset_mode` now only defines the initially selected mode.  
A user can define a new mode too which gets appended to the list

Iterate reset commands

---

core/commands/log.py

Sublime Text calls `on_highlight` a second time on "done", t.i. with the same `idx` (or here: `commit`).  Because of that we have a race between `on_highlight` wanting to show the panel and `on_done` attempting to close it.
Limit the side-effects of `on_highlight` by applying `lru_cache`.  (We already solved that in our `show_panel` abstraction.)

Fix `LogMixin` not closing the commit info panel

---

common/util/view.py
core/git_mixins/tags.py
core/interfaces/tags.py
syntax/show_commit.sublime-syntax
syntax/tags.sublime-syntax

Closes #1543 
- Divide the local section into lightweight and annotated tags
- For annotated tags show a relative date.
- For remotes, only show additional tags not already available locally

Modernize tags dashboard

---

core/commands/log_graph.py

For example, the user fetched and sees that `origin/master` moved, you can now tell `master` to just move to `origin/master`.

Offer offline fast-forward if upstream is already ahead

---

core/base_commands.py

See the lengthy commit messages for details.

More robust `WithProvideWindow` mixin

---

common/ui.py
core/interfaces/status.py
core/interfaces/tags.py
tests/test_status_dashboard.py

- Implement TagsInterfaceCommand as abstract GsTextCommand
- Redo how we read out what the user selected (the tag, the commit).  Only rely on the rendered text. This is part of a series

Iterate on the interfaces (1/tags)

---

common/ui.py
core/commands/blame.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
core/interfaces/tags.py

The missing part is how we create, resurrect, just focus dashboards.  Basically the enerving misuse of `__new__`  and that we have a gate/`_initialized?` attribute in `__init__`.

Iterate on `ui.py` itself (4)

---

common/ui.py
core/interfaces/branch.py
core/interfaces/rebase.py
core/interfaces/status.py
core/interfaces/tags.py
tests/test_status_dashboard.py

Fixes #1623 
Notable: `on_create` is just `__init__` now, and `on_close` could be `__del__`.

Refactor `Interface` initialization and instantiating

---

core/git_command.py

Also fixes #1551
Not ideal that we cache so much here that a user might often need to restart Sublime Text if "git" could not be found or is too old.  But it is simpler and we want to avoid excessive test calls for now.

Allow arbitrary many git binaries and their versions

---

core/commands/log_graph.py
syntax/graph.sublime-settings
syntax/graph.sublime-syntax

T.i. remove the `|` before the date and author column:

Refresh graph design omitting the `|`

---

Default.sublime-commands
Default.sublime-keymap
core/interfaces/tags.py
core/ui_mixins/quick_panel.py

- Remove the "push --all" feature
- Don't ask for a remote to push to when there is only one

Small iteration on the tags dashboard

---

core/utils.py

Change one type ignore line because mypy update

---

core/commands/log_graph.py

Since we now have the used `git_version` at hand, we can choose which format we can use without guessing.

Remove date-format probing

---

core/git_mixins/status.py
syntax/dashboard.sublime-syntax

In the status dashboard we show some rebasing information but it was awkward designed.
Make it a bit better.

Restyle rebasing information in the status dashboard

---

core/interfaces/status.py

Basically prevent moving into the stash section while staging/unstaging etc.

Keep cursor in the file region when drawing

---

core/commands/inline_diff.py
core/commands/line_history.py
core/view.py

Teach `Line History` to open from the diff, inline-diff and historical files

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
Default.sublime-keymap
core/commands/commit.py
core/commands/diff.py

Allow unstaging and discarding directly in the commit message view

---

core/commands/custom.py
core/git_command.py
core/runtime.py

Add a timeout to every git call

---

core/git_mixins/tags.py
core/interfaces/tags.py

Fetch remote tags in parallel, and use a 20.0 timeout

Tune tags dashboard

---

common/commands/help.py
common/util/view.py
core/commands/diff.py
core/commands/inline_diff.py
core/commands/log_graph.py
core/commands/stash.py
core/git_command.py
core/runtime.py
github/commands/pull_request.py
gitlab/commands/merge_request.py

Workaround sublimehq/sublime_text#5772

Always open new views on the right side of the current view

---

core/git_mixins/active_branch.py
core/git_mixins/status.py
core/interfaces/branch.py
core/interfaces/status.py
core/interfaces/tags.py
core/store.py
syntax/dashboard.sublime-syntax
syntax/status.sublime-settings
syntax/test/syntax_test_dashboard.txt
tests/test_repo_status.py

Show recent commit sin the status dashboard

---

core/commands/checkout.py

Fix arg name from `gs_checkout_remote_branch`

---

Default.sublime-keymap
core/commands/_help_popups.py
core/commands/inline_diff.py
core/commands/show_file_at_commit.py

- Implement `[p]`revious/`[n]`ext revision navigation in the inline diff
- Implement `[g]` to goto the graph view
- Implement `O` to show the file at the current revision

Iterate the inline diff

---

Default.sublime-keymap
core/commands/_help_popups.py
core/commands/show_commit.py

Implement back and forth navigation for the "show commit" views; that includes the commit panel from the graph view.

Implement `[n/p]` for commit views

---

common/commands/help.py
common/util/view.py
core/commands/diff.py
core/commands/inline_diff.py
core/commands/line_history.py
core/commands/log_graph.py
core/commands/show_file_at_commit.py
core/commands/stage_diff.py
core/commands/stash.py
github/commands/pull_request.py
gitlab/commands/merge_request.py

Rename `get_scratch_view` to `create_stash_view` because that's what it is, and allow passing in arbitrary initial configuration for the new view because that looks nice.

Refactor `get_scratch_view`

---

core/commands/log_graph.py
tests/fixtures/log_graph_1.txt
tests/test_graph_view.py

Fixes https://github.com/timbrel/GitSavvy/issues/1364
Closes https://github.com/timbrel/GitSavvy/issues/494
Generally shorten the graphs to some "n" commits after the commit-of-interest (the `follow` setting).  
Also shorten the ASCII art ("the graph") if it gets too wide.

Iterate graph drawing

---

Default.sublime-keymap
core/commands/commit.py
core/commands/diff.py

Implement unstaging in all mode in the commit view

---

core/commands/diff.py
core/commands/show_file_at_commit.py
core/ui_mixins/quick_panel.py

Looks like mypy 1.4.0 fixed a bug!

Remove some type ignore comments after mypy upgrade to 1.4.0

---

core/commands/commit.py

We want to support especially `select_all` followed by `delete` because that makes the commit message empty so that the user can safely abort the commit process.
Since the commit view is a hybrid writable/read-only view this doesn't work because `select_all` selects the whole buffer leaving the cursor at EOF position which in turn switches the view to read-only mode.
We thus implement a helper, intercept the `select_all` calls, and just select the commit message.  We're cautious though, and only do this if nothing is selected and the cursor is within the writable message area.

Implement `select_all` helper for the commit view

---

core/git_command.py

As mypy gets smarter we can remove two ignore comments.

Remove two mypy ignore comments

---

core/base_commands.py
core/commands/pull.py

As it turns out I reimplemented the wheel as `ask_for_branch` supports remembering the last used value.

Use `ask_for_branch`'s `memorize_key` feature

---

core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py

To keep the cursor sane, compute the new commit hash for the rewritten commit and set `follow` to that.
Notes:
- We change `gs_log_graph_refresh` to a `GsTextCommand` which seems unrelated at first sight.  This is just done for to have a proper type of the first argument of `resolve_commit_to_follow_after_rebase`. (Classically, `resolve_commit_to_follow_after_rebase` would be in a "mixin".)
- The side-effects `follow_head` and `follow_new_commit` check if `self.view` is actually a `log_graph` as all these commands are actually generic enough to be called from elsewhere.

Follow the commit that got rewritten after a rebase

---

core/git_mixins/branches.py

We unconditionally ask for `ahead-behind:HEAD` in `get_branches()` which is okay unless HEAD cannot get resolved.  E.g. on a new repo without any commits, the initial branch "main" might get created and HEAD might then refer to "refs/heads/main" but this file does not exist as there are no commits yet.
Just run without `AheadBehind` in that case.
As this is a rare case call `for-each-ref` as before but check for the error to call it again without `ahead-before:HEAD`.  This is efficient for the 99.99% use-case.

Fix `get_branches` when HEAD cannot get resolved

---

core/commands/log_graph.py

This is a follow up to 20e78581 (Do not alter selection if in log graph's prelude).

Do not reset cursor if `assume_complete_redraw`

---

core/commands/log_graph.py

Since Sublime 4096 quick panels can receive modifier key and hence support committing with e.g. `ctrl+enter` basically for free.
Let `ctrl+enter` commit the item and keep the quick panel list open to quickly select another file.  (Or remove the just added one.)
This behavior cannot get advertised as there is no "help/preview" section for the quick panel as we know it from the `ListInputHandler`. Rel: https://github.com/sublimehq/sublime_text/issues/6257

Let `ctrl+enter` commit and keep the file list open

---

core/commands/cherry_pick.py
core/commands/fixup.py
core/commands/log.py
core/commands/log_graph.py
core/git_mixins/history.py
core/ui_mixins/quick_panel.py

Work-around sublimehq/sublime_text#6237

Tune timing between opening/closing a quick panel and an output panel

---

core/commands/log_graph.py

Concise menu entries for creating or deleting tags

---

Default.sublime-commands
core/commands/merge.py

Add "merge --continue" command for completeness

---

Default.sublime-keymap
core/commands/_help_popups.py
core/commands/log_graph_rebase_actions.py
tests/test_graph_walk_reflog.py

:eyes:  Add `N` and `P` bindings to add/remove previous tips of the current branch, basically to see older versions of the branch.  This is pretty sick.

Add `[N]/[P]` to walk the reflog of the current branch

---

core/git_mixins/ignore.py
core/interfaces/status.py
core/store.py
syntax/status.sublime-syntax

Show `skip-worktree` files in the status dashboard

---

core/runtime.py

Rel https://github.com/python/mypy/issues/17171

Add mypy ignore comment after mypy 1.10.0

---

core/git_mixins/tags.py
core/interfaces/tags.py
core/store.py

Do not show or fetch tags from remotes with --no-tag set

---

core/interfaces/tags.py
core/ui_mixins/quick_panel.py

Do not offer to push tags to `noTags`-remotes

---

Default.sublime-keymap
common/ui.py
core/interfaces/branch.py
core/interfaces/status.py
core/interfaces/tags.py

Bind [o] to open commits under the cursor in the dashboards

---

core/commands/blame.py
core/commands/checkout.py
core/commands/cherry_pick.py
core/commands/fixup.py
core/commands/log.py
core/commands/log_graph.py
core/commands/log_graph_rebase_actions.py
core/commands/show_file_at_commit.py
core/interfaces/rebase.py

These mostly point to code-smells I cannot fix quickly enough.

Fix new mypy errors

---

core/runtime.py

Always print the line contents as it just too confusing without it.

Tune friendly traceback

---

core/fns.py
core/utils.py
github/commands/configure.py

The main goal is to be sparse and to allow unsetting any values.  E.g. is the user chooses a remote but then sticks with the default branch, just persist the chosen remote name.  (etc.)  
There is also a showcase busy panel herein.

Modernize `gs_github_configure_remote`

---

core/git_mixins/status.py
syntax/dashboard.sublime-syntax
tests/test_repo_status.py

Add rebase hints to the status

---

Default.sublime-keymap
core/interfaces/status.py

Add `[P]` to pull in the status view

---

Default.sublime-commands
core/commands/__init__.py
core/commands/config.py

Adds "git: open config file" and "git: open exclude file".

Add commands to open the repo config and exclude files
